### ISSUE TITLE
PHP Export regex doesn't respect single quotes in labels

### ISSUE THREAD

**Issue by embolden** [elliotcondon/acf#191]
Below is a screenshot of my export currently:
![screen shot 2013-11-08 at 11 43 37 am](https://f.cloud.github.com/assets/1679978/1502622/78c46d8a-489d-11e3-8716-e2cd23869def.png)

Expected output:
![screen shot 2013-11-08 at 11 48 23 am](https://f.cloud.github.com/assets/1679978/1502654/16d8d5e2-489e-11e3-95f3-d59d46c0cd48.png)

It looks like the regex in `acf/core/controllers/export.php` on line 387 is the culprit.

**Comment by elliotcondon** [comment]
Hi guys

This has been fixed in ACF PRO and will make its way into ACF5 when released
