### ISSUE TITLE
While loop skipping first item in has_sub_field

### ISSUE THREAD

**Issue by TwisterMc** [elliotcondon/acf#258]
I set up a repeater field for images. Then, in the template, I first check to see if they exist, which they do and there are four of them. I then do a while loop to output them, but at that point, there are only three. The first one has gone missing.

Code:
```
<?php if (has_sub_field('carousel_images' )): ?>
    <!-- If I var dump the the carousel_images here, there are four of them. Which is correct. -->
    <div class="slides">
        <?php while (has_sub_field('carousel_images' )):  // get carousel images
        // If I var dump the the carousel_images here, there are three of them. Which is incorrect. The first image is missing.
            $attachment_id = get_sub_field('recipe_image');
            $size = 'carousel-large'; // (thumbnail, medium, large, full or custom size)
            $image = wp_get_attachment_image_src( $attachment_id, $size );
            ?>
            <div class="slides-slide">
                <img src="<?php echo $image[0]; ?>" width="760" height="372" alt="" />
            </div>
        <?php endwhile; ?>
    </div>
<?php endif; ?>
```

We ended up rewriting the code and pushing the images into an array first then used a foreach loop instead of a while loop and it worked.

**Comment by dajocarter** [comment]
The problem is the `if (has_sub_field('field_name'))`. Change this to `if (get_sub_field('field_name'))` and it will work.

**Comment by elliotcondon** [comment]
Hi @TwisterMc 

Please make use of the latest loop functions:
http://www.advancedcustomfields.com/resources/functions/have_rows/
