### ISSUE TITLE
Error when you click publish with group name blank

### ISSUE THREAD

**Issue by everaldomatias** [elliotcondon/acf#339]
I found the following problem: (WP 4.0+ last ACF)

When I click publish the group of fields and forget the group name blank, I can not publish because the publish button is inactive and the loading is running endlessly.

Watch a print:

![print-acf](https://cloud.githubusercontent.com/assets/1918474/5164858/d0b24bd2-73c3-11e4-83b2-c6dd33c6ee94.jpg)

With that all fields that have created are lost.

**Comment by hbarudin** [comment]
Bump on this. Just encountered and wanted to make sure it was recorded.

**Comment by elliotcondon** [comment]
Hi guys.

I've just tested this, however, an alert appears like so:
![screen shot 2015-12-07 at 10 43 54 am](https://cloud.githubusercontent.com/assets/2296425/11616451/810c94da-9ccf-11e5-9000-0ec848f73685.png)

Can you please check your console log for any JS errors when saving the group?

**Comment by hbarudin** [comment]
Hi -
I see the alert as well; but when I dismiss the alert, the 'Publish' button is still in a disabled state, so I can't then re-trigger the action (see screenshot and motion capture below). I see no JS errors in the console at any step of the process.

<img width="300" alt="screen shot 2015-12-07 at 10 02 19 am" src="https://cloud.githubusercontent.com/assets/1155458/11630054/a28a07ec-9cc9-11e5-9e33-92742e455691.png">

![disabled](https://cloud.githubusercontent.com/assets/1155458/11630088/d3e67ab4-9cc9-11e5-858f-ce37cac0caec.gif)

**Comment by elliotcondon** [comment]
Hi @hbarudin 

Thanks for the gif, I'll have this sorted ASAP

**Comment by elliotcondon** [comment]
Hi guys

This has now been fixed - v4.4.4
