### ISSUE TITLE
PHP Notice

### ISSUE THREAD

**Issue by alexeightsix** [elliotcondon/acf#349]
Version 4.3.9 | By Elliot Condon | View details

Deleted a field
URL: http://xxx.ca/rm/wp-admin/post.php?post=61&action=edit&lang=en

Notice: Undefined variable: field in /home/xxxxxx/public_html/rm/wp-content/plugins/advanced-custom-fields/core/fields/_functions.php on line 525

Warning: Cannot modify header information - headers already sent by (output started at /home/xxx/public_html/rm/wp-content/plugins/advanced-custom-fields/core/fields/_functions.php:525) in /home/xxx/public_html/rm/wp-includes/pluggable.php on line 1178

**Comment by bruno-barros** [comment]
The `$field` variable is not present.
`wp_cache_delete( 'load_field/key=' . $field['key'], 'acf' );`
Commenting this line stops the error message.

**Comment by sarahbethfederman** [comment]
changing $field['key'] to the $field_key variable passing into the function worked for me. 

This really should get fixed though, it's been reported over a year ago previously.

**Comment by elliotcondon** [comment]
Thanks guys. I'll release a version soon with this fix. Please pull the latest code from github to fix this issue for now

**Comment by sarahbethfederman** [comment]
Oh I see it from 6 days ago! Awesome, thanks!
