### ISSUE TITLE
Bug display date input

### ISSUE THREAD

**Issue by usb248** [elliotcondon/acf#374]
Hi,
I use the recent version of ACF and input date is very ugly ... (On WP 4.1.1)
I let you see ... (i'm on last version of FF with Windows 8.1)
![screenshot](https://cloud.githubusercontent.com/assets/7659927/6770482/6a806910-d0c1-11e4-93b0-155aaf31290c.png)

How i can solve this display bug ? Or, maybe, when is the next update for this input .. ?

**Comment by luancuba** [comment]
@usb248 apparently, any script that is being included in the admin and is causing conflict.

**Comment by elliotcondon** [comment]
Hi @usb248 

Is it possible that your theme / another plugin is adding a custom date picker script?
Can you please setup a blank WP with only ACF, test it, and then add  in plugins one by one until the UI issue occurs

**Comment by usb248** [comment]
Yes, it was option tree plugin... I replace this by acf option page feature. :)
