### ISSUE TITLE
Image file size limit less than 1 MB not working

### ISSUE THREAD

**Issue by arippberger** [elliotcondon/acf#381]
Receiving this error when trying to upload files less than 0.75 MB (31 KB, 156 KB, etc): "File size must must not exceed 0.75 MB"

It appears the file size limit does not work if a decimal value less than 1 is provided (0.5, 0.25, 0.75, etc. do not work, 1.25, 1.5, 2.5 do work).

**Comment by DaveG43** [comment]
Having the same issue.

**Comment by elliotcondon** [comment]
Hi guys

What version of ACF is this error occurring on?

**Comment by DaveG43** [comment]
The latest version for me. 5.2.7

**Comment by elliotcondon** [comment]
Hi @DaveG43 

Thanks mate. Can you export your field group so I can see the image field's settings?

**Comment by DaveG43** [comment]
Here you go.

    if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array (
	'key' => 'group_5591ddd2daa9d',
	'title' => 'Project Info & Images',
	'fields' => array (
		array (
			'key' => 'field_5591df4e34b34',
			'label' => 'Year',
			'name' => 'year',
			'type' => 'text',
			'instructions' => 'Add year of completion eg. 2015',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 2015,
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5591de2281781',
			'label' => 'Images',
			'name' => 'images',
			'type' => 'gallery',
			'instructions' => 'Attach images for the projects gallery here.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 1,
			'max' => 5,
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => 2000,
			'max_height' => '',
			'max_size' => '0.5',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'project',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
    ));    

    endif;

**Comment by elliotcondon** [comment]
Thanks @DaveG43 

I'll do some testing today and get back to you with an answer

**Comment by elliotcondon** [comment]
Hi @DaveG43 

I've made some changes to some internal functions which should fix the issue with decimal places in filesize restrictions.

Can you please edit the api/api-helpers.php file and replace the following 2 functions:
```
/*
*  acf_get_filesize
*
*  This function will return a numeric value of bytes for a given filesize string
*
*  @type	function
*  @date	18/02/2015
*  @since	5.1.5
*
*  @param	$size (mixed)
*  @return	(int)
*/

function acf_get_filesize( $size = 1 ) {
	
	// vars
	$unit = 'MB';
	$units = array(
		'TB' => 4,
		'GB' => 3,
		'MB' => 2,
		'KB' => 1,
	);
	
	
	// look for $unit within the $size parameter (123 KB)
	if( is_string($size) ) {
		
		foreach( $units as $k => $v ) {
			
			if( substr($size, -2) === $k ) {
				
				$unit = $k;
				$size = substr($size, 0, -2);
					
			}
			
		}
		
	}
	
	
	// calc bytes
	$bytes = floatval($size) * pow(1024, $units[$unit]); 
	
	
	// return
	return $bytes;
	
}


/*
*  acf_format_filesize
*
*  This function will return a formatted string containing the filesize and unit
*
*  @type	function
*  @date	18/02/2015
*  @since	5.1.5
*
*  @param	$size (mixed)
*  @return	(int)
*/

function acf_format_filesize( $size = 1 ) {
	
	// convert
	$bytes = acf_get_filesize( $size );
	
	
	// vars
	$units = array(
		'TB' => 4,
		'GB' => 3,
		'MB' => 2,
		'KB' => 1,
	);
	
	
	// loop through units
	foreach( $units as $k => $v ) {
		
		$result = $bytes / pow(1024, $v);
		
		if( $result >= 1 ) {
			
			return $result . ' ' . $k;
			
		}
		
	}
	
	
	// return
	return $bytes . ' B';
		
}
```

Let me know if this fixes the issue

**Comment by DaveG43** [comment]
Hi Elliot, just a quick test and elements <0.5MB uploaded fine. 
I did try one that was 510kb and was surpised that it uploaded. But then trying one with 550kb I did get the error message: File size must must not exceed 512 KB.
So putting 0.5MB was close but not exact (Just mentioning so you know).
Anyway, suits my purposes for now. Thank you!

**Comment by elliotcondon** [comment]
Hi @DaveG43 

Thanks mate.
1MB = 1024KB, so 0.5MP = 512KB

These results seem perfect. Looks like this is solved!
