### ISSUE TITLE
Date picker display and return formats are confusing

### ISSUE THREAD

**Issue by arippberger** [elliotcondon/acf#389]
This may be an edge case but, as you can see from the attached image, it's not clear whether the date will be displayed as MM/DD/YYYY or DD/MM/YYYY when the day and the month are represented by the same number.

![screen shot 2015-05-05 at 3 54 54 pm](https://cloud.githubusercontent.com/assets/1673133/7482788/9303cb98-f33f-11e4-97f5-f4c7c10b4f18.png)

**Comment by elliotcondon** [comment]
Hi @arippberger 

Thanks for the issue report. The date setting shows the current day, just a coincidence that it was teh 5th of the 5th

Thanks
E
