### ISSUE TITLE
Acf_form validation and fill data

### ISSUE THREAD

**Issue by gnnpls** [elliotcondon/acf#391]
Hi,
I am using a repeated field on custom admin menu item page. When I sumbit my inputs they are being validated but not in ajax. They are submitted and then error validation messages appear without back button. 
These inputs are going to become user_meta. How I am going to show them again in the user when he want to display the form again?

**Comment by elliotcondon** [comment]
Hi @gnnpls 

Please note this github repo is for bug reports only, not support. Can you please either contact our support team here: http://support.advancedcustomfields.com/new-ticket

or create a forum topic here: http://support.advancedcustomfields.com/new-topic

Notes:

Can you please elaborate more about the issue?
- What version of WP?
- What custom admin menu item?
- Please paste any code which may help to understand the issue.

Cheers
E
