### ISSUE TITLE
.has-image IMG tag not visible in control panel

### ISSUE THREAD

**Issue by mikos** [elliotcondon/acf#393]
I'm using ACF on a client's website and they're removing images from the Media section in WordPress. Usually, this would cause ACF image fields to display a 30x30px square with the option to edit or remove the missing image. However, on Chrome this does not appear.

I was able to fix this by commenting out the `width: auto` on line 292 of input.css. It doesn't appear to have had any knock-on effects for me.

**Comment by elliotcondon** [comment]
Hi @mikos 

Thanks for the bug report. I'll be fixing this issue shortly and release a minor version

Thanks
E
