### ISSUE TITLE
Flexible Content with a lot of sections fails to save

### ISSUE THREAD

**Issue by zjrosen1** [elliotcondon/acf#394]
I had 10 layouts in one flexible content field with some repeaters as well inside. When I tried to add the 11th layout, the repeater field inside don't save. I see there is a similar problem here 

http://support.advancedcustomfields.com/forums/topic/cant-save-post-with-lots-of-custom-fields/

I've since seen that two radio fields are not defaulted "required" and "conditional logic". I didn't pay attention to this at first because I normally never use them but realized it seems like thats adding to the problem. However making a selection on the radio fields still doesn't let me save without getting a length of undefined error.

Also a more recent issue as someone as pointed this out in the latest release its occurring which I am on.

http://support.advancedcustomfields.com/forums/topic/uncaught-typeerror-cannot-read-property-length-of-undefined-2/

**Comment by elliotcondon** [comment]
Hi @zjrosen1 

Thanks for the bug report. I've replied ot the forum thread and will look into this issue shortly.

Cheers
E
