### ISSUE TITLE
[Image field] - JS / Uncaught TypeError

### ISSUE THREAD

**Issue by Oxonium** [elliotcondon/acf#395]
Hey !

First of all, thumbs up for what might be the best Wordpress plugin of all time :+1: 

I just have a recurrent problem in the back-end. An error is preventing me to select an image from an image field (or use the "visual" tab of a WYSIWYG for that matter). This error shows up directly on page load : 

```javascript
Uncaught TypeError: Cannot read property 'id' of undefined
```

The console error refers to load-scripts.php.

The "interesting" thing is that there is no error at all when adding a new custom post type entry. It occurs only on existing items.

My configuration : 

* Wordpress 4.2.2
* ACF 5.2.5

Keep up the good work and thanks a lot in advance for any reply,

Cheers.

**Comment by elliotcondon** [comment]
Hi @Oxonium 

Thanks for the report, however, this is not the place to report it. Can you please open this issue with either our support team here: http://support.advancedcustomfields.com/new-ticket/ or the community forum here: http://support.advancedcustomfields.com/new-topic

My advice is to first disable all other plugins / theme and test out the issue, then add the plugins back in until you hit the problem and then you will know what is causing the JS error

**Comment by yoeridekker** [comment]
I had the same problem, fixed it by including WP media upload function:
(I only needed it on the acf-options page)

function load_custom_wp_admin_style() {
	$screen = get_current_screen();
	if( strpos( $screen->base, 'acf-options' ) !== false ) wp_enqueue_media();
}
add_action( 'admin_enqueue_scripts', 'load_custom_wp_admin_style' );
