### ISSUE TITLE
`get_field` is not formatting jQuery date

### ISSUE THREAD

**Issue by redgluten** [elliotcondon/acf#397]
Currently `get_field` doesn’t seem to format a jQuery date field according to the format display option.

My DB format is `yymmdd` but whatever [jQuery date format](http://api.jqueryui.com/datepicker/#utility-formatDate) I’m using, `get_field` is always returning `yymmdd`.

Tested on Wordpress 4.2.2 with ACF 4.4.2.

**Comment by elliotcondon** [comment]
Hi @redgluten

ACF4 does not format the value when retrieving from the DB. Your 'date_format' is the format in which the value is both saved and loaded.

There is a setting for display format, however this is only used to enter the value.

Formatting the value on load is something that has been added in ACF5 (currently ACF PRO) and will be released as a free version soon.

Thanks
E
