### ISSUE TITLE
Usage of get_pages in ACF silently breaks meta_query in acf/fields/post_object/query/name filter for Post Object field type.

### ISSUE THREAD

**Issue by dfcowell** [elliotcondon/acf#401]
Referencing the [WordPress Codex - get_pages](https://codex.wordpress.org/Function_Reference/get_pages) entry:

> NOTE: This function will currently not retrieve pages using the 'meta_key' and 'meta_value' parameters in the $args array as described below. Until this is fixed in the WordPress codebase, you may want to use get_posts() instead.

I spent a good two hours tonight digging around the WordPress docs and ACF source code trying to find out why my filter caused ACF to return no results in the select list for my Post Object field.

Here is the filter for reference:

```php
function filter_post_object_silo( $args, $field, $post ) {

    $args['meta_key'] = '_wp_page_template';
    $args['meta_value'] = 'page-silo-sub.php';

    var_dump($args);

    return $args;
}
add_filter( 'acf/fields/post_object/query/name=silo', 'filter_post_object_silo', 10, 3 );
```

Eventually I narrowed it down to this code in `/core/fields/post_object.php`:

```php
			if( $get_pages )
			{
				$posts = get_pages( $args );
			}
			else
			{
				$posts = get_posts( $args );
			}
```

Proposed fixes would be either alerting the user somehow after the `$get_pages` check if they've populated the `meta_key` or `meta_query` indices of `$args` or simply using `get_posts()` instead.

Alternatively a note on the docs page (http://www.advancedcustomfields.com/resources/acf-fields-post_object-query/) would also be nice. :)

Also, a way to force usage of `get_posts()` would be awesome.

Thanks,
-Dan.

**Comment by elliotcondon** [comment]
Hi @dfcowell 

Thanks for the bug report. How strange that WP would remove this functionality...

The good news is that ACF PRO only uses get_posts, and ACF v5 will be rolling out soon with this fixed.

Cheers
E
