### ISSUE TITLE
Option Page Plugin

### ISSUE THREAD

**Issue by stephan-fischer** [elliotcondon/acf#404]
I have the newsest ACF Dev Version and would activate the Option Page Plugin.
Following error comes:

Fatal error: Cannot redeclare acf_set_options_page_title() (previously declared in C:\xampp\htdocs\xxx\wp-content\plugins\advanced-custom-fields-pro\pro\api\api-options-page.php:411) in C:\xampp\htdocs\xxx\wp-content\plugins\acf-options-page\acf-options-page.php on line 567

Best regards
Stephan Fischer

**Comment by elliotcondon** [comment]
Hi @stephan-fischer 

Your PHP error suggests that you have already activated the ACF PRO plugin.
Also activating the options page add-on will throw an error.

Please disable ACF (v4) and any add-ons such as options page.
ACF PRO already includes all premium add-on functionality

**Comment by stephan-fischer** [comment]
ok i payed extra :)
