### ISSUE TITLE
Add Media not Working in WYSIWYG field

### ISSUE THREAD

**Issue by rossjcooper** [elliotcondon/acf#406]
I have set up two custom fields within a group called sponsor_left and sponsor_right both WYSIWYG fields. All other editing functions work apart from the Add Media function. It opens the media browser it just doesn't add it to the editor.

![image](https://cloud.githubusercontent.com/assets/3597958/8255814/8e106884-169a-11e5-8f2f-fa931a3c640c.png)

![image](https://cloud.githubusercontent.com/assets/3597958/8255824/9f1e4556-169a-11e5-8bde-d6eade370489.png)

**Comment by rossjcooper** [comment]
I have just tried renaming the fields and also deleting one, neither have produced any useful results.

**Comment by elliotcondon** [comment]
Hi @rossjcooper 

Can you try first placing the cursor within the WYSIWYG field before clicking the add media button.
It is possible that the issue is due to the editor not being 'focused'.

Can you also try on an instal with no plugins activated?

Thanks
E
