### ISSUE TITLE
Add has_field() function

### ISSUE THREAD

**Issue by klihelp** [elliotcondon/acf#410]
Is it possible to add has_field() function?
Would be helpful for code readability as well.
In my case I would register a true/false field; but want to make sure that if does not registered than make variable default to true.

```
$show_archive_list = true;

$field = get_field('show_archive_frontpage', $idFrontpage);
// var_dump($field); // = false
// why $field = false is when field does not exists
$show_archive_list = $field;

```

**Comment by elliotcondon** [comment]
Hi @klihelp 

ACF will return `false` if a field value does not exist. This is to allow developers the ability to conditionally check if a value exists.

Why not write something like this:

`
if( get_field('show_archive_frontpage', $idFrontpage) ) {

} else {

}
`

**Comment by klihelp** [comment]
Can you see my above example, How would you deal with it?

```
$default_value = true;
$show_archive_list = $default_value;

$field = get_field('show_archive_frontpage', $idFrontpage);

// If field registered
 // $show_archive_list = $field;
// otherwise
 // $show_archive_list = $default_value;
```

**Comment by elliotcondon** [comment]
Hi @klihelp 

In this case you will need to get the formatted version of the value which will be returned as a string of '0' or '1'. If no value exists, the value will equal `null`.

So your code may look like this:
`
<?php 
	
$default_value = true;
$show_archive_list = $default_value;

$field = get_field('show_archive_list', $idFrontpage, false);

if( $field !== null ) {
	
	$show_archive_list = empty($field) ? false : true;
	
} 

 
  ?>
`

PLEASE debug this code line by line to test the returned value before post back if it deosn't work as expected. You can debug like so:
`

echo '<pre>';
	var_dump($field);
echo '</pre>';
`

**Comment by klihelp** [comment]
Sorry, but your example are not reflecting my example, you are missing to use the $default_value

**Comment by elliotcondon** [comment]
Hi @klihelp 

My code example does make use of the `$default_value`. I don't think I can make my example any clearer.

I think it is a good idea to add the has_field function, and I'll add this to my to-do.
The function you are referring to is an outdated one which was replaced with have_rows and is used to loop through repeater fields, not ask if an actual value exists.

Thanks
E

**Comment by klihelp** [comment]
Thank you!:)

I meant this:
```
if( $field !== null ) {
   // $show_archive_list = empty($field) ? false : true;
    $show_archive_list = empty($field) ? false : $default_value;
}
```

**Comment by elliotcondon** [comment]
Hi @klihelp 

On line 2, $show_archive_list is set to $default_value.

On line 6, we ask if the value is NOT null. If the value is not NULL, that means it exists in the DB and we should override $show_archive_list with it's value.

If no value was saved in the DB, line 6 will return false and the statement within will never run. This will leave $show_archive_list set to $default_value.
