### ISSUE TITLE
Change Field Name?

### ISSUE THREAD

**Issue by klihelp** [elliotcondon/acf#413]
Is it possible to change/update the Field Name slug without loosing the values to the old Field Name slug?

**Comment by elliotcondon** [comment]
Hi @klihelp 

ACF like WP uses the field's name to save / load data.
If this name is changed, ACF and WP will not be able to find the previous value.

It is possible to modify the DB and perform a find / replace to update meta_key within the postmeta table.
This will allow you to change a field's name (via the WP admin interface), then update the meta rows and change the meta_name to match the new field's name
