### ISSUE TITLE
Add Advanced Custom Fields for MENU ITEM from Wordpress

### ISSUE THREAD

**Issue by salvimateus** [elliotcondon/acf#418]
This opens up many possibilities:

- Adding icons on the menu
- Overview
- Images

**Comment by elliotcondon** [comment]
Hi @salvimateus 

Thanks for the feature request. I have this on my to-do and think it will be a great addition!

**Comment by salvimateus** [comment]
@elliotcondon I bought your plugin and it is wonderful! If you do this the more it will be perfect function! thank you :D

**Comment by elliotcondon** [comment]
:)
