### ISSUE TITLE
Add Advanced Custom Fields for create Custom WIDGETS

### ISSUE THREAD

**Issue by salvimateus** [elliotcondon/acf#419]
This opens up many possibilities for creating unlimited widgets and exporting in php to implement in wordpress themes.

**Comment by elliotcondon** [comment]
Hi @salvimateus 

Thanks for the feature request. This has already been added to ACF PRO and will soon make it to the free version (v5 release)

**Comment by salvimateus** [comment]
@elliotcondon After buying, I saw. Thank You!
