### ISSUE TITLE
RESET Button and DATA EXPORT of options page from theme

### ISSUE THREAD

**Issue by salvimateus** [elliotcondon/acf#420]

**Comment by elliotcondon** [comment]
Hi @salvimateus 

Thanks for the feature request. I'm not sure how this would look in the plugin.

Essentially, all you need to do is delete the wp_options rows where the option_name starts with 'option_'.

As for the export, would this work like the WP export tool?

**Comment by salvimateus** [comment]
@elliotcondon 

For example, I filled my page "theme options" in wordpress localhost.

And then I want to send the same values of these fields for production.

It could be through an xml or json specific from acf.

And the "reset" button would return to the "factory settings" Theme Options page.

**Comment by elliotcondon** [comment]
Hi @salvimateus 

Thanks for the clarification.

You might be interested in a plugin called WP Migrate PRO.
It is a great tool for pushing / pulling DB between installations. Very handy when developing locally / online.

I'll consider adding in an export tool, but I wonder if an existing WP export tool will export wp_option values. Have a search for such a plugin, I'm sure one exists.

The reset button would be quite handy, I'll consider adding it in.

Thanks
E
