### ISSUE TITLE
Feature Request: Relationship Field - Filter by page parent

### ISSUE THREAD

**Issue by addedlovely** [elliotcondon/acf#421]
Hey Elliot, thanks for the great work. I've got an idea of the 'Relationship Field'; If you select page as the post_type, would be really useful to have the an option to filter by page_parent.

**Comment by elliotcondon** [comment]
Hi @addedlovely 

Thanks for the feature request. 
I like the idea, but I'm not sure how the interface would allow for this, and also the possibility for page filters.

Maybe a filter to allow for an array of custom filters?

**Comment by addedlovely** [comment]
In most scenarios the filter by taxonomy field should be redundant for 'pages' ( there might be some weird edge case where some has a page taxonomy setup). Ideally that could change to a dropdown for selecting the parent page.

Filter would also be cool if the above is too fiddly for low use.

**Comment by elliotcondon** [comment]
Hi @addedlovely 

Yep, when a feature request is made, I must think of all the edge cases, no matter how small.
I think a filter with the ability to customize the filters would be awesome!

I'll add this to my to-do, but can't make any promises.

Thanks
E
