### ISSUE TITLE
Custom location rule :  grandparent page

### ISSUE THREAD

**Issue by joDelicious** [elliotcondon/acf#424]
Hello there !

It would be awesome to be able to specify a grandparent page for the ACF to show.
I have tried building a custom rule, but still without success...

Can anyone help ?

Thank you !

Johan

**Comment by elliotcondon** [comment]
Hi @joDelicious 

Thanks for the feature request.

I'm not sure this rule would be used as much as the others, and for now, I advise you to create a custom location rule.

If you are having any issues creating a rule, please post your issue on the support forum:
http://support.advancedcustomfields.com/
