### ISSUE TITLE
Validations do not fire when metabox is minimised

### ISSUE THREAD

**Issue by lukerollans** [elliotcondon/acf#425]
I've noticed a bug where validations will pass for fields within a metabox that is minimised when the validation should not pass

If I get time I'll try to open a PR for this :)

![acf-bug](https://cloud.githubusercontent.com/assets/4101096/8951617/c19cd21a-3601-11e5-8927-9f15d80e6c06.gif)

**Comment by elliotcondon** [comment]
Hi @lukerollans 

Thanks for the explanation and gif. Very clear.

I will soon be releasing ACF v5 which will introduce AJAX powered validation and will avoid this issue.

Thanks for the bug report, but I will consider this fixed for the time being. If possible, please consider upgrading to ACF PRO!

**Comment by lukerollans** [comment]
@elliotcondon should this bug still not be fixed incase AJAX does not work? Or does ACF depend on javascript/AJAX in such a way that it wouldn't work at all if javascript was disabled or otherwise didn't work that I'm not aware of?

**Comment by elliotcondon** [comment]
Hi @lukerollans 

I'm putting ACF4 issues on hold at the moment while I prepare ACF5 for release.

ACF4 validation is entirely JS. ACF5 has a completely new validation system which involves PHP + AJAX to ensure validation 100%.

Thanks
E

**Comment by lukerollans** [comment]
No probs, thanks for the responses
