### ISSUE TITLE
Term slug instead of term id in export file condition

### ISSUE THREAD

**Issue by ravinderk** [elliotcondon/acf#428]
@elliotcondon 
Any update on this, i still got this limitation.
http://support.advancedcustomfields.com/forums/topic/problem-with-php-export-using-post-taxonomy/

**Comment by elliotcondon** [comment]
Hi @ravinderk 

Thanks for the post.

This issue has been addressed and fixed in ACF PRO (v5) which will soon make it's way into the free wp.org version!
