### ISSUE TITLE
Add a little red star in fields editor for required fields

### ISSUE THREAD

**Issue by iDuuck** [elliotcondon/acf#434]

**Comment by luancuba** [comment]
Eu acho que o aviso quando o usuário clica em salvar sem preencher os campos obrigatórios já é o bastante. O que voce acha @elliotcondon ?

**Comment by luancuba** [comment]
I think the warning when the user clicks save without filling in the required fields is enough. What do you think @elliotcondon ?

**Comment by elliotcondon** [comment]
Hi @luancuba 

I'm not sure I understand the issue you are raising.
Can you please provide a screenshot and more explanation of the problem / solution?

Thanks
E

**Comment by iDuuck** [comment]
I don't have a problem. It's just an enhancement :)
I am using really much fields with ACF (some pages are powered *only* by using ACF) and I need to know if it's required or not (in the field editor, when composing fields) without opening up the field. Would make it much more easier.

What do you think?

**Comment by luancuba** [comment]
![screenshot-wordpress dev 2015-09-03 11-11-14](https://cloud.githubusercontent.com/assets/4856659/9660548/86a0a686-522c-11e5-966e-f0b617806435.png)

I think is it that you want, right? @iDuuck

**Comment by elliotcondon** [comment]
Hi @luancuba 

Aah, I see.

Nice one! I like it and I'll add it to my to-do
