### ISSUE TITLE
 Notice: Undefined index: options in advanced-custom-fields\core\api.php on line 987

### ISSUE THREAD

**Issue by atwellpub** [elliotcondon/acf#435]
I believe it's picking up on a site's field options registered via  ACFPro's export PHP. Errors dissapear when Pro is activated. They reappear when Pro is deactivated and Lite is activated. 

I'm wokring a lot with acf_add_local_field_group as well as register_field_group in a sandbox environment. 

Possibly related to this issue as well:
https://github.com/elliotcondon/acf/issues/412

**Comment by elliotcondon** [comment]
Hi @atwellpub

The function 'acf_add_local_field_group' does not exist in the free version of ACF.
Please change to 'acf_add_local_field_group' to 'register_field_group'
