### ISSUE TITLE
Date Picker field has no Save Format as indicated in the docs

### ISSUE THREAD

**Issue by wfsmith** [elliotcondon/acf#436]
http://www.advancedcustomfields.com/resources/date-picker/

The documentation above shows a "Save Format" option for changing the format in which the date is saved to the database, but this apparently no longer exists.  I am not sure which updated removed it but the docs should be updated.

Cheers.  Love the plugin.  Keep up the great work!

**Comment by elliotcondon** [comment]
Hi @wfsmith 

Thanks for the bug report. Yes, ACF PRO (v5) has removed the save_format option and only allows for return_format instead.

I'll be sure to update the docs with a v5 info soon

Thanks
E
