### ISSUE TITLE
ACF PRO : Plugin textdomain loaded too soon

### ISSUE THREAD

**Issue by Rahe** [elliotcondon/acf#439]
Hi,

The 'load_plugin_textdomain' or 'load_textdomain' function is called too soon, the plugin textdomain have to be loaded at 'plugin_loaded' action or 'init' so the translation plugin can change the the strings, or load other translation files.

Thank you

**Comment by elliotcondon** [comment]
Hi @Rahe 

Thanks for the issue report. That's a very good point, I'll add this to my to-do
