### ISSUE TITLE
Please disable acf-json creation upon sync

### ISSUE THREAD

**Issue by joelstransky** [elliotcondon/acf#443]
I feel the creation of a new acf-json file right after a sync is needlessly cumbersome since if it gets committed, other developers will be alerted to sync when there is really nothing to sync.
Please see my discussion here for details: http://support.advancedcustomfields.com/forums/topic/the-acf-json-workflow/

**Comment by elliotcondon** [comment]
Hi @joelstransky 

Thanks for the issue.
I like your idea and have replied to the forum thread, lets keep the conversation there for now, and I should be able to add this in.
