### ISSUE TITLE
Can't get WPML to work with ACF options page

### ISSUE THREAD

**Issue by schikulski** [elliotcondon/acf#444]
I've created an options page using the following code:

    if(function_exists('acf_add_options_page')) {

	acf_add_options_page(array(
		'page_title'	=> 'Settings',
		'menu_title'	=> 'Settings',
		'menu_slug'		=> 'settings',
		'capability'	=> 'edit_posts',
		'parent_slug'	=> '',
		'position'		=> false,
		'icon_url'		=> false,
		// 'redirect'		=> false,
	));
    }

And a lot of option fields using:

	if( function_exists('acf_add_local_field_group') ):
	acf_add_local_field_group(array (
		'key' => 'group_547c4e16c143e',
		'title' => 'Innstillinger: Priser & reservasjon',
    (...)
... and so on

This works great on my main language. And when I change language in the admin to the second language the fields are display as in my main language. But when I change any settings the same settings are changed on my main language. But I need the values to be different, but the fields to be the same.

I've added the ```my_acf_settings_default_language```and ```my_acf_settings_current_language```setting, but with the same result. 

How can I get WPML to work with my options page?

**Comment by elliotcondon** [comment]
Hi @schikulski 

Please remove any filters to modify the language such as 'my_acf_settings_default_language'. 
These are not needed for WPML compatibility.

It is possible that the issue is due to the field group being registered via PHP code, however, I think the field group should still work correctly.

Can you please contact our support team with login details so we can login and debug the issue?
http://support.advancedcustomfields.com/new-ticket/

Thanks
E

**Comment by schikulski** [comment]
Ah, removing the ```my_acf_settings_default_language```and ```my_acf_settings_current_language```filters actually did the trick. Guess misread [this article I found here](http://www.advancedcustomfields.com/resources/multilingual-custom-fields/)

**Comment by nisargindianic** [comment]
```
function acf_option_page_language_prefix() {
        if ( defined( 'ICL_LANGUAGE_CODE' ) ) {
            global $sitepress;
            
            $sitepress->get_default_language();

            if($sitepress->get_default_language() == ICL_LANGUAGE_CODE) {
                $lang = '';
            } else {
                $lang = ICL_LANGUAGE_CODE.'_';    
            }       

        } else {

            $lang = '';
            
        }
        return $lang;
    }

    $lang = acf_option_page_language_prefix();

acf_add_options_page(array(
            'page_title'  => 'Footer'
            'menu_title'  => 'Footer',
            'menu_slug'   => 'theme-footer',
            'post_id'     => $lang.'footer-settings',
            'capability'  => 'edit_posts',
            'redirect'    => false,
            'parent_slug' => 'theme-master',
        ));


$acf_lang = acf_option_page_language_prefix();

$data['settings'] = get_fields($acf_lang.'footer-settings');
```
this solution work like charm
