### ISSUE TITLE
Use remote URL as default value for image field type

### ISSUE THREAD

**Issue by atwellpub** [elliotcondon/acf#449]
I was wondering if it could be made possible for a locally hosted image asset to be the default value of a ACF image field. 

From what I can see it's completely powered by the media library, but it would be nice to bypass this for a non media library asset. 

What do you think?

**Comment by elliotcondon** [comment]
Hi @atwellpub 

Thanks for the issue report.

Can you clarify exactly what you are trying to do?
The image field value may only be a numeric number that points to an attachment ID.
It is not possible for it to be set as a custom URL.

Perhaps you can use an if/else statement to load the default value on the front end?

**Comment by atwellpub** [comment]
What exactly we are trying to do is, on first load, the image field reads a non-media-uploaded image as the default image. 

I can't imagine it being possible because of what you said unless ACF had an autouploader type engine which seems like it would be kind of complicated and unclean. 

I'm not sure how else a WordPress client would interpret a default value for an image. (We are using ACF to power template assets and we try to have the template repopuplated/setup.

**Comment by elliotcondon** [comment]
Hi @atwellpub 

Are you able to upload the default image to the WP library, then use some code to hook into the acf/load_field and assign the attachment ID to `$field['default_value']`

**Comment by atwellpub** [comment]
That might be what we have to do.
