### ISSUE TITLE
Conditional fields options don't get updated

### ISSUE THREAD

**Issue by amarsyla** [elliotcondon/acf#451]
Hello,

I just noticed a small bug when using multiple conditions for fields. I have a true/false, a radio button and another random field on my field group. I wanted to use the conditions to show my third random field when the first field is set to true, and the radio button is set to a certain value. When I add the second conditional for the radio button, its values show only 'checked'. In my case, I have five other values for that button, and they don't show up. You have to switch to another field, and get back to the one you want for its options to be updated. This is something small, but I thought it would be nice to mention.

Thanks.

**Comment by elliotcondon** [comment]
Hi @amarsyla 

Thanks for the bug report.
- Are you using ACF free or ACF PRO?
- what exact version?

Thanks
E

**Comment by amarsyla** [comment]
Thanks for your reply @elliotcondon .

I am using ACF PRO 5.3.0.

Thanks.

**Comment by elliotcondon** [comment]
Hi @amarsyla 

Thanks for the info.
I've done some recent work on the conditional logic rules UI, so it may be fixed already.
I'll do some testing and get back to you

**Comment by elliotcondon** [comment]
Hi @amarsyla 

I've just done some testing, and have found that he issue seems fixed.
I'll be releasing a new version later today (if all goes well), so please let me know if the problem is solved for you after upgrading
