### ISSUE TITLE
Placeholder field for SELECT fields in admin view

### ISSUE THREAD

**Issue by eballeste** [elliotcondon/acf#453]
Seems like a SELECT field will by default have a data-placeholder attribute with the value of "Select" assigned to it and I can't edit this value through the WordPress backend. 

On the flip side, it is possible to assign a placeholder when registering a SELECT field via code.

**Comment by eballeste** [comment]
Just noticed this is not the repository for the ACF Pro version, don't know where the appropriate channel to report this issue would be, sorry!

**Comment by elliotcondon** [comment]
Hi @eballeste 

Thanks for the issue.

In the future, you can post any questions on the forum or to our support team here:
http://support.advancedcustomfields.com/

As for your question, the placeholder is not yet a setting which can be edited via the UI. Perhaps I'll add this into a future version, but for now, this is not necessary

Thanks
E

**Comment by eballeste** [comment]
Alright, for anybody with this issue, good ol' js to the rescue...

```javascript
$('.acf-field-select select').data('placeholder', 'choose an option');
```

**Comment by eballeste** [comment]
Oh yeah, forgot to mention this is being used for a front-end form where changing the default placeholder was kind of important.

**Comment by elliotcondon** [comment]
Hi @eballeste 

Thanks for the reply.

Perhaps you could make use of the acf/load_field filter and add the 'placeholder' setting like so:

```
<?php

function my_acf_load_field( $field ) {
	
    $field['placeholder'] = 'choose an option';

    return $field;
    
}

add_filter('acf/load_field/type=select', 'my_acf_load_field');

?>
```

**Comment by eballeste** [comment]
Nice! That works, thanks!

**Comment by eballeste** [comment]
Nice! That works, thanks!

**Comment by david-treblig** [comment]
Mmm could this be re-opened? I always have to add this filter in every project I do and I find this tiresome. Since the code to use the placeholder text is already there in class-acf-field-select.php, why not include the field in the admin?

**Comment by eballeste** [comment]
@david-treblig, true, but just in case this doesn't happen, consider making a plugin that you can pop into the must-use plugins folder that simply contains all the hooks and filters you find yourself adding to every project, helps with sanity
