### ISSUE TITLE
When exporting field groups to PHP, add option for translation-ready output

### ISSUE THREAD

**Issue by amarsyla** [elliotcondon/acf#454]
Hello Elliot,

This week, I found myself in a situation that the field groups I had to export to PHP, had to be translation ready (wrapped in the __() functions, with my own text domain). Obviously and unfortunately, I had to do this manually for each label on the generated output by ACF. Would it be a good idea, that on the export page, to be a text value to add a text domain? So, if a text domain is added, the output will be translation ready. An example would be that instead of `label: Field Name`, it would be `label: __('Field Name', 'text_domain_here')`.

The reason I am posting this here, and not in your support forum, is that I may try to code this and contribute it to the repo, if you give me a positive answer.

Thanks for the great plugin.

**Comment by elliotcondon** [comment]
Hi @amarsyla 

Thanks for the feature request.
I have recently added this into ACF5 (ACF PRO) with the setting 'export_textdomain'
http://www.advancedcustomfields.com/resources/acfsettings/

Thanks
E
