### ISSUE TITLE
Considered adding support for wp_nav_menu meta?

### ISSUE THREAD

**Issue by jonathan-dejong** [elliotcondon/acf#463]
Hey Elliot!

I just read up on the walker class in WordPress from an article over at smashingmagazine.. decent read! 

Anyway, they showcase the use of the walker by adding custom meta to nav menu items (since they are a post type like anything else). I thought to myself
- Hmm.. I wonder if ACF supports this already, I've not checked. 

As it turns out ACF does not support it and I just figured I'd suggest it to you (or perhaps get to know why you don't intend to). I realise that ACF probably shouldn't create it's own walker class to show these fields but it could help out by doing all the work in the backend.. And then let the user create their own walker class and insert the meta fields as they see fit (like with any other situation really). 

Thoughts?

**Comment by elliotcondon** [comment]
Hi @jonathan-dejong 

Nice one. Sure, I'm happy to add in compatibility with nav menus.
There are a few things on my to-do first, but I'll add this one on too

**Comment by jonathan-dejong** [comment]
Nice :) 

Here's the link to the article.. might be useful 
http://www.smashingmagazine.com/2015/10/customize-tree-like-data-structures-wordpress-walker-class/
