### ISSUE TITLE
[ACF4] WYSIWG strips out inline javascript found in links. 

### ISSUE THREAD

**Issue by atwellpub** [elliotcondon/acf#466]
Heya I have a customer support ticket where the user is having issue adding an inline onclick javascript command into the source of her WYSIWG content:

```
<a href="javascript:launchCourse()">go go go</a>
```

I've verified the issue on test install:
http://screencast.com/t/cT3Zvf3F

I'm not sure what to do, but I want to help her get it solved. I've had no luck looking for a predocumented solution.

**Comment by elliotcondon** [comment]
Hi @atwellpub 

Can you please test this in the WP content editor. Does it work any different to the ACF WYSIWYG field?

I've just tested, and the WP editor converted the characters when in visual mode, and stripped out the href when in text mode.

**Comment by atwellpub** [comment]
I see, it is a WordPress default feature. I would love to be able to enable inline JS. Not sure on the arguments against it.

**Comment by elliotcondon** [comment]
Hi @atwellpub 

Thanks for the reply.

Me either. I'm not sure how to remove this functionality, and not sure if it's part of the JS, PHP or both
