### ISSUE TITLE
get_fields() returns empty when the fields have been inserted with the update_field function

### ISSUE THREAD

**Issue by robsonfgjunior** [elliotcondon/acf#468]
If I do:
```PHP 
get_field( 'some_field_name', $post->ID ); 
```
It returns the data well.

But if I do:
```PHP 
get_fields( $post->ID ); 
```

it returns an empty array.

What's interesting about it is that the `$post` in question wasn't updated using the Admin edit screen but the information was entered using the `update_field()` function.

I did it because I have an old website with thousands of posts so I wanted to migrate every old custom field to ACF, and used a little script to loop through every posts and then  `get_post_meta()` to read from the old metabox and `update_field()` to insert the data in the new ACF fields.

The information is displayed correctly in the backoffice and `get_field()` works, but `get_fields()` returns nothing.

Now if I edit one of these old posts in the backoffice and just hit the Wordpress "Update" button **without touching anything**, then the `get_fields()` function **magically starts to work**!

Seems to me that the `update_field()` function doesn't insert all the necessary information in the database for `get_fields()` to work, but does the job for the `get_field()` function.

**My question is:**
Is there a way for me to use the `get_fields()` function without having to manually Open and Update every old post in the backoffice?

I know I could do a `get_field()` call for every single ACF field that I have, but `get_fields()` was just a lot simpler!

**Comment by robsonfgjunior** [comment]
By they, I ran the script twice. The first time I used:
```PHP
update_field( $field_name, 'value', $post->ID );
```

And the second time I used the field_key copied from the backoffice as suggested in the documentation:
```PHP
update_field( $field_key, 'value', $post->ID );
```

And I got the same output from `get_fields()` either way.

The only thing that seems to fix it, is to Open and Update the post in the backoffice.

**Comment by elliotcondon** [comment]
Hi @robsonfgjunior 

Thanks for the email.

The issue is that when using update_field with a field_name, the field's key will not be saved as a reference value. Reference values are explained here: http://www.advancedcustomfields.com/resources/functions/update_field/

If you use the field_key in the update_field function, the reference will save, and the get_fields functionshould work correctly.

When you edit and save the post via the WP backend, the field keys are saved and the reference values are created, this is why the get_fields function will work.

All this said, even if the reference value doesn't exist, the custom field should sill be returned, that would be the expected result. I'll add this to my to-do and get all custom fields to be returned, irrelevant of the reference value.

**Comment by robsonfgjunior** [comment]
Thanks for the quick response elliot!

The thing is that I already tried to use the field key in the update_field function.
Here's my code:

```PHP
$posts = get_posts( array(
	'post_type' => 'address',
	'posts_per_page' => -1
) );

foreach ($posts as $p) {
	// Update country select box
	update_field( '2field_5626140c06dcd', get_post_meta( $p->ID, '_cda_pais_igreja', true ), $p->ID );
	
	// Update address text area
	update_field(  '3field_562615b606dce', get_post_meta( $p->ID, '_cda_morada_igreja', true ), $p->ID );
	
	// Update GPS text field
	update_field( '4field_562615e506dcf', get_post_meta( $p->ID, '_cda_gps_igreja', true ), $p->ID );
	
	// Update Image upload Field
	update_field( '7field_562616be02236', get_post_meta( $p->ID, '_thumbnail_id', true ), $p->ID );

}
```

Do you see anything wrong? I might be missing something.
After running this code this is the output I get from running individuals get_field calls:
```PHP
get_field( 'church_address', $p->ID );
get_field( 'church_gps', $p->ID );
get_field( 'church_country', $p->ID );
get_field( 'church_thumb', $p->ID );
```
outputs:
```
// Address
Rua Eduardo Augusto Pedroso, nº18 C  r/c 
1495-047 Algés
(próximo a estação de comboio)

// GPS
38.700631,-9.230640

// Country
PT

// Thumbnail ID
73784
```


But if if run this for the very same post:
```PHP
get_fields( $p->ID );
```
a print_r outputs this:
```
Array (
    [] => null
)
```

**Comment by robsonfgjunior** [comment]
OMG I feel so stupid! I've found the problem.
I was just copying the field_key by double clicking the string in the backoffice and didn't realised it was selecting more than it should, prepending the field number, so I as running this:
```PHP
update_field( '2field_5626140c06dcd' ...
```
Instead of this:
```PHP
update_field( 'field_5626140c06dcd' ...
```

Now the `get_fields()` works just as expected!
Sorry for wasting your time :)

**Comment by elliotcondon** [comment]
Hi @robsonfgjunior 

Thanks for the replies.

I was just about to sya, but you bet me to it, that your field keys are not valid.

A field key MUST start with 'field_'

If you are using changing the key, please add the '2' at the end, not the beginning.

All good, glad you solved it!
