### ISSUE TITLE
Add filter for admin preview size

### ISSUE THREAD

**Issue by klihelp** [elliotcondon/acf#469]
Can you add a filter for preview size in the admin?
I would like to match the admin with the front and show  the image preview in different sizes depending on cpt. A filter would be ok atm, because I could use similarly as the admin_post_thumbnail_size built-in filter.

```/**
		 * Filter the size used to display the post thumbnail image in the 'Featured Image' meta box.
		 *
		 * @param string|array $size         Post thumbnail image size to display in the meta box. Accepts any valid
		 *                                   image size, or an array of width and height values in pixels (in that order).
		 *                                   If the 'post-thumbnail' size is set, default is 'post-thumbnail'. Otherwise,
		 *                                   default is an array with 266 as both the height and width values.
		 * @param int          $thumbnail_id Post thumbnail attachment ID.
		 * @param WP_Post      $post         The post object associated with the thumbnail.
		 */
		$size = apply_filters( 'admin_post_thumbnail_size', $size, $thumbnail_id, $post );
```

**Comment by elliotcondon** [comment]
Hi @klihelp 

Can you please elaborate more on this request.
What field(s) would you use this for?

The image field already contains a preview size setting. This could be programmatically changed using teh acf/load_field function

**Comment by klihelp** [comment]
Ah, yes, for image field.
I got two custom post type, with two different image sizes; so filtering the preview size would be nice to match with the idea.

**Comment by elliotcondon** [comment]
You can find docs here: http://www.advancedcustomfields.com/resources/acfload_field/

Simply hook in via the field's type, name or key and print out the $field variable so you can see what you need to change.

Then you can look at the current admin screen from global variables + $_GET params, and configure the preview_size as you want. Please remember this filter is run every time the field is loaded including on the front end of your site. So you may only want to run this if is_admin()

**Comment by klihelp** [comment]
thanks for your help!
I was able to use this specific filter for my ```$field['name'] ='secondary_thumbnail_id'```

```$field = apply_filters( "acf/load_field/name={$field['name']}", $field );```
