### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Labyala** [elliotcondon/acf#470]
Hello,

in French translation po file, you translate "Other" like this 
#: ../core/fields/radio.php:102 ../core/views/meta_box_location.php:91
msgid "Other"
msgstr "Sections de l'admin WordPress"

i think it's better to translate with 
msgstr "Autre"

Thanks

**Comment by elliotcondon** [comment]
Hi @Labyala 

Thanks for the post.

Will do

**Comment by elliotcondon** [comment]
Hi @Labyala 

Thanks for the post.

Will do
