### ISSUE TITLE
Unfold of widgets not working with latest version

### ISSUE THREAD

**Issue by mikakaltoft** [elliotcondon/acf#471]
Hi

I am unable to unfold my clients widgets on his website with the latest version of the plugin.

Please see screenshot. I believe that shows the issue.

When I deactivate ACF it works just fine.

<img width="1213" alt="screen shot 2015-11-05 at 11 40 25 am" src="https://cloud.githubusercontent.com/assets/10320181/10966213/543a0838-83b2-11e5-927e-05fb4f4f41ee.png">

Sincerely,
Mika

**Comment by elliotcondon** [comment]
Hi @mikakaltoft 

Thanks for the bug report.

What version of ACF / ACF PRO are you using?
What is the issue in your screenshot?

Thanks
E

**Comment by mikakaltoft** [comment]
Hi Elliot

I apologize for the late response. We are using the latest version: Version 5.3.6.1

I can confirm that the issue persist.

Sincerely,
Mika

**Comment by elliotcondon** [comment]
Hi @mikakaltoft 

Thanks for the reply.

I've just attempted to replicate this issue but can't (with the same version).
I've added an image and file field to all widgets, but they open/close correctly with no JS errors.

Perhaps you have some conflicting JS code?
Perhaps from another plugin / field type?

**Comment by mikakaltoft** [comment]
Hi @elliotcondon 

Thanks for your reply.

I am not working for the client at the moment, so I will leave the issue as he doesn't mind. However, if I pick up the work again, I will look into it :-)

Thanks for your help!!
