### ISSUE TITLE
Wordpress Auto-Hyperlink plugin

### ISSUE THREAD

**Issue by fborgosano** [elliotcondon/acf#476]
Hello everyone. I have an automated Wordpress blog in wich it runs a plug-in called Auto-Hyperlink Urls. It's great, the only problem is that it works also on the YouTube links that, if they are hyperlinked and not in plaintext, the videos don't embed automatically. There's a way to modify the Auto-Hyperlink plugin?
Here the link: https://wordpress.org/plugins/auto-hyperlink-urls/

Thank you!

**Comment by elliotcondon** [comment]
This is the repo for Advanced Custom Fields, not auto-hyperlink-urls, I think you posted this statement in the wrong place,

**Comment by fborgosano** [comment]
Ops, sorry :-D

Il 27/11/2015 22:23, Elliot Condon ha scritto:
