### ISSUE TITLE
WYSIWYG deprecated method issue.

### ISSUE THREAD

**Issue by patlaughlin** [elliotcondon/acf#482]
Hi there,

I'm experiencing an issue where the WYSIWYG field type is failing to load the toolbar. I can see this error thrown on my local version. The local site's plugin version is a bit behind but my production copy is fully up to date (both WP and ACF) and i'm experiencing the issue there as well. Is this an issue on my side or ACF?

Thanks for any help. Love the plugin.

![image](https://cloud.githubusercontent.com/assets/1470818/11872009/19af55b4-a4a1-11e5-8acb-1080fa3f6020.png)

**Comment by patlaughlin** [comment]
For context. This is ACF 5.3.2.2 and WP 4.4.

**Comment by patlaughlin** [comment]
user error! thanks anyway.

**Comment by elliotcondon** [comment]
:)
