### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < with autocomplete and front-end form

### ISSUE THREAD

**Issue by gabyferman** [elliotcondon/acf#488]
I'm having issues with autocomplete, keeps giving me the Uncaught SyntaxError, I'm trying to do an ACF element that gets information from a postal code using geonames.org:

http://ws.geonames.org/postalCodeSearchJSON?placename=mx&username=demo&formatted=true&postalcode_startsWith=

The first field is for the postal code, where as you're typing will giving you postal code suggestions and then, after selecting your postal code will add the information to next input fields (state, city, street).

I've tried different solutions, but I keep getting the same error, here's a print screen:

<img src="http://i.stack.imgur.com/8GoEa.jpg" alt="" />

Right now I don't know if is something I'm not doing or a conflict with ACF, since I've used geonames and autocomplete for an advanced search plugin in other website, and autocomplete for a custom_post search in this same website.

**Comment by elliotcondon** [comment]
Hi @gabyferman 

Thanks for the post and screenshot.

Looking at your screenshot, I don't think this issue is related to the ACF plugin, but is due to the HTML markup of your page.

Please debug the error and fix the issue, it looks like you have not written the HTML comments correctly around your <html> tags

**Comment by gabyferman** [comment]
Hi,

yes, I thought of that and I made a test without the tags, just using the last one, without the IE specifics, and still didn't work. But I'm using the autocomplete on other part of the website to make a search field for my custom post 'cliente' and it works fine even with the IE tags.

<img src="http://i.imgur.com/GEDk1Tb.jpg">

On the screenshot you can see the field working and not reporting any errors. I'm not saying is the plugin, maybe is the way I'm doing the AJAX call, I tried different options and the error kept showing up :/

**Comment by elliotcondon** [comment]
Was your first screenshot showing HTML in the AJAX call, or HTML of the page?

Your AJAX should only ever contain JSON.

If you require help with debugging an issue with custom code, please contact our support team:
http://support.advancedcustomfields.com/new-ticket/

I will close this github issue for now
Thanks
E
