### ISSUE TITLE
Undocumented parameter of the_sub_field

### ISSUE THREAD

**Issue by netAction** [elliotcondon/acf#489]
According to documentation these functions have just one parameter. In *api/api-template.php* there seems to be a second parameter. Is it safe to use it when raw output is needed?

    function the_sub_field( $field_name, $format_value = true ) {

http://www.advancedcustomfields.com/resources/get_sub_field/

**Comment by elliotcondon** [comment]
Hi @netAction 

Thanks for the heads up, I'll add them in!
