### ISSUE TITLE
`$field_group['active']` not set when object cache is dirty

### ISSUE THREAD

**Issue by rask** [elliotcondon/acf#490]
I updated ACF PRO just now, and when loading fields I got loads of errors on `.../advanced-custom-fields-pro/core/location.php line 1244` telling how the `$field_group['active']` is not set and a field group cannot be instantiated on the page.

I tried to validate what was wrong, and seemingly the location for the field group could not be set properly at all (the `active` value did not exist).

After I flushed Redis Cache using 

    $ redis-cli
    $> FLUSHALL
    $> quit

then the field groups could be instantiated properly.

Is this something that "just happens" or is it fixable? Perhaps make field group loading bypass cache in case something like this happens?

**Comment by elliotcondon** [comment]
Hi @rask 

Thanks for the email.

I have a function called acf_get_valid_field_group.
This function ensures all the array settings exist, such as 'active'.

It looks like your caching has saved an earlier state of the field group, and was not flushed when the new setting was added.

I can potentially add a new action to the plugin which you can use to hook into and flush all caches, but this is the first time I have heard of this issue, so it may not be worth it.

Any thoughts?

**Comment by rask** [comment]
I will investigate. Did not reappear after the initial flush I made, so this may well be something specific on my system that I accidentally broke during development. In the mean time you may close this one, we can always open a new one if this is repeatable and it makes sense to fix it.

**Comment by elliotcondon** [comment]
Hi @rask 

Thanks for the reply, keep me posted
