### ISSUE TITLE
Ordenar lista de posts ( related type )

### ISSUE THREAD

**Issue by 3runoDesign** [elliotcondon/acf#492]
How can I change the order of the field list (related type)? Because the list is sorted by title.

**Comment by elliotcondon** [comment]
Hi @3runoDesign 

You can modify the order of item shown in the relationship field by hooking in and changing the query args:
http://www.advancedcustomfields.com/resources/acf-fields-relationship-query/

**Comment by 3runoDesign** [comment]
Hi @elliotcondon,
did not work.

See how I'm doing:

Fiel:
![screen shot 2016-02-05 at 6 05 13 pm](https://cloud.githubusercontent.com/assets/1563041/12859165/13642798-cc33-11e5-8052-3e5583d66bcd.png)

functions.php:
```php
function my_relationship_query( $args, $field, $post )
{
    $args['orderby'] = 'date';
    return $args;
}
add_filter('acf/fields/relationship/query/name=related_news', 'my_relationship_query', 10, 3);
```
Yet still the order is by name.

**Comment by elliotcondon** [comment]
Hi @3runoDesign 

Thanks for the reply.

This is starting to look like there is an overriding script in your theme or perhaps in a plugin which is modifying all get_post args via the pre_get_posts filter.

Are you using this filter within your theme? If not, can you please disable all other plugins, and maybe swap to the default theme just in case, and try again?

By default, the posts displayed in the relationship field should be ordered via their date just like they appear in the post's list.

**Comment by 3runoDesign** [comment]
@elliotcondon solved.

Thank you. :+1:

**Comment by elliotcondon** [comment]
Awesome!
