### ISSUE TITLE
add_action( 'media_buttons' ) has no impact on WYSIWYG editor

### ISSUE THREAD

**Issue by mikedidthis** [elliotcondon/acf#493]
Thank you for such a great plugin! 

I maybe missing something, using `add_action( 'media_buttons' )` seems to have no effect on the WYSIWYG editor.

```PHP
$this->loader->add_action( 'media_buttons', $plugin_admin, 'render_button' );
```

On the `the_content` editor, it renders fine: 

![](http://i.imgur.com/955AyK3.png)

On the `ACF WYSIWYG` editor is doesn't: 

![](http://i.imgur.com/mD46F4C.png)

Any advice would be appreciated.

Thanks

**Comment by elliotcondon** [comment]
Hi @mikedidthis 

Thanks for the issue report.

I can guarantee that ACF uses the do_action('media_buttons') code, so your action should be firing.
It looks like you have some sort of frame work ($this->loader), perhaps this is what is causing the issue?

What if you simply use add_action()?

**Comment by mikedidthis** [comment]
Hi @elliotcondon thank you for the quick reply. It was my own mistake:

```PHP
  public function render_button() {
    include_once( plugin_dir_path( dirname( __FILE__ ) ) . 'partials/admin-button.php' );
  }
```
Changed to `include` and works as expected. Sorry about that.
