### ISSUE TITLE
Make PHP field group exporting: output gettext methods

### ISSUE THREAD

**Issue by rask** [elliotcondon/acf#494]
Possible enhancement:

When exporting field groups as PHP code in the tools for the plugin, could it be possible to generate WordPress gettext methods (`__()`) for field names and descriptions? The person exporting the fields could optionally supply a text domain argument to use before exporting.

This would make translating field groups using gettext easier for the developers, as they do not have to go and edit the methods in by hand.

**Comment by elliotcondon** [comment]
Hi @rask 

Thanks for the question.

This feature has been added to ACF PRO, and will someday make it to the free version when I release ACF v5
