### ISSUE TITLE
Convert " to '

### ISSUE THREAD

**Issue by JanSchmidhofer** [elliotcondon/acf#495]
Im using acf to generate an xml file and i have a problem:

if i use " as value in a field, the xml output is broken. 
Is there a possibility to convert " into ' automatically ?

**Comment by elliotcondon** [comment]
Hi @JanSchmidhofer 

Sure, I would recommend that you perform this 'convert' during your export code.

**Comment by JanSchmidhofer** [comment]
Thanks, but im generating the xml directly with a custom page-template. But i found a solution on your website. I think this is the best solution: <?php echo str_replace('', '', get_field('my_field')); ?>
