### ISSUE TITLE
Radio & Check inputs not importing from json file

### ISSUE THREAD

**Issue by c9dd** [elliotcondon/acf#496]
Hi 

I'm having a major issue of the radio and check inputs are not importing along with their default choices.

I'm running a multisite instal of WP & have the pro version of ACF along with WPML. This had been working in the past without issue.

**Comment by c9dd** [comment]
It also seems the 'select' fields are not importing the values either

**Comment by elliotcondon** [comment]
Hi @c9dd 

Thanks for the issue.

Can you please provide more information such as version numbers and an exported file with instructions to test with?

**Comment by jmilne** [comment]
I have the same issue after updating to ACF Pro 5.3.4

**Comment by elliotcondon** [comment]
Hi guys,

If your issue is that a select, radio or chckbox 'choices' setting is unavailable after import, this issue has been fixed. A new version will shortly be released.

Please edit your api/api-helpers.php file and update the function:

```
function acf_decode_choices( $string = '' ) {
	
	// bail early if already array
	if( is_array($string) ) {
		
		return $string;
	
	// allow numeric values (same as string)
	} elseif( is_numeric($string) ) {
		
		// do nothing
	
	// bail early if not a string
	} elseif( !is_string($string) ) {
		
		return array();
	
	// bail early if is empty string 
	} elseif( $string === '' ) {
		
		return array();
		
	}
	
	
	// vars
	$array = array();
	
	
	// explode
	$lines = explode("\n", $string);
	
	
	// key => value
	foreach( $lines as $line ) {
		
		// vars
		$k = trim($line);
		$v = trim($line);
		
		
		// look for ' : '
		if( acf_str_exists(' : ', $line) ) {
		
			$line = explode(' : ', $line);
			
			$k = trim($line[0]);
			$v = trim($line[1]);
			
		}
		
		
		// append
		$array[ $k ] = $v;
		
	}
	
	
	// return
	return $array;
	
}
```

**Comment by jmilne** [comment]
You are **the** man Elliot. Cheers.

**Comment by c9dd** [comment]
Thanks. Sorry for the late reply, I expect it's a time zone thing :)

I also expect you don't need version numbers (all the latest ones) and exports any more.

**Comment by elliotcondon** [comment]
Thanks guys, looks like this is working for you.

Cheers
E
