### ISSUE TITLE
Multiple taxonomy selections bug

### ISSUE THREAD

**Issue by Autive** [elliotcondon/acf#499]
Hi @elliotcondon,

I'm having an situation where i need to add multiple items of the same taxonomy to one post. So at first i had a main repeater field where i did put an taxonomy select field under with the specific taxonomy as condition.

The issue is that every time i had more then 2 taxonomy fields the last changed field would override all the fields. So the value's of every field would de set to this value and losing their own settings (**after publish**). This and the following does make me believe this has something to do with the saving of these fields.

I did try the following things to debug the issues as far as possible for you:
- First of all no PHP errors or JS errors found in any of these tries.
- Changing the taxonomy select to radio/select/multi-select/etc. doesn't make any change.
- On change/select the value is stored correctly in the right (hidden) field and not changed for the other taxonomy fields.
- Setting these fields in a repeater field or not doesn't matter
- Creating two fields for **seperate** taxonomie's on one post doesn't cause any problems
- Enable or disabling "allow adding taxonomy or add taxonomy to post" doesn't matter
- Using Term ID or Term Object doesn't matter

I'm hoping you can find a solution for this problem, if there is anything i can do to help resolving this let me know!

Thanks in forward!

**Comment by elliotcondon** [comment]
Hi @Autive 

Thanks for the issue, but I don't provide support over github.
Can you please open a support ticket here: http://support.advancedcustomfields.com/new-ticket/

I would open one for you, but I don't know your email.

Please be sure to include your ACF version number, this is important to know what features area / are not available.
