### ISSUE TITLE
Official documentation : "compare" sign mistake

### ISSUE THREAD

**Issue by n457** [elliotcondon/acf#501]
Hi :)

There is a mistake in a code example of the official ACF date picker documentation : http://www.advancedcustomfields.com/resources/date-picker/

section "Query posts based on date", the "compare" signs must be interchanged.

Thanks for creating ACF

**Comment by elliotcondon** [comment]
Thanks @n457

I'll have this fixed this morning!

**Comment by n457** [comment]
👍
