### ISSUE TITLE
Relationship field bug

### ISSUE THREAD

**Issue by cloudstoneme** [elliotcondon/acf#505]
Hi Elliot,

If there is a relationship field used on the page and it has new value ready to save,  when save post, the filter added to "acf/update_value" will can't get correct post ID.

Maybe the problem is you did not use `wp_reset_query() `or `wp_reset_postdata()` after all custom post query. 

BTW: I'm using ACF Pro 5.3.5 with WordPress 4.4.2

**Comment by cloudstoneme** [comment]
Never mind, I just figured out that it's a revision problem.

**Comment by elliotcondon** [comment]
Hi @cloudstoneme 

All good, glad you found a solution
