### ISSUE TITLE
Any plan to support term meta?

### ISSUE THREAD

**Issue by cloudstoneme** [elliotcondon/acf#508]
Hi, 

Is there any pan to support term meta as it introduced since 4.4?

**Comment by elliotcondon** [comment]
Hi @cloudstoneme 

Yes, this is on the to-do, but unfortunately it is getting pushed back due to other priorities.

If your project requires the termmeta table for querying, perhaps you could hook into the acf/save_post action and save the values to your termmeta table via code.

This way, ACF will continue to work as normal, and you can also query the DB.

**Comment by yumyo** [comment]
+1 

Hi @elliotcondon, thank you for the advice. 
My problem, however, is that I have inherited a project with many ACF custom fields tied to categories and hundreds of them. So, I actually got 4671 rows in the options table and 1404 autoloaded options. 
Could the term meta solution still be an option in my case? If yes, is there a way to process them in batch?

**Comment by elliotcondon** [comment]
Thanks @yumyo 

Yes, termmeta is coming soon! Most likely in about 2 or 3 major versions time.
ACF saves wp_options values with autosave = 'no', however, in earlier versions this was not the case.

For now, please edit your DB and change all the autoload = 'yes' to 'no'

**Comment by utsavsinghrathour** [comment]
Sorry for hijacking this thread. But any news on this @elliotcondon?

**Comment by elliotcondon** [comment]
Hi @utsavsinghrathour 

Support for termmeta was added in v5.5.0.
Please note this github repo is for the older ACF v4 codebase.

ACF version 5 is in the middle of it's release, and can currently be obtained via early access or by purchasing ACF PRO:
https://www.advancedcustomfields.com/blog/acf-5-early-access/
https://www.advancedcustomfields.com/pro/
