### ISSUE TITLE
Location Field card in add-ons screen

### ISSUE THREAD

**Issue by matteocng** [elliotcondon/acf#516]
The add-ons screen includes the 'Location Field' card, linking to the now removed add-on repository. Not sure if we should hide such card for detected version >= 4.3.0 or just remove the Download button, noting that it's been built-in since 4.3.0. For < 4.3.0 we could hide it or perhaps change the link to the add-on [download page](https://wordpress.org/support/plugin/advanced-custom-fields-location-field-add-on).

**Comment by elliotcondon** [comment]
Hi @matteocng 

Thanks for the update, I'll take a look
