### ISSUE TITLE
Data is not saving

### ISSUE THREAD

**Issue by rahilwazir** [elliotcondon/acf#517]
I recently migrated from ACF 4 Pro to ACF 5 Pro and followed the following [migration guide](https://www.advancedcustomfields.com/resources/upgrading-v4-v5/).

But now whenever I save the ACF options page or update my post/page, the ACF field values wiped out after reload happens. The other native input values like title/content are intact.

I'm not sure why is it happening. I rolled back to ACF 4 and everything seems to work well.

**Comment by elliotcondon** [comment]
Hi @rahilwazir 

Can you please confirm that after installing ACF PRO, the DB upgrade was run, and all field's existed in the field group edit page, and on the post edit page.

Is it possible that your website contains some custom code that could prevent the save_post action from running? Or perhaps some code is modifying the $_POST data during save?

**Comment by rahilwazir** [comment]
Well I'm not sure the DB upgrade. ACF is distributed within our plugin.

Here's my scenario

I have ACF 4 with addons which is included programmatically in a plugin, not actived/listed as a plugin in WordPress.

So I did same for ACF 5, after including it, things are not working and ACF Field Groups page is always empty for me because fields are being registered through code.

**Comment by rahilwazir** [comment]
Here's my code before ACF 5:

```
// Check if ACF is used with another plugin, if not already called, use this one
if ( ! class_exists( 'acf' ) ) {
	define( 'ACF_LITE', true );
	add_filter( 'acf/settings/path', function () {
		return plugin_dir_path( __FILE__ ) . 'vendor/advanced-custom-fields/';
	} );
	add_filter( 'acf/settings/dir', function () {
		return plugin_dir_path( __FILE__ ) . 'vendor/advanced-custom-fields/';
	} );

	// Load the ACF Core
	include_once( plugin_dir_path( __FILE__ ) . 'vendor/advanced-custom-fields/acf.php' );

	// Repeater Add-On
	if ( ! class_exists( 'acf_repeater_plugin' ) ) {
		include_once( plugin_dir_path( __FILE__ ) . 'vendor/acf-repeater/acf-repeater.php' );
	}

	// Flexible Content Add-On
	if ( ! class_exists( 'acf_field_flexible_content' ) ) {
		include_once( plugin_dir_path( __FILE__ ) . 'vendor/acf-flexible-content/acf-flexible-content.php' );
	}

	// Options Page Add-On
	if ( ! class_exists( 'acf_options_page_plugin' ) ) {
		include_once( plugin_dir_path( __FILE__ ) . 'vendor/acf-options-page/acf-options-page.php' );
	}
}
```

After migrated to ACF 5:

```
if (!class_exists('acf')) {
	#define('ACF_LITE', true);

	add_filter('acf/settings/path', function () {
		return plugin_dir_path(__FILE__) . 'vendor/advanced-custom-fields-pro/';
	});

	add_filter('acf/settings/dir', function() {
		return plugin_dir_url(__FILE__) . 'vendor/advanced-custom-fields-pro/';
	});

	// Load the ACF Core
	include_once plugin_dir_path(__FILE__) . 'vendor/advanced-custom-fields-pro/acf.php';
}
```

Please comment.

**Comment by elliotcondon** [comment]
Hi @rahilwazir 

Thanks for the reply.

Can you create me a login for me to test?
If the fields are appearing on the edit screen, there must be a reason why they are not saving.

When are you registering the fields?
- in an action? If so, which one?

**Comment by rahilwazir** [comment]
> Can you create me a login for me to test?

Unfortunately the site is not live yet. But I can give you access through my local DNS, let me know if this works for you?

> When are you registering the fields?
   - in an action? If so, which one?

This is how I'm registering the fields. It's not called in any action hook and placed directly to the plugin file.

```
if (function_exists('acf_add_local_field_group') && function_exists('raw_data')
	&& function_exists('all_other_acf_fields')) {

	$raw_data = raw_data();
	acf_add_local_field_group( $raw_data );

	$acf_field_groups = all_other_acf_fields();

	if ( $acf_field_groups ) {
		foreach ( $acf_field_groups as $field_groups ) {
			acf_add_local_field_group( $field_groups );
		}
	}
}

/**
 * Add options page manually
 *
 * @since ACF 5
 */
acf_add_options_page();
```

`raw_data()` and `all_other_acf_fields()` just returns the array of fields.

Example of returning fields:

```
function raw_data() {
    return array(
        'id' => 'acf_book-meta-data',
        'title' => 'Book Meta Data',
        'fields' => array(
            array(
                'key' => 'field_54be7c15d492f',
                'label' => 'ISBN-10',
                'name' => 'inbm_isbn10',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
                'spree_id' => 'product_properties:isbn_10',
            ),
      ...
```

**Comment by elliotcondon** [comment]
Hi @rahilwazir

Thanks for the reply.

Got your email, but the URL does not load for me.

Can you try placing your ACF code with in the 'acf/init' action?
- It's possible that your code is running to early and not allowing ACF to save $_POST data correctly.
https://www.advancedcustomfields.com/resources/acfinit/

**Comment by rahilwazir** [comment]
@elliotcondon 

Well that didn't work.

I did install fresh ACF 5 and it worked well. I think there is problem with my plugin then. Leave it to me and I'll get back to you once I fix the issue.

**Comment by rahilwazir** [comment]
Ok I found out.

In the theme, a filter was hooked into `acf/update_value` filter, which was not returning the actual `$value` (`void`)

Closing this, not a core bug!

**Comment by elliotcondon** [comment]
Thanks for the follow up
