### ISSUE TITLE
remove margin if model has no title

### ISSUE THREAD

**Issue by manu09** [elliotcondon/acf#519]
Please remove the margin of `#post-body-content` if there is no visible form (e.g the title) inside.

![2016-04-02-111110_2720x1024_scrot](https://cloud.githubusercontent.com/assets/1057526/14225459/ca162f7e-f8c3-11e5-9dcc-2ca4d460965b.png)

**Comment by elliotcondon** [comment]
Thanks @manu09 

ACF doesn't contain an option to hide the post's title, can you please explain how you have done this?
If you have written custom code to do this, I suggest that you add the CSS alongside your custom code.

Thanks
Elliot

**Comment by manu09** [comment]
Oh, you're right I didn't notice it isn't ACF's fault. Is there any reason why you can't hide the title with ACF? I used CPT UI.

**Comment by elliotcondon** [comment]
Hi @manu09 

The title is an integral part of WP. Without it, you will have some WP issues
