### ISSUE TITLE
download ACF Pro via composer

### ISSUE THREAD

**Issue by timalbert** [elliotcondon/acf#524]
For the past couple weeks I have been having trouble downloading ACF Pro via composer. I assumed it was because ACF moved to ssl, but it does not seem to be working when I update the url. Below is my composer package.

```javascript
    {
      "type": "package",
      "package": {
        "name": "advanced-custom-fields/advanced-custom-fields-pro",
        "version": "5.3.3",
        "type": "wordpress-plugin",
        "dist": {
          "type": "zip",
          "url": "https://connect.advancedcustomfields.com/index.php?p=pro&a=download&k=xxx"
        }
      }
    }
```

**Comment by elliotcondon** [comment]
Hi @timalbert 

Thanks for the post.
I'm working on adding SSL to subsites at the moment.
I've had a setback with my host and will hopefully have this done in the next week

Thanks
Elliot

**Comment by timalbert** [comment]
Thanks - any plans on showing the best way to implement?

**Comment by elliotcondon** [comment]
Hi @timalbert 

I don't user composer, so I can't be of much help here.
I'm working with my host to setup https at the moment, please be patient
