### ISSUE TITLE
Feature: Show value of selectable field in collapsed state for layouts

### ISSUE THREAD

**Issue by macolo** [elliotcondon/acf#526]
The repeater field already does it: In collapsed state, the value of a field chosen by the user is displayed in the collapsed bar.

This would be also desirable for flexible content layouts.

Especially for pages with many fields configured (flexible content) this would greatly improve the editor's user experience, respectively his orientation.

**Comment by elliotcondon** [comment]
Hi @macolo 

The flexible content field contains an AJAX preview + PHP filter to modify the HTML displayed in the flexible content title. https://www.advancedcustomfields.com/resources/acf-fields-flexible_content-layout_title/
