### ISSUE TITLE
Request: Flexible Content / Repeater Layouts - Collapse All

### ISSUE THREAD

**Issue by macolo** [elliotcondon/acf#527]
It would be good if the editor could collapse all layouts at once, especially for CMS-style flexible content setups, where it is difficult to keep an overview over the different page blocks & content elements.

Maybe with a 'collapse all' toggle on the level of each flexible content field?

**Comment by elliotcondon** [comment]
Hi @macolo 

Thanks for the email.

I don't wish to add a toggle all button to the flexible content field just to avoid clutter on the page.
perhaps you could add this in with some custom JS.

Simply trigger a click event on each flexible content's layout title.
