### ISSUE TITLE
Sortable is not a function

### ISSUE THREAD

**Issue by lubieciastka** [elliotcondon/acf#528]
Hi,

We are using extensivly ACF solution ( we have even PRO version ) in one of our projects, however we are recently getting such an error:

`input.js:52 Uncaught TypeError: this.$values.unbind(...).sortable is not a function`

Unfortunatelly after some research on our side we have no idea what is causing this error, but it breaks tottaly our custom fields ( they are not visible at all ) Is this a well known error ? Or is this maybe something on our side ?

Thx

**Comment by elliotcondon** [comment]
Hi @lubieciastka 

Thanks for the bug report.

No, this is not a well known error, but suggests that there is a conflict between plugins enqueuing scripts, and that the jQuery ui portable library is not available on your edit page.

Either a plugin is preventing this script from loading, or the file is corrupt.
I would suggest disabling plugins 1 by 1, and also swapping to default theme to test what resolves the issue.

**Comment by rommyusa** [comment]
I ran into the same issue (using version 4.4.7). After investigating this, I realized that disabling the plugin Wordfence solved the issue.
