### ISSUE TITLE
Catchable fatal error

### ISSUE THREAD

**Issue by sky4git** [elliotcondon/acf#529]
I am getting Fatal error for some reason.
`Catchable fatal error: Object of class stdClass could not be converted to string in /wp-content/plugins/advanced-custom-fields/core/api.php on line 42`

Not sure what would be reason, as I am not even using any ACF function on the page?

Its fixed as per this post for now: [https://wordpress.org/support/topic/catchable-fatal-error-on-search?replies=2]

**Comment by elliotcondon** [comment]
Hi @sky4git 

Thanks for the bug report.
What page are you viewing when you see this error?
A post, user, taxonomy...

**Comment by sky4git** [comment]
That was on 'The Events Calendar' page. This page is generated by the plugin automatically. I debugged it and the reason it was happening because I used ACF field in custom taxonomy I've created, and I was reading it on that page.

I was able to get rid of the error by entering the value in each taxonomy terms. So, I assume problem with 'null' checking somewhere.

**Comment by elliotcondon** [comment]
Thanks @sky4git 

I've just fixed the issue and released a new version
