### ISSUE TITLE
Relationship field not selectable on WP 4.5

### ISSUE THREAD

**Issue by bennuttall** [elliotcondon/acf#532]
I have a relationship field which, after upgrading to WordPress 4.5 today, does not allow selections to be added. Selecting a post greys it out, but doesn't add it to the right hand side.

I'm seeing a JavaScript error in the console:

```js
ReferenceError: post_id is not defined
```

I'm using ACF 4.4.6

**Comment by rpetersn** [comment]
Ditto here!  Exact same issue here.  Note that this issue exists in a completely vanilla installation of WP4.5 and ACF 4.4.6 with a stock theme.  Standing by to help troubleshoot/etc.

**Comment by joelarmad** [comment]
I'm having the same problem... thanks in advance for any help

**Comment by elliotcondon** [comment]
HI guys

Thanks for the bug report.

I've just found and fixed the issue and released a new version.

It looks like the underscore JS library has changed the _.template() function without backwards compatibility! Pretty scary stuff, but it's fixed now.

**Comment by rpetersn** [comment]
THANK YOU!  All better here with 4.4.7....my hat is off!  Cheers. :)

**Comment by aarondo** [comment]
@elliotcondon The post_id problem is now solved with the update but I'm still having problems with advanced custom fields. I'm getting "Cannot read property 'replace' of undefined" in load-scripts.php when I look in console its coming from the new underscores library.

**Comment by joelarmad** [comment]
Thanks a lot  elliotcondon... al solved in 4.4.7

**Comment by aarondo** [comment]
All solved for me now too. It was a caching issue. Thanks

**Comment by elliotcondon** [comment]
Thanks guys!

**Comment by bennuttall** [comment]
Thanks @elliotcondon

**Comment by ayyobro** [comment]
I was dying trying to debug this. Thanks @elliotcondon !!!

**Comment by gkope** [comment]
👍
