### ISSUE TITLE
To make it possible to collapse blocks

### ISSUE THREAD

**Issue by Shmasya** [elliotcondon/acf#533]
Please make it possible to collapse blocks of a repeater.

**Comment by elliotcondon** [comment]
Hi @Shmasya 

This is possible in ACF PRO

**Comment by Shmasya** [comment]
Please, how? I have ACF PRO, but i see very very long list of repeater bloks.

**Comment by elliotcondon** [comment]
Collapsable repeater rows are announced in this release:
https://www.advancedcustomfields.com/blog/acf-pro-5-3-2-update/
