### ISSUE TITLE
Remove unnecessary data from file or image field output

### ISSUE THREAD

**Issue by hprobotic** [elliotcondon/acf#536]
Hi
I wanna remove some unnecessary field: title, description, modified, author, alt from field file output. How we can add more option to ACF/fields/file.php on acf_render_field_setting
![screen shot 2016-04-22 at 4 23 32 pm](https://cloud.githubusercontent.com/assets/5791885/14737519/b4698aac-08a6-11e6-9f17-9f3ab6a855aa.png)
![screen shot 2016-04-22 at 3 53 13 pm](https://cloud.githubusercontent.com/assets/5791885/14737532/c0da5cee-08a6-11e6-9d96-582dc5cc10fd.png)

**Comment by elliotcondon** [comment]
Hi @hprobotic 

If you want to modify the field's value, please use the acf/format_value filter:
https://www.advancedcustomfields.com/resources/acfformat_value/

**Comment by hprobotic** [comment]
Thanks @elliotcondon
