### ISSUE TITLE
Fellow WP Plugin Dev here: Your plugin clashes somewhere with mine and I'm not sure where.

### ISSUE THREAD

**Issue by dsifford** [elliotcondon/acf#540]
See dsifford/academic-bloggers-toolkit#40

Happy to work with you to figure out where we might be clashing. 👍

**Comment by elliotcondon** [comment]
Hi @dsifford 

Thanks for the bug report. Can you provide some context about the popup in question.
Also, a link to your plugin page would be great so I can get it installed and do some debugging

**Comment by dsifford** [comment]
My plugin leverages TinyMCE pretty heavily. The popup in question is created using `TinyMCE.windowManager` ... The file that opens that window is here: https://github.com/dsifford/academic-bloggers-toolkit/blob/master/lib/js/tinymce-entrypoint.ts


The plugin page on wordpress is here: https://wordpress.org/plugins/academic-bloggers-toolkit/

Let me know if there's anything else I might be able to clarify.

**Comment by dsifford** [comment]
Oh, and the relevant code begins here: https://github.com/dsifford/academic-bloggers-toolkit/blob/master/lib/js/tinymce-entrypoint.ts#L25

**Comment by elliotcondon** [comment]
Thanks @dsifford 

You've caught me at the right time. I'll download and set it up now and let you know what I find

**Comment by dsifford** [comment]
Sounds great. I'm gonna be pecking away working on test coverage on mine here for the next few hours so by all means don't be a stranger if you have any questions for me. 👍

**Comment by elliotcondon** [comment]
It looks like the number of popups created are proportional to the number of tinymce editors on the page. I'm guessing this issue is not only with ACF but with any plugin that adds an extra tinymce editor to the screen.

Perhaps in your code, you need to find the active tinymce (the one that is focused) and launch your popup for that one, not all

**Comment by dsifford** [comment]
Interesting (and probably good intuition). Is the editor that you create hidden somewhere? There is visibly only one on the the post editor I'm looking at.

**Comment by dsifford** [comment]
Fixed...

For future reference, if other TinyMCE plugins come barking up your tree, this is how to quickly fix it.

```ts
tinyMCE.PluginManager.add('abt_main_menu', (editor: TinyMCE.Editor, url: string) => {
    if (editor.id !== 'content') { return; }

// ..... etc
```

**Comment by elliotcondon** [comment]
Hi @dsifford 

Thanks for the reply. 

This will restrict your plugin to only the WP content editor. It would be good if your plugin worked with extra tinymce editors such as in ACF.

Perhaps you could look into adding the popup to the activeEditor, not all. This would solve the issue at the root and not need for the id check

**Comment by dsifford** [comment]
Do you have any idea how this is done? The tinyMCE documentation and I [don't really get along](https://github.com/tinymce/tinymce-docs/issues/317). 

AFAIK, I just add the plugin to PluginManager which then takes care of adding to the editors, no?

**Comment by elliotcondon** [comment]
Perhaps an easy solution is to use the global JS var `wpActiveEditor`.

you could use this to compare against.

```
tinyMCE.PluginManager.add('abt_main_menu', (editor: TinyMCE.Editor, url: string) => {
    if (editor.id !== wpActiveEditor) { return; }

// ..... etc
```

**Comment by dsifford** [comment]
Hm, I wasn't even aware that existed. Very cool. Yeah, I think that'll work nicely!
