### ISSUE TITLE
post_object example from resources not working.

### ISSUE THREAD

**Issue by rachelreveley** [elliotcondon/acf#543]
I am using the following code on a static page template following the instructions here: https://www.advancedcustomfields.com/resources/post-object/ to add a single blog post excerpt.

The page corectly shows a single blog heading but the except  
`<p><?php the_field('related_blog_post'); ?></p>` is blank

```
<?php

$post_object = get_field('related_blog_post');

if( $post_object ): 

	// override $post
	$post = $post_object;
	setup_postdata( $post ); 

	?>
    <div class="blog-post-product-page">
    	<a href="<?php the_permalink(); ?>">
    		<h2><?php the_title(); ?></h2>
    		<p><?php the_field('related_blog_post'); ?></p>
    	</a>
    </div>
    <?php wp_reset_postdata(); // IMPORTANT - reset the $post object so the rest of the page works correctly ?>
<?php endif; ?>
```
May or may not be relevant:

I am using Foundationpress
page has a fixed set of custom fields, not repeaters of flexible  content.

**Comment by elliotcondon** [comment]
Hi @rachelreveley 

Thanks for the question and code.

It looks like the 'related_blog_post' field is a post_object field. It is not possible to 'echo' an object in PHP, so this is why you are not seeing anything in the <p> tags.

Are you sure you want to echo the related blog post? Perhaps you would want to display it's title instead with: <?php the_title(); ?>

**Comment by rachelreveley** [comment]
I was after the title and the excerpt text. 
Looking at it the next day is always a good idea. I realised after about 30 seconds that I just need to put

```
    	<h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
    	<p><?php the_excerpt(); ?></p>
```

Thanks @elliotcondon
