### ISSUE TITLE
Manage fields registered via PHP in ACF Field Groups

### ISSUE THREAD

**Issue by anrw** [elliotcondon/acf#546]
Hi all,

There are many benefits to using PHP to register fields, however once you have generated and exported them it makes very complicated to edit them. 
As an idea I propose to show these fields in "ACF Field Groups" and allow users to edit them. After editing is finished we can just show the new generated code.

Let me know what you think,
Andrew

**Comment by elliotcondon** [comment]
Hi @anrw 

ACF v5 includes a feature called local JSON.
It's a way to edit field groups as normal, but also have them saved / loaded via JSON (similar to PHP array).

ACF 5 is currently available in ACF PRO and will be released as a free update in the future

**Comment by anrw** [comment]
Hi @elliotcondon 

Thanks! Didn't know about it. I use PRO version on my projects. The problem is that on one of my projects all fields (>40 field groups) are registered using PHP. Is there a way I can convert them back to json?

Thank you

**Comment by elliotcondon** [comment]
Hi @anrw 

I believe it would be possible to write some script to save the JSON files.
After you have registered/added your field group's via PHP, try running this code:

```
<?php 

$field_groups = acf_get_local_field_groups();	

foreach( $field_groups as $field_group ) {
	
	// vars
	$key = $field_group['key'];
	
	
	// append fields
	if( acf_have_local_fields( $key ) ) {
		
		$field_group['fields'] = acf_get_local_fields( $key );
		
	}
	
	
	// save json
	acf_write_json_field_group( $field_group );
	
}

?>
```

This should load all local field groups and save them to JSON files.
You will need a folder called 'acf-json' in your theme for ACF to write to, but this should work.

If not, please debug the code and make sure all variables are as expected

**Comment by anrw** [comment]
Thanks, @elliotcondon ! It worked like a charm!
