### ISSUE TITLE
delete_row function does not fully delete row

### ISSUE THREAD

**Issue by timiwahalahti** [elliotcondon/acf#547]
Hi.

delete_row function does not fully remove row from repeater field, it removes only metadata for spesific row number. The problem is, it don't update row count nor ordinal numbers for remaining rows. This causes situation where empty "ghost" rows are returned and visible.

Before delete_row i had following rows in `postmeta` table:

```
event_recurring				2
event_recurring_0_start		20160501	
event_recurring_0_end		20160502
event_recurring_1_start		20160620
event_recurring_1_end		20160622
```
and after `delete_row( 'event_recurring', 1, $post_id )` it is:

```
event_recurring				2
event_recurring_1_start		20160620
event_recurring_1_end		20160622
```

the end result is looking like this in meta box
<img width="739" alt="screenshot 2016-06-01 22 21 11" src="https://cloud.githubusercontent.com/assets/415544/15722625/536a7d40-2847-11e6-8b18-230fec08b4c2.png">

end result should look like this in database:

```
event_recurring				1
event_recurring_0_start		20160620
event_recurring_0_end		20160622
```

**Comment by elliotcondon** [comment]
Hi @timiwahalahti 

Thanks for the bug report.
Are you using ACF4 + repeater add-on, or ACF PRO?
I believe this has been fixed in ACF PRO. Are you able to test?

**Comment by timiwahalahti** [comment]
I'm using ACF PRO but outdated version, updating to latest (5.3.8.1) fixed this issue.

My mistake, sorry for the inconvenience.
