### ISSUE TITLE
WYSIWYG field - not being saved

### ISSUE THREAD

**Issue by duikb00t** [elliotcondon/acf#551]
**Setup**

I have a few WYSIWYG fields setup separated by tabs. When I enter all data in my tabs, only 'some' of them are being saved into the database.

Currently the 2nd and 3rd field are always empty after saving my content.

<img width="1005" alt="schermafbeelding 2016-06-24 om 09 04 20" src="https://cloud.githubusercontent.com/assets/1292776/16330653/320c9d6c-39eb-11e6-9ec7-9f5d5a1a1667.png">

Is there a fix for this?

**Comment by duikb00t** [comment]
**Fixed**
Weird fix, maybe who's developing ACF should take a look at this:
I have field names like: 'avantages' 'construction' ... I renamed them into: 'av', 'cons', ...

For some weird reason this just works. Could be a field in the database which is not long enough to store all fields or something else?

**Comment by elliotcondon** [comment]
Hi @duikb00t 

Thanks for the bug report.
What edit screen are the WYSIWYG's saving data to?
- user, post, options page, ...?

There is a 64 character limit when saving to the wp_options table, however, your field names do not seem very long.

**Comment by duikb00t** [comment]
Hi @elliotcondon 

I select a new 'Post' and select a 'Category' where the ACF group is attached too.
The fields appear and then I was unable to save the ones shown in the screenshot above.

Best regards

**Comment by elliotcondon** [comment]
Hi @duikb00t 

Thanks for yoru reply, but it is slightly confusing.
Are you editing a post, or a category?

Can you please provide login details for me to test this issue
Please include step by step instructions to  replicate the issue exactly
