### ISSUE TITLE
Decimal value in Number field not visible in back end

### ISSUE THREAD

**Issue by Niq1982** [elliotcondon/acf#553]
Number field is saved in database as a string and decimals are separated with a comma. The HTML5 number field does not support commas as decimal separators, so the number field in back end shows nothing, if a value like "75,5" is saved. Like this:` <input type="number" id="acf-field-foobar" class="number acf-is-appended" name="fields[field_577a3feea480e]" value="75,5" placeholder=""> `

A fix for this could be adding following lines in number.php, line 75:
```
if( isset($field['value']) )
		{
			$field['value'] = str_replace(",", ".", $field['value']);
		}
```

**Comment by elliotcondon** [comment]
Hi @Niq1982 

Thanks for the bug report.

I like your suggested fix, but worry that other users may not like the value being changed.
I can imagine receiving emails in regards to 'Why are my number values changing?'

It looks like coma support is being added to browsers. A quick google linked to this topic:
https://www.slightfuture.com/webdev/html5-input-number-localization

I think I will leave this bug for now, and let browsers add compatibility instead of getting in the way.

Thanks again for your bug report and proposed fix.

**Comment by Niq1982** [comment]
I can't see what kind of harm would cause if the admin edit screen converts the value from comma-separated to dot-separated, since the field input is processed always upon save and the dot gets changed again to a comma and value converted through int to a string. Yeah the browsers may fix this problem, but nevertheless: the HTML5 reference says it clearly: number field input value accepts only a floating number and only allowed separator is ".". In my case, this bug makes the number field completely useless.

**Comment by elliotcondon** [comment]
Hi @Niq1982 

Thanks for the reply.

Now I understand.

Currently the number field replaces ',' for an empty string. This is becuase the US and EN currency format looks like this: $1,234.00.

We use a ',' every 3 characters to denote the amount.
I understand that different languages use the ',' in a different way, but am not sure how to support both.

**Comment by Niq1982** [comment]
Hi, i worked out a perfect solution to this problem, maybe you could include it in ACF documentation (also since there is no documentation about number field)?

To functions.php: 
`function acf_number_fix($value, $post_id, $field) {
    if (is_admin()) {
        $value = str_replace(",", ".", $value);
    }
    return $value;
}
add_filter('acf/load_value/type=number', 'acf_number_fix', 10, 3);`

**Comment by elliotcondon** [comment]
Hi @Niq1982 

Great use of the acf/load_value filter!
I'll consider adding this to the docs, but can you please write a step by step instructions to replicate the issue? That will make it very easy for me to replicate and understand how the problem occurs
