### ISSUE TITLE
delete_row doesn't delete all rows in a loop

### ISSUE THREAD

**Issue by gopeter** [elliotcondon/acf#556]
Hi,
at first, thanks for this great plugin. Saved me thousands of hours over the past few years! :)

But I ran into some troubles while developing a plugin that uses the `delete_row` method. I'm trying to delete all rows in a loop, but everytime I run my script just one row gets deleted (but all values!)

This is how it looks before:

![bildschirmfoto 2016-07-18 um 17 13 25](https://cloud.githubusercontent.com/assets/1242960/16919816/6b92fa8a-4d0b-11e6-9339-da381b9d092d.png)

And this is how it looks after my script tried to delete all rows:

![bildschirmfoto 2016-07-18 um 17 13 42](https://cloud.githubusercontent.com/assets/1242960/16919829/75982b0e-4d0b-11e6-8275-0bdf67ecd149.png)

So the script just delete on row at a time, but deletes all values at a time.

That's how I tried it:

```php
$rows_to_delete = null;

if ( have_rows( 'flightplan', $post_id ) ):
  $rows_to_delete = [ ];

  while ( have_rows( 'flightplan', $post_id ) ): the_row();
    array_push( $rows_to_delete, get_row_index() );
  endwhile;

  /*
   * just a try
   * reverse array because IDs got re-index (?) after each delete, so delete from last to first ID (e.g. 4, 3, 2, 1)
   */
  $rows_to_delete = array_reverse( $rows_to_delete );

endif;

if ( is_array( $rows_to_delete ) && count( $rows_to_delete ) > 0) {
  foreach ( $rows_to_delete as $row_to_delete ) {
    delete_row( 'flightplan', $row_to_delete, $post_id );
  }
}
```

**Comment by gopeter** [comment]
OK, this has something to do with `wp_cache_get` because the `$rows` count inside `delete_row` doesn't get updated for each delete iteration.

If I comment out the cache code inside the `acf_get_value` method, everything works fine.

Any idea for a workaround? :-)

**Comment by gopeter** [comment]
Adding 

```php
wp_cache_delete( 'load_value/post_id=' . $post_id . '/name=flightplan', 'acf' );
```

before 

```php
delete_row( 'flightplan', $row_to_delete, $post_id );
```

now works for me :)

**Comment by elliotcondon** [comment]
Hi @gopeter 

Thanks for the issue report.

What version of ACF are you using?

**Comment by gopeter** [comment]
I'm using 5.3.10. (ACF Pro)

**Comment by elliotcondon** [comment]
Thanks @gopeter 

I'll do some testing with this today and hopefully have it added to the next version

**Comment by gopeter** [comment]
Thanks a lot! :)

**Comment by elliotcondon** [comment]
Hi @gopeter 

I've reviewed the delete_row() function and made some major improvements!

Can you please edit the api/api-template.php file and replace the delete_row() function with this:

```
/*
*  delete_row
*
*  description
*
*  @type	function
*  @date	19/10/2015
*  @since	5.2.3
*
*  @param	$post_id (int)
*  @return	$post_id (int)
*/

function delete_row( $selector, $row = 1, $post_id = false ) {
	
	// filter post_id
	$post_id = acf_get_valid_post_id( $post_id );
	
	
	// get field
	$field = acf_maybe_get_field( $selector, $post_id );
	
	
	// bail early if no field
	if( !$field ) return false;
	
	
	// get value
	$rows = acf_get_value( $post_id, $field );
	
	
	// bail early if no value
	if( empty($rows) ) return false;
	
	
	// vars
	$i = $row-1;
	
	
	// bail early if row doesn't exist
	if( empty($rows[ $i ]) ) return false;
	
	
	// unset
	unset( $rows[ $i ] );
	
	
	// reindex
	$rows = array_values($rows);
	
	
	// update
	acf_update_value( $rows, $post_id, $field );
	
	
	// return
	return true;
	
}
```

Please test this out and let me know what you think.
This should solve all issues with the function!

Cheers
E

**Comment by gopeter** [comment]
Sorry for the late answer!

The new code works like a charm. Thanks! :)

**Comment by elliotcondon** [comment]
Hi @gopeter 

That's great! Thanks for the reply.

5.4.0 should be released in under a week including this fix!
