### ISSUE TITLE
acf_form_head ( ) it seems not work on my theme.

### ISSUE THREAD

**Issue by AndrGelmini** [elliotcondon/acf#561]
Hello everyone and especially to you Eliot .

I have long sought a solution to this problem but I can not find a solution .

Hello everyone and especially to you Eliot .

I have long sought a solution to this problem but I can not find a solution .

I also tried to manage the updating of user destination front end via the plugin of acf - RestAPI successful but I think with acf form the result is cleaner .

So I installed Theme My Login considering that dovetails very well with WP Social Login

Now I want to create a user page where users are able to manage their information .

Using the theme Italystrap .

When I go to create the form with `acf_form();` the form you see perfectly , but when I go to try to change my user information page gives me error.

> Are you sure you want to do this ?
> 
> Try again

The code

Function.php 

`/**
 * Add acf_form_head to head
 * @return acf_form_head
 */
function aef_user_page_add_acf_header() { 
	if (is_page_template( 'page-user.php' ) && is_user_logged_in()):
    		acf_form_head();     
   	endif;
} 
add_action( 'wp_head', 'aef_user_page_add_acf_header', 0 ); 

/**
 * Deregister the admin styles outputted when using acf_form
 */
add_action( 'wp_print_styles', 'aef_deregister_admin_styles', 999 );
function aef_deregister_admin_styles() {
	// Bail if not logged in or not able to post
	if (is_page_template( 'page-user.php' ) && is_user_logged_in()):
		wp_deregister_style( 'wp-admin' );
	endif;
}

/**
 * Back-end creation of new candidate post
 * @uses Advanced Custom Fields Pro
 */
add_filter('acf/pre_save_post' , 'aef_do_pre_save_post' );
function aef_do_pre_save_post( $post_id ) {
	// Bail if not logged in or not able to post
	if (is_page_template( 'page-user.php' ) && is_user_logged_in()):
			// check if this is to be a new post
		if( $post_id != 'new_post' ):
			return $post_id;
		endif;
		// Create a new post
		$post = array(
			'post_type'     => 'post', // Your post type ( post, page, custom post type )
			'post_status'   => 'publish', // (publish, draft, private, etc.)
			'post_title'    => wp_strip_all_tags($_POST['acf']['field_54dfc93e35ec4']), // Post Title ACF field key
			'post_content'  => $_POST['acf']['field_54dfc94e35ec5'], // Post Content ACF field key
		);
		// insert the post
		$post_id = wp_insert_post( $post );
		// Save the fields to the post
		do_action( 'acf/save_post' , $post_id );
		return $post_id;

	endif;
}`

page_user.php 

`	<head>
		<?php get_header('user_page'); ?> 
	</head>

	<body>
	   <section id="page-user">
	      <div class="container-fliud">
			<?php 
				// Recupero le informazioni dell'utente corrente.
					global $current_user;
					get_currentuserinfo();
				 // recupero il parametro per acf filed
					$su = wsl_get_stored_hybridauth_user_profiles_by_user_id( $current_user->ID );
					$u_id = 'user_' . $current_user->ID; 
					$url = site_url( 'wp-json/acf/v2/user/' . $current_user->ID );
            		?>
            
            <?php if (!empty(get_currentuserinfo()->ID)):
            
            	while ( have_posts() ) : the_post();

			if ( !is_user_logged_in() ):
 
			 echo 'You are not logged in. <br /> <a href="' . get_permalink(31) .'">Log In &rarr;</a>';

			else:

			 $options = array(
				 'post_id' => 'user_'.$current_user->ID, // $user_profile,
				 'field_groups' => array(4099),
				 'return' => add_query_arg( 'updated', 'true', get_permalink() ), // return url
				 //'submit_value' => 'Update Profile'
			 );

			 echo '<p>Your username is <b>'.$current_user->user_login.'</b>. This cannot be changed.</p>';

			 acf_form( $options ); 
 
			endif;

            	endwhile; 
                        
                 //get_template_part( 'loops/content', 'profile-user');
             else:
           		 get_template_part( 'loops/content', 'none');
             endif; ?>

	      </div>
	   </section>
       
      <?php acf_enqueue_uploader(); ?>
       
	</body>
    
    <footer>
    	<?php get_footer('user_page'); ?>
    </footer>`

**Comment by AndrGelmini** [comment]
Hello. doing some testing I noticed that the plugin theme my login interrupted the flow causing the error.

for all those who had the same problem I leave the explanation of how I solved the problem .

the jqery problems continue to exist .

so I added this as much nell'eader code to avoid mistakes .
` 	// verify nonce
	if( isset($_POST['acf_nonce']) && wp_verify_nonce($_POST['acf_nonce'], 'input') ):
		$post_id = $_POST['post_id']; // $post_id to save against
		$post_id = apply_filters('acf/pre_save_post', $post_id); // allow for custom save
		// save the data
		do_action('acf/save_post', $post_id);	
		// redirect
		if(isset($_POST['return'])):
			wp_redirect($_POST['return']);
		endif;
	endif;`

I created a form in this way .

`						$options = array(
							'post_id' => 'user_'.$current_user->ID, // $user_profile,
							'field_groups' => array(group_ID),
							'return' => add_query_arg( 'updated', 'true', get_permalink() ), // return url
							'form' => false,
							//'submit_value' => 'Update Profile'
						);  

                <form ruele="form" id="test-user" method="post" action="">
                	<?php wp_nonce_field( 'update-user_' . $current_user->ID ); ?>
                	<?php acf_form( $options ); ?>
						<input type="hidden" name="action" value="profile" />
						<input type="hidden" name="user_id" id="user_id" value="<?php echo esc_attr( $current_user->ID ); ?>" />
						<input type="submit" class="btn btn-primary btn-lg btn-block" value="Aggioana informazioni" name="submit" id="submit" />
                </form>     
 `

Ma ripeto non riesco a far funzionare come si deve il jquery. 

lo sviluppatore del tema mi ha consigliato di scrivere tutto il codice jquary in questo modo. 

`jQuery.noConflict()(function($){
    "use strict";
    $(document).ready(function() {
        alert('alert');
    });
});`

of some one you have any ideas on how to sniff jquary code before it is written and modify the structure of the code ?

**Comment by elliotcondon** [comment]
Hi @AndrGelmini 

Thanks for the topic, but I am very confused by your descriptions.
I am sorry, but I am unable to help you at this time. Please clear describe the issue and make sure your code previews correctly (currently looks broken)

Thanks
Elliot

**Comment by AndrGelmini** [comment]
Hi Eliot .

I do not know why but I can not format properly read the code . so I send you a postebin . so that it can be neatly formatted .

Anyway. the first problem was a problem due to the use of a plugin called Theme my login ( TML ) . ( SOLVED ) by inserting a wp_nonce_field .

Here how I solved the problem of permits
[http://pastebin.com/bmKsTSMa](url)

But now I'm experiencing credit problems of incompatibility jquary especially in the field selectors date. I docuto to an incompatibility between acf and bootstrap .

according to my tests the same template of Italistrap -child does not work , while on fefteen works great .

the theme developer has advised me to write any custom code jquary this way.
[http://pastebin.com/wuSekk1J](url)

I think the main problem is how docuto are recalled jquary libraries you ripropondo the script that invokes the libraries .

[http://pastebin.com/BbMaBT21](url)

I hope I was clear and understandable .. I'm sorry for the previous unclear message.

**Comment by elliotcondon** [comment]
Hi @AndrGelmini 

Your links do not work. Can you please check these and edit your reply to include correct links to code.

I'm still not understanding the issue at all. Your description includes no detail as to what this 'incompatibility' is. I hope I can figure out the issue from your code when i see it.

Please also include some screenshots to help point me in the right direction

**Comment by AndrGelmini** [comment]
Hello Eliot .

So now the links should work. at least for me work .

I believe the problem was due to a jquery icompatibilità ACF with http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js

I guess that's because I set the wp jquery for pgina tests and everything goes as it should .

**Comment by elliotcondon** [comment]
Hi @AndrGelmini 

Is this issue solved? Can we mark this as closed.

I am very confused about what the issue is here and how it is related to ACF

**Comment by AndrGelmini** [comment]
Yes Eliot.

The problem I solved ..

As I told you I had two problems, one that the sending of the form I was an error for lack of permits, the other was due to an incompatibility between (I honestly do not know) but now everything is fine.

Now I'm juggling to write one plugin for acf that makes sure to create a multi-page form in front end.
