### ISSUE TITLE
[Question] - Why are you storing settings in a hidden TinyMCE instance, rather than just some field?

### ISSUE THREAD

**Issue by dsifford** [elliotcondon/acf#562]
Perhaps I'm interpreting what's going on incorrectly, but it seems that you nest a hidden tinymce instance on `post.php` and `post-new.php` for storing settings? 

Why not just use an input field? Can you clarify this?

I'm the author of [Academic Blogger's Toolkit](https://github.com/dsifford/academic-bloggers-toolkit) and I'm trying to work out more plugin conflicts between yours and mine.

Thanks

**Comment by elliotcondon** [comment]
Hi @dsifford 

Thanks for the topic.

I create a hidden tinymce instance to ensure the scripts and styles are loaded onto the edit page and the tinymce instance is created. This solves issues when a WYSIWYG field is added to a form that does not contain a post editor (custom post type, user, taxonomy, etc).

Whats the issue you are having?

**Comment by dsifford** [comment]
Hey! Hope my first message didn't come off as abrasive or anything. Not my intention at all!

> This solves issues when a WYSIWYG field is added to a form that does not contain a post editor (custom post type, user, taxonomy, etc).

That's what I figured. Clever little workaround.

> Whats the issue you are having?

Mostly just random edge-cases. We had a discussion in the past and you recommended adding in a check to see if `tinymce.activeEditor.id` matches `wpActiveEditor` and return early if not, which has worked for the most part. However there were some cases where your custom hidden editor would slip by that check and cause the interactions between the user and my plugin to hit your hidden editor.

I was able to cut through most of the issues by just explicitly attaching to tinymce instances having the id of `content`, but I've had one user who asked if he'd be able to use my plugin along with a tinymce editor generated by your plugin in some custom post that he made. [Here's that issue](https://github.com/dsifford/academic-bloggers-toolkit/issues/115).

Any suggestions?

**Comment by elliotcondon** [comment]
Interesting.

I use the id 'acf_content' in both ACF and ACF PRO for the hidden WYSIWYG field.
Perhaps you could check for this id and bail early if detected?

**Comment by elliotcondon** [comment]
of perhaps you could check if the editor element is :visible? (The ACF one is always hidden)

**Comment by dsifford** [comment]
@elliotcondon 

> I use the id 'acf_content' in both ACF and ACF PRO for the hidden WYSIWYG field.

Good to know. I think I can manage working with that. Thanks for clarifying (again!). 😄

**Comment by dsifford** [comment]
@elliotcondon FYI: Customizr theme [also has issues](https://github.com/dsifford/academic-bloggers-toolkit/issues/122) related to the multiple tinymce editor thing.

Is there a way to stub out the `init` event dispatcher for your hidden editor?

**Comment by elliotcondon** [comment]
Interesting....

I'll have a look, but can you do the same also?
- I'm hoping there is some documentation for tinymce to hook into the init action and somehow prevent the bubbling of the event so no other code gets triggered.

**Comment by dsifford** [comment]
Sure, I'll poke around and see if I can turn something up tomorrow afternoon.

> I'm hoping there is some documentation for tinymce to hook into the init action and somehow prevent the bubbling of the event so no other code gets triggered.

The [docs for tinymce](https://www.tinymce.com/docs/api/tinymce/tinymce.editor/) aren't very good. No disrespect to them at all, but it's mostly incomplete. It's mainly just a fancy list of method and parameter names on the top level of each class. The shape/type of method args and class members aren't really there yet (besides primitives). There are a few exceptions to this, but not many.

That all said, I might be able to figure something out if nothing turns up. Keep me posted if you're able to find something in the meantime. 👍

**Comment by dsifford** [comment]
Not as much time as I'd hoped to have today to look into this, but here's the relevant line in the tinymce source https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/Editor.js#L1025

**Comment by elliotcondon** [comment]
Hi @dsifford 

I think I've been able to fix the issue! Instead of preventing the 'init' action, I was able to better set the 'activeEditor' which seems to be happy with ABT.

Do you have an ACF PRO license? 
If possible, can you please download and test the latest build of ACF PRO (5.4.3 RC1)?
​
1. Login to your account online: http://www.advancedcustomfields.com/my-account
2. Click on the ‘see all versions’ link next to your license
3. Download the latest 5.4.3 RC1 version​​

**Comment by dsifford** [comment]
Woot woot! 🎉  

Sorry I wasn't more helpful with this. I actually just got home from a week-long vacation, so I wasn't really able to look at it at all. Glad to hear you were able to get it figured out nonetheless!

> Do you have an ACF PRO license? 

I do not. The only reason I became aware of the issue is because it was reported by an ABT user (specifically, @floaltvater). He might be willing to give it a try though.
