### ISSUE TITLE
Required field not validating in a taxonomy term

### ISSUE THREAD

**Issue by ilokhov** [elliotcondon/acf#563]
Firstly, thanks a lot for this great plugin.

Required fields in taxonomy terms do not seem to be validating for me. To reproduce the behaviour:

- use a clean current version of WordPress (4.6) and the latest version of ACF (4.4.8)
- create a new field group to show up in a taxonomy term (in my case I used the standard "Tags" term)
- create a text field in this group and set it to being required
- when creating a new term or editing an existing term, even when this required text field is left empty, it does not validate and proceeds to save the term with an empty field

I had a look at the input.js file in ACF, on line 3937 there is this bit of code:

`$(document).on('submit', '#post', function(){`

So the validation kicks in when submitting the form with the id "post". However I checked in the markup of a taxonomy term edit page in the admin area, and the form has the id "edittag". Likewise, when creating a new taxonomy term, the form has the id "addtag". So in these cases the validation never kicks in and terms can be edited/created without filling in required fields.

If I include the other ids (edittag, addtag) in the on submit function, they get validated, however the fields with errors do not get highlighted, so I assume more would have to be done to get it to work properly.

Is there a way to make required fields validate properly on taxonomy terms?

Thanks and let me know if you need more info.

**Comment by elliotcondon** [comment]
Hi @ilokhov 

Thanks for the bug report. This sounds like an easy fix. I'll update the free plugin shortly

**Comment by elliotcondon** [comment]
Just to let you know, this issue is already resolved in ACF PRO (v5) which will be released as a free version in the future

**Comment by ilokhov** [comment]
Hi @elliotcondon

Thanks a lot for the quick reply, looking forward to the update in ACF4. I am using ACF PRO on one site and can confirm that this works there.

**Comment by dalton-e** [comment]
Has this been fixed? Still having this problem on 4.4.10

**Comment by elliotcondon** [comment]
Hi @dalton-e 

This issue will most likely not be fixed in the free version of ACF (v4).
That said,  the free version of ACF v5 will soon be announced which will fix the issue
