### ISSUE TITLE
WYSIWYG broken

### ISSUE THREAD

**Issue by OlliGranlund** [elliotcondon/acf#566]
Issue: http://i.imgur.com/4sGK60y.png

Tested:
- Reinstalling wordpress version 4.6
- Updating ACF Pro plugin
- Disabling all other plugins

The built in Wordpress tinymce editor works flawless. No errors in console or debug_log.

**Comment by OlliGranlund** [comment]
Seems to be a browser problem. Tested Chrome on Windows (latest version), Chrome on Android (latest version) and Firefox (not latest version). None of those worked. However, tested with a Mac and Safari, it worked flawless...

**Comment by OlliGranlund** [comment]
Seems to be a browser problem. Tested Chrome on Windows (latest version), Chrome on Android (latest version) and Firefox (not latest version). None of those worked. However, tested with a Mac and Safari, it worked flawless...

Guess I need to start bugging in chrome instead...

**Comment by elliotcondon** [comment]
Hi @OlliGranlund 

Looks like the JS is not initializing correctly.
Please check your console log when refreshing the page to view JS errors

**Comment by OlliGranlund** [comment]
![image](https://cloud.githubusercontent.com/assets/9628495/18307977/52e58c9c-74fb-11e6-92a0-f0bd67b73db0.png)

**Comment by elliotcondon** [comment]
Hi @OlliGranlund 

Thanks for the reply.
Just to confirm, does this issue occur with other themes when ACF is not active?

**Comment by OlliGranlund** [comment]
Yes

Tested using the latest Wordpress default theme Twenty Sixteen. No plugins in use. The issue is really weird as the page shouldn't have anything special in it. Other sites using same theme and plugins are working fine :/

**Comment by elliotcondon** [comment]
Hi @OlliGranlund 

Thanks for the reply. Are you able to provide me login access with a link to the post edit page in question?

Thanks
E

**Comment by OlliGranlund** [comment]
I'm sorry, this issue doesn't seem to be connected to the plugin. If nothing helps, I'll soon do a fresh WP install and try with that. Sorry for blaming the plugin in this case :(
