### ISSUE TITLE
Uncaught TypeError: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by davidcie** [elliotcondon/acf#568]
This is just what is being discussed over at the support forum [here](https://support.advancedcustomfields.com/forums/topic/uncaught-typeerror-cannot-read-property-body-of-undefined/). Wanted to make sure the fix is also planned for ACF4; at the moment none of my WYSIWYG fields display TinyMCE and are stuck in pure text mode editing.

**Comment by elliotcondon** [comment]
Hi @davidcie 

Thanks for the bug report.
I'll do some testing today and let you know what I find

**Comment by elliotcondon** [comment]
Hi @davidcie 

I've just tried to replicate the issue but can't.
Any chance you can setup a site online for us both to test?

I have a feeling the issue is due to a specific combination of ACF + x

Thanks
Elliot

**Comment by davidcie** [comment]
@elliotcondon thanks for looking into it. Will try to set up a test site so that we can try to nail this down and come back with login data.

**Comment by davidcie** [comment]
Hmmmm this is pretty weird. Was unable to replicate the problem on a fresh WP 4.6.1 install despite similar setup and plugin palette. Then I went back to the original site and... discovered that everything is indeed working correctly there too! Perhaps a recent plugin or WP update (4.6._1_?) fixed what was broken...

If on the other hand this is intermittent and I do manage to decisively repro the issue will take the liberty to ask you to re-open this isssue.

Thank you for your time and apologies for the apparent confusion!

**Comment by elliotcondon** [comment]
Hi @davidcie 

Thanks for the reply. This sounds like cached JS is the issue. WP did update the tinymce library, so it is possible that a file was referencing an old variable/function that no longer exists?

If the issue starts again, try a hard refresh and let me know if it solves theproblem
