### ISSUE TITLE
delete_row() not deleting all rows in repeater

### ISSUE THREAD

**Issue by NWR91** [elliotcondon/acf#569]
Wordpress 4.6
ACF 5.4.4

Using delete_row() inside the repeater field while loop doesn't doesn't delete all rows in the repeater.

$deleteID = 1; 			
while ( have_rows('repeater_field', $post_id) ) { the_row();
    delete_row('repeater_field', $deleteID, $post_id);
    $deleteID++; 
}

Is there anything I'm missing, or is this an error in ACF?

**Comment by elliotcondon** [comment]
Hi @NWR91 

Thanks for the email.
Your code looks correct, assuming that $post_id contains the correct value.

Can you elaborate more on 'doesnt work'?

Thanks
Elliot

**Comment by NWR91** [comment]
Thanks to @elliotcondon for the answer via email. 

for anyone else, instead of the while loop, simply do `delete_field('repeater_field', $post_id);`
