### ISSUE TITLE
Field Group Location Rules not loading all posts

### ISSUE THREAD

**Issue by ghurson** [elliotcondon/acf#574]
All of the field groups on my site have recently started dropping a few posts from a certain (custom) post type, and I have lost the ability to place a field group on a specific page.

Is there something on a specific post (this is a custom post type) that would cause a few - but not all - posts not to show in this list? There are over 1000 blog posts on the site - could that cause it? Could I remove those from the list somehow?

I'm sure there is more relevant information here that I could provide - please let me know if you need anything from me for diagnostics.

Thanks!

**Comment by elliotcondon** [comment]
Hi @ghurson 

Thanks for the question, but this is not a place for support. Please create a new support ticket here: http://support.advancedcustomfields.com/new-ticket/

By the sounds of it, it may be possible that the location rule for 'posts' is not able to load all the 1000 posts.

I would advise using a different location rule such as 'page template' or 'post format'.
Creating a field group for a 'specific post' can lead to other issues in the future if the post ID's change (during migration, etc)

Thanks
E
