### ISSUE TITLE
Repeater + WYSIWYG doesn't work

### ISSUE THREAD

**Issue by MatthewPringle** [elliotcondon/acf#575]
Adding multiple rows in a repeater, each with a WYSIWYG, causes only the first textarea to transform to the WYSIWYG. The other remain as a text area.

I have installed this on an untouched, default wordpress 4.6.1

I user stand that other commits are attempting to fix this issue, but unfortunately those do not work.

If I revert to ACT 4.4.8 everything works fine. 4.4.9 causes this issue.

No other plugins are installed, no changes to anyWordpress files.

Safari 9.1.1.

![untitled](https://cloud.githubusercontent.com/assets/368800/18954917/0b70b4aa-864d-11e6-8607-8b4d182fa0a5.png)

**Comment by MatthewPringle** [comment]
I have also tested this issue in the latest Chrome and IE. Same results.

**Comment by elliotcondon** [comment]
Hi @MatthewPringle 

Thanks for the bug report.
Can you please email me directly with login details to your site so I may take a look myself?
Please include a link to the edit page in question.

My email is e@elliotcondon.com

Thanks
E

**Comment by elliotcondon** [comment]
HI @MatthewPringle 

Thanks for the login details. I've found/fixed the issue and released a new version 4.4.10.

Can you please update and let me know if the issue is solved?

**Comment by MatthewPringle** [comment]
Hi Elliot

Thanks for the update, that has resolved that issue with TinyMCE not working in a repeater.

Thanks so much for the quick turn around!

Matt
Sputnik

**Comment by C0deS1ayer** [comment]
I need this fix for ACF Pro.  Whats the chance of getting ACF Pro updated?

**Comment by elliotcondon** [comment]
Hi @C0deS1ayer - this bug should not affect ACF PRO. If you are having an issue with ACF PRO, please create a support ticket via the following link with full detail about the issue. Be sure to include login details so I may test the problem and ask for the ticket to be escalated to me (Elliot) with a link back to this github thread.

https://support.advancedcustomfields.com/new-ticket/

Thanks
Elliot
