### ISSUE TITLE
[docs] Repeater field query

### ISSUE THREAD

**Issue by jmarceli** [elliotcondon/acf#584]
It should be mentioned in https://www.advancedcustomfields.com/resources/querying-the-database-for-repeater-sub-field-values/ that using revisions in content type needs better SQL query and that revisions are the cause of duplicate results, see:
https://support.advancedcustomfields.com/forums/topic/acf-repeater-database-query/
or
https://support.advancedcustomfields.com/forums/topic/querying-the-database-for-repeater-sub-field-values-shows-duplicate-results/

Which shows that it is not obvious for the users.

**Comment by elliotcondon** [comment]
Hi @jmarceli 

Thanks for the issue.

This doc is definitely outdated, and perhaps I should ocnsider removing it from the website.
If you are attempting to query posts by custom field values, please follow this doc and see the 4th example: https://www.advancedcustomfields.com/resources/query-posts-custom-fields/

**Comment by jmarceli** [comment]
Thanks for the example. The docs in question was the first result in Google when I was searching for repeater sub fields query so removing/redirecting would be a good solution.
