### ISSUE TITLE
Auto Save Advanced Custom Fields

### ISSUE THREAD

**Issue by soRailicious** [elliotcondon/acf#585]
Hi Guys,

i don't really get a solution. I googled it a few times and i am searching hours and hours... But i don't get a solution to save the values from ACFields in WordPress Heartbeat Autosave...

This means:
A Newsposter is typing his News and doesn't save this post (he forget it)... He is clicking beside or is clicking "back" and the Post only saves the wordpress default values...

But the ACF Values disappears... They are lost!

How we can save the ACF in the WordPress Autosave routine?

We are using some fields for the default post type 'post' (Teaser, Picture Description, Featured Checkbox, A short addition line for the title, and so on)....

Could maybe someone help me?

**Comment by elliotcondon** [comment]
Hi @soRailicious 

Currently, ACF does does not allow custom field value save during the 'autosave' event. This was a decision made for performance reasons.

If you would liket o add this in, you would need to listen to teh WP 'save_post' action, check the $post_type == 'auto-draft' and then run the custom action:
```
do_action('acf/save_post', $post_id);
```

Please take a look at the file 'core/controllers/post.php' and find the functino save_post() to see the logic for saving the post form

**Comment by soRailicious** [comment]
@elliotcondon https://support.advancedcustomfields.com/forums/topic/hook-acfsave_post-not-applied-for-all/#post-45195 <- this doesn't work with autosave, just if you press save... can you maybe give the last tip to it?

**Comment by elliotcondon** [comment]
Hi @soRailicious 

The thread you have linked to does not include any code to save custom fields during autosave. Please read over my last reply for all the information needed to write the necessary code

**Comment by amandablum** [comment]
is it possible to open this again? I've seen a number of questions about this and I understand the solution above is halfway there. A gist or snippet would be really helpful.

**Comment by elliotcondon** [comment]
Hi @amandablum 

Sure thing, something like this should work. Please note this has not tested but should get you started:

```
<?php 
	
add_action('save_post', 'my_autosave_acf');

function my_autosave_acf( $post_id ) {	
	
	// check if is autosave
	if( defined('DOING_AUTOSAVE') && DOING_AUTOSAVE ) {
		
		// verify nonce
		if( isset($_POST['acf_nonce'], $_POST['fields']) && wp_verify_nonce($_POST['acf_nonce'], 'input') ) {
			
			// update the post (may even be a revision / autosave preview)
			do_action('acf/save_post', $post_id);
		}
	}
}

?>
``

**Comment by amandablum** [comment]
Did not fire autosave with above function. Question. Would autosave even fire if you've hidden all the core content on the page via ACF? in other words, if there is no content or excerpt, would autosave even fire, so that ACF would get caught in that save?

**Comment by elliotcondon** [comment]
Hi @amandablum, I'm not sure without testing.

**Comment by amandablum** [comment]
for the sake of testing, I put content back into the page. I then let autosave fire. It saved content in the content editor but not content in the custom fields.

**Comment by amandablum** [comment]
When you throw content editor back into the mix, it will show the fields in autosaves, but not retain any information. So it shows what's in the fields pre autosave, but doesn't show any autosaved data. 

Tried a number of things. using GET vs POST, based n how saves of existing posts are done vs drafts. Tried adding ACF to REST API, which had the effect of NOT showing the ACF at all in the autosaves. Those fields were now completely gone. 

I don't know if this data helps at all.
