### ISSUE TITLE
[feature request] Showing acf fields based on sub taxonomies or categories

### ISSUE THREAD

**Issue by vitalijm** [elliotcondon/acf#588]
**In "Edit Field Group":**
We are editing acf fields, called _"SOME_ACF_FIELDS_ONE"_
In rules we are choosing specific post taxonomy or category, for example _"SOME_CATEGORY_NAME_ONE"_.

**Then in "Add new post":**
ACF fields _"SOME_ACF_FIELDS_ONE"_ must be showed if we are choosed _"SOME_CATEGORY_NAME_ONE"_ taxonomy, or its sub taxonomies or categories.

**One more moment:**
When we are choosed taxonomy or category _"SOME_CATEGORY_NAME_ONE"_ in one specific language, in other does not showing _"SOME_ACF_FIELDS_ONE"_.

Wordpress: 4.6.1
ACF Pro: 5.4.8
Polylang: 2.0.7

**Comment by elliotcondon** [comment]
Hi @vitalijm 

Thanks for the question.
I'm not sure how polylang handles translation of field groups, so I can 't provide much info for your second question.

To have 'sub terms' trigger the 'parent term' location rule, you will need to write your own location rule. This is easily done by following this tutorial:
http://www.advancedcustomfields.com/resources/custom-location-rules/

**Comment by vitalijm** [comment]
Thanks for info.

Solution: https://github.com/Hube2/acf-filters-and-functions/blob/master/acf-post-category-ancestor-location-rule.php
