### ISSUE TITLE
Advanced Custom Fields PRO conflicts with Attachments

### ISSUE THREAD

**Issue by jameswlane** [elliotcondon/acf#590]
It seems like there is a conflict with adding a metabox to the admin page editor from ACF and Attachments.

When I enable ACF the Attachments metabox disappears.

**Comment by jameswlane** [comment]
I have also posted the issue with Attachments https://github.com/jchristopher/attachments/issues/172

**Comment by elliotcondon** [comment]
Hi @jameswlane 

Thanks for the issue. Can you please elaborate on the issue with a more comprehensive bug report?

Thanks
Elliot
