### ISSUE TITLE
[ACF Pro] Illegal string offset 'acf_fc_layout' 

### ISSUE THREAD

**Issue by mikos** [elliotcondon/acf#592]
I recently updated from ACF Pro 5.4.8 to 5.5.0 and one of my flexible-content fields won't save. On page load (after attempting a save) I get the following error in the server logs:-

```
PHP Warning:  Illegal string offset 'acf_fc_layout' in /wp-content/plugins/advanced-custom-fields-pro/pro/fields/flexible-content.php on line 304
```

The issue remains in version 5.5.1.

**Comment by elliotcondon** [comment]
Thanks @mikos 

I'll do some testing with this later today.
It's a long shot, but do you have a 'tab' or 'message' field with the same name/label as your flexible content field? 

Can you please also export and attach your field group .json file?

**Comment by mikos** [comment]
@elliotcondon Actually yes. The flexible content field is called 'Slides' and it is under a tab also called 'Slides'. It looks like I can fix the issue by re-saving the custom field group.

**Comment by elliotcondon** [comment]
Thanks @mikos - yes, I'll be releasing a patch today to fix this issue

**Comment by mikos** [comment]
@elliotcondon That's great! Thanks for your quick response.
