### ISSUE TITLE
ACF frontend form file input accept attribute

### ISSUE THREAD

**Issue by jmarceli** [elliotcondon/acf#594]
There is an issue with ACF file input frontend rendering.

ACF allows to restrict mime types with `mime_types` key but this doesn't affect frontend input attributes, there should be some option to set `accept` attribute for frontend file input http://www.w3schools.com/tags/att_input_accept.asp.
To be more precise the `mime_types` option defined for the frontend file input silently drops uploaded files if they don't suite defined extensions (which might cause hard to track bugs).

**Comment by elliotcondon** [comment]
Hi @jmarceli 

Thanks for the topic.
This issue has recently been fixed in ACF PRO.

ACF PRO now allows a basic file input to validate it's value (including file type, size, etc).

It won't be long now until ACF v5 is announced and you can get this functionality for the free version

**Comment by jmarceli** [comment]
Thanks for the reply. I'm an ACF PRO user (v5.5) and even in `file` field PHP code I didn't find anything about `accept` attribute support. The relevant code line looks as follows:

    <input type="file" name="<?php echo $field['name']; ?>" id="<?php echo $field['id']; ?>" />

So there is no chance to set `accept` attribute this way. Of course, I'm writing about `basic` uploader not `wp` Media Library based uploader.

**Comment by elliotcondon** [comment]
Hi @jmarceli 

Thanks for the reply.

Yes, I am not making use of the 'accept' attribute. instead, the validation is performed during the AJAX request on form submit - just like all other fields. If there is a specific issue, can you please open a support ticket so we may talk about login details, debugging, code, etc: http://support.advancedcustomfields.com/new-ticket/

**Comment by jmarceli** [comment]
I've created a ticket and here is a workaround for this issue (in case anyone is having same problem):

```
function validate( $valid, $value, $field, $input ){
	// bail early if value is already invalid
	if( !$valid ) {
		return $valid;
	}

  $ext = pathinfo($value, PATHINFO_EXTENSION);
  $allowed_ext = explode(',', $field['mime_types']);
  if ( !in_array( $ext, $allowed_ext ) ) {
    $valid = 'Unsupported extension .' . $ext . '. Please use one of the following extensions: .' . implode(', .', $allowed_ext);
  }

	// return
	return $valid;
}
add_filter('acf/validate_value/type=file', 'validate', 10, 4);
```

**Comment by elliotcondon** [comment]
Hi @jmarceli 

Thanks for the code.
I have recently added in file field validation fr the 'basic uploader'.

Can you please update to the latest version (5.5.5)?
- If the validation is still not working, please let me know so I can debug the issue

**Comment by jmarceli** [comment]
I've updated the plugin and it seems to be working fine. Thanks.
