### ISSUE TITLE
ACF fields disappear after update

### ISSUE THREAD

**Issue by mnguye08** [elliotcondon/acf#596]
Hi,

I use ACF 4.4.5 with Wordpress 4.4.2.
When I click on "Update" button (just update, no specific action), several fields disappear (73 fields to 58 fields).
What can be the cause of this issue?
How can I fix it?

Thanks for your feedback!

**Comment by elliotcondon** [comment]
Hi @mnguye08 

Thanks for the topic.
This sounds like you have hit a limit on the number of $_POST vars that can be sent in a request. Please read this doc here: https://www.advancedcustomfields.com/resources/limit-number-fields/

Please consider upgrading to ACF PRO to avoid this issue, or contact our support team for further debugging: http://support.advancedcustomfields.com/new-ticket/
