### ISSUE TITLE
Image field with PDF show "No image selected"

### ISSUE THREAD

**Issue by geoffyuen** [elliotcondon/acf#597]
[image field](http://imgur.com/a/ThiKn)

I have a repeater with 2 image fields. The first is set to only allow files of .pdf. On the page panel, when you click the `Add Image` button and choose a pdf it still displays the broken image icon. After saving the page that icon is replaced with "No image selected" as seen in the screen shot above. It *is* attached though as the rendered page has the pdf linked properly.

**Comment by elliotcondon** [comment]
Hi @geoffyuen 

Thanks for the issue, 
Can you please submit a support ticket via the following link and be sure to include more description about your issue and include an export of your field group so we can take a look at the field names and test.

http://support.advancedcustomfields.com/new-ticket/
