### ISSUE TITLE
ErrorException: Call to undefined function acf_register_field_type()

### ISSUE THREAD

**Issue by mattalberon** [elliotcondon/acf#598]
This bug occurs when called on:

wp-content/plugins/advanced-custom-fields-pro/fields/text.php in handleFatalError at line 190

In the following context:

Query String

wc-ajax	get_refreshed_fragments

**Comment by elliotcondon** [comment]
Hi @mattalberon 

The function `acf_register_field_type()` is defined in the 'core/fields.php' file.
This file is included before any field types.

Is it possible that you are including the text field type via some custom code?

**Comment by mattalberon** [comment]
@elliotcondon I think you might be right.

I couldn't reproduce the issue locally, however, I've removed a script which I think could have affected it.
