### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by Beee4life** [elliotcondon/acf#599]
I noticed my Yoast admin menu bar item was missing the past days.
I then switched back to Twentyseventeen and started activating plugins one by one.
When I activated ACF (Pro), it made Yoast's menu item disappear.

I tried other situations as well to eliminate if it was something else, but to me it appears to be ACF latest update.

**Comment by Beee4life** [comment]
My bad, it was a MU plugin which got triggered on ACF activation.

**Comment by elliotcondon** [comment]
Hi @Beee4life 

Thanks for the topic and replies. Glad to hear everything is working

**Comment by Beee4life** [comment]
Sorry that i brought it up without looking further :) but i'm just hppy it's fixed....
