### ISSUE TITLE
Tabs icons

### ISSUE THREAD

**Issue by LittleHamster** [elliotcondon/acf#603]
@elliotcondon I am trying to add an icon to tabs but it doesnt seem to be working, there is also this topic: 
https://support.advancedcustomfields.com/forums/topic/add-icon-to-tab-l/

I tried the UI and inserted an image with icon but the image is not displayed. I also added the code via php: 

```
'fields' => array(
                    array(
                        'key'               => 'field_pub_post',
                        'label'             => '<img src="icon-url">Post',
                        'name'              => '',
                        'type'              => 'tab',
                        'placement'         => 'left',
                        'endpoint'          => 0,
                    ),
```

can you allow the icons to be used in the tab labels? is there a fix for this? thanks

**Comment by elliotcondon** [comment]
Hi @LittleHamster 

Thanks for the feature request.
I've just done some testing and can confirm the issue (HTML is stripped out of the tab text).
This is easily fixed in the core JS and I'll have this fixed in the next version!
