### ISSUE TITLE
acf_form fails with error if `fields` argument is passed

### ISSUE THREAD

**Issue by tvervest** [elliotcondon/acf#604]
When the `acf_form` method is called with an options array containing the `fields` argument [as per the docs](https://www.advancedcustomfields.com/resources/acf_form/), the plugin fails with the following notice:

```
Notice: Undefined index: fields in [[removed]]/wp-content/plugins/advanced-custom-fields/core/api.php on line 1188
```

A simple way to trigger this issue, is by executing the following code:

```
acf_form(array(
  'fields' => array(
    'test_field'
  )
));
```

The problem seems to be caused by the call to `array_merge`, even if the `$defaults` object doesn't contain an empty array as a default value. A simple check if the `$defaults` object contains the key (added to the already existing if-statement on line 1183) should be sufficient to prevent this from happening, however the *real* problem seems to be that the `fields` option doesn't seem to do what it says in the docs at all - i.e. the fields still show, even if they aren't present in the `fields` option array.

This issue occurs using the (at the time of writing) latest version of the plugin: `4.4.11`.

**Comment by elliotcondon** [comment]
Hi @tvervest 

Thanks for the topic.
Please note that the free version of ACF (version 4) does not contain the 'fields' setting.

There are different versions of the doc you linked to. Please see:
https://www.advancedcustomfields.com/resources/acf_form/?version=4

If you require the 'fields' setting, please consider using ACF PRO, or waiting for the ACF v5 announcement (very soon).

**Comment by tvervest** [comment]
Ah, I see! Seems I wasn't paying enough attention while reading the docs ;) Thanks for the quick reply, I'll use a workaround for now and wait for the release of ACF v5!
