### ISSUE TITLE
Adjust textdomain in export

### ISSUE THREAD

**Issue by LittleHamster** [elliotcondon/acf#605]
Hi @elliotcondon 
can you please follow up with textdomain in export request?
https://support.advancedcustomfields.com/forums/topic/adjustable-textdomains-and-textdomains-in-php-export/

so when we export the php code, have the option to define a textdomain and then export it, it would make life much easier, thanks

**Comment by elliotcondon** [comment]
Hi @LittleHamster 

You can use the ACF setting 'l10n_textdomain' to define a custom textdomain.
http://www.advancedcustomfields.com/resources/acfsettings/

This textdomain will be used in the PHP export code
