### ISSUE TITLE
[ACF Pro] If( function_exists('') ) {} Problem

### ISSUE THREAD

**Issue by protasisimone** [elliotcondon/acf#606]
Hi all, 

I've a ACF Pro in my theme, but if I try to create a options page with this code:
```php
if( function_exists( 'acf_add_options_page' ) ) {
	
	acf_add_options_page();
	
}
```

ACF doesn't work (Work only if I use ACF Pro in plugin version).

This work only write this code:
```php
function aaa() {
	acf_add_options_page();
}

add_action( 'acf/init', 'aaa' );
```

It's normal?

Sorry for my english, thanks for ur reply.

**Comment by elliotcondon** [comment]
Hi @protasisimone 

Thanks for the question, however, this github repo is not a place for general support. Please submit a support ticket here so we can best help you
http://support.advancedcustomfields.com/new-ticket/

Please be sure to explain what 'doesnt work' - this is very vague.

Thanks
Elliot
