### ISSUE TITLE
Removing add/remove/move links from acf flexible content fields in admin area

### ISSUE THREAD

**Issue by gerharddt** [elliotcondon/acf#608]
Is it possible to remove the add/remove/move functionality from flexible content for some users on ACF?

So when you log in as client A you can add/remove and move the content areas around, but as Client B, you can update all of the content in the fields already there, but you can't move content around or add or remove any content areas.

Maybe it's a variable/function I can unset or unregister?

My guess was around capabilities here: advancedcustomfields.com/resources/acf-settings but tried most of the wp capabilities and no luck.

**Comment by elliotcondon** [comment]
Hi @gerharddt 

Thanks for the message. Please know this is not a support area. Github is used only for bug reports and development progress.

Please submit your question as a new support ticket here:
https://support.advancedcustomfields.com/new-ticket/

Such 'capabilities' for the flexible content field are not possible via PHP. You will nee to write some custom JS to remove the 'add/remove' icons.

Thanks
Elliot
