### ISSUE TITLE
SELECT: Added optgroup with filter, now it returns the same value and label

### ISSUE THREAD

**Issue by hrsetyono** [elliotcondon/acf#609]
I follow [this guide](https://www.advancedcustomfields.com/resources/dynamically-populate-a-select-fields-choices/) to dynamically populate a list and found out that you can add optgroup if we add nested array

```
$field['choices'] = array(
  'Section 1' => array('a' => 100, 'b' => 200, 'c' => 300),
  'Section 2' => array('a' => 100, 'b' => 200, 'c' => 300)
)
```

I have a Select field that does that and set the return value to **Both (value and label)**.

But If I do that, the label will be the same as value. Here's the dump:

```
array (size=2)
  'value' => 'a',
  'label' => 'a'
``` 

Removing the nested array solves the issue, so the problem is definitely optgroup.

Thanks

**Comment by elliotcondon** [comment]
Hi @hrsetyono 
Thanks for the question.

Yes, this will be a current limitation of the 'both' return value setting.
The select field `format_value` function uses basic logic to find the choice's vale/label and will only work with 'non optgroup' items.

I'm happy to add this to my to-do for a future version. Until then, please use the basic 'Value return setting' and lookup the label via a foreach loop.

**Comment by hrsetyono** [comment]
@elliotcondon Thanks for the quick response. Currently I have workaround by keeping the data linear (not nested) and format it during `prepare_field` filter.

With my code, line that starts with `#` will become the optgroup title. For example, here's my Options field:

```
#Section 1
a : 100
b : 200
c : 300
#Section 2
d : 400
e : 500
f : 600
```

Then, put this code on `functions.php`:

```
add_filter('acf/prepare_field/key=field_123456778', 'acf_prepare_field_select'); // change the field key to your target

function acf_prepare_field_select($field) {
  $choices = $field['choices'];
  $field['choices'] = array(); // start from empty

  $current_group = '';
  foreach($choices as $value => $label) {
    // if contain hashtag, turn it into optgroup
    if(strpos($label, '#') !== false) {
      $current_group = str_replace('#', '', $label);
      $field['choices'][$current_group] = array();
    }
    else {
      $field['choices'][$current_group][$value] = $label;
    }
  }

  return $field;
}
```

**Comment by elliotcondon** [comment]
Hi @hrsetyono 

Thanks for the reply and great work using the prepate_field filter! Very cool!
