### ISSUE TITLE
Datepicker date format problem

### ISSUE THREAD

**Issue by cih997** [elliotcondon/acf#610]
After update from 5.5.10 to 5.5.12 Datepicker dates went crazy.

For example I have a form in frontend and when I enter 01/12/2017 the 12/01/2017 is stored in database (and otherwise). This was working fine before that update.

To add, display and store formats are d/m/Y and I did not change it after upgrade. Again - it was working perfectly before update.

Any ideas?

**Comment by elliotcondon** [comment]
Hi @cih997 

Thanks for the topic, however, please address all support inquiries to a new support ticket here:
http://support.advancedcustomfields.com/new-ticket/

We have not made any changes to the datepicker fields, so please check your field settings (try toggling some changes and updating the field group to ensure the field's settings are saved correctly)
