### ISSUE TITLE
wp_register_script was called incorrectly

### ISSUE THREAD

**Issue by Beee4life** [elliotcondon/acf#611]
"wp_register_script was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks."

That's the error I get after the latest update.

**Comment by elliotcondon** [comment]
Hi @Beee4life 

Thanks for the bug report. I am hearing similar issues and will have this fixed today

**Comment by Beee4life** [comment]
sorry to 'bug' you about this bug, but have you made a fix already ?

**Comment by elliotcondon** [comment]
Hi @Beee4life 

Yes, please download the latest plugin files from your ACF account online

**Comment by Beee4life** [comment]
Ah you edited 5.5.13 ? I was expecting 5.5.14.

**Comment by elliotcondon** [comment]
Yes, only a quickfix to 5.5.13 this time

**Comment by Beee4life** [comment]
Thanks for the info.
