### ISSUE TITLE
$_POST['acf'] doesn't exist in free version

### ISSUE THREAD

**Issue by Beee4life** [elliotcondon/acf#612]
I am not sure if it's a bug or intentional, but wanted to mention it here, just in case.

On https://support.advancedcustomfields.com/forums/topic/conditional-logic-using-taxonomy-field/page/4/ in my post of May 22, 2017 at 11:35 pm I mention the free version of ACF does NOT return $_POST['acf'], hence why my solution didn't work with the free ACF.

**Comment by elliotcondon** [comment]
Hi @Beee4life 

$_POST data is sent with the key 'fields' in ACF 4 and below.
Please see the developer notes here: https://www.advancedcustomfields.com/resources/upgrade-guide-version-5/

Thanks
E

**Comment by Beee4life** [comment]
I saw it returned as 'fields', but I had not expected that. And thus my solution didn't work. 

I expected $_POST['acf'] like in the pro version. Took some debugging to find this out, since I hadn't seen the developer notes for this :) Thanks for the info.
