### ISSUE TITLE
Translation Error German

### ISSUE THREAD

**Issue by Johannes-Hartmann** [elliotcondon/acf#615]
There is an error in the german translation, if you copy a field it shows "Field Title (copy)" as "Field Title (kopieren)" it should say "Field Title (Kopie)" couldn't find it in the .PO or .MO else I would made a pull request.

**Comment by elliotcondon** [comment]
Hi @Johannes-Hartmann 

Thanks for the bug report. Is this for the free or PRO version of ACF?

**Comment by Johannes-Hartmann** [comment]
Sorry @elliotcondon for not mentioning it, it's in the PRO version. I could check the whole thing and send it to you by mail (corrected) if that helps you.

**Comment by Johannes-Hartmann** [comment]
Hi @elliotcondon I just checked the files, it's a more complicated problem, we have two different meanings for the word copy, to copy = kopieren, a copy = Kopie. So changing it will make the label "copy" a field wrong in german.

**Comment by elliotcondon** [comment]
Thanks @Johannes-Hartmann 

I'm able to add 'context' to these strings so that they can be translated into 2 different words.
I'll add this to my to-do and let you know when it is done.

**Comment by elliotcondon** [comment]
Hi @Johannes-Hartmann 

I've just searched the ACF PRO plugin for the string 'copy' but can only see it used ine one context - this field is a copy.

If I'm not mistaken, there is no button or action called 'copy', only the text (copy) that is added the field label.

Can you please help me understand (with a screenshot) where you need to create the 2 different words?

**Comment by Johannes-Hartmann** [comment]
Hey @elliotcondon I made a grave mistake, the button is duplicate, should have looked more thorough. The added text (copy) is (kopieren) in German, which should be (Kopie) 

There are no 2 different words, just a guy who was to tired to look right. Sorry for that.

**Comment by elliotcondon** [comment]
Hi @Johannes-Hartmann 

Thanks for the reply. I'm glad that no changes are needed, and it's always great to check things anyway, cheers!
