### ISSUE TITLE
Uncaught Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element. on Widgets page

### ISSUE THREAD

**Issue by yanuardev** [elliotcondon/acf#616]
Hi @elliotcondon  
I experience this issue on Widgets page, so I can't do anything with my widgets. I tried to deactivate my plugins but no luck. 

I have ACF Pro 5.5.14 installed in my Site. with latest WP version 4.7.5 and all of my plugin is up to date.

Here is my plugin list:

Beaver Builder Plugin (Lite Version)
Version 1.9.5.3 | By The Beaver Builder Team 

Gravity Forms
Version 2.2.3 | By rocketgenius

MailPoet Newsletters
Version 2.7.10 | By MailPoet 

Max Mega Menu
Version 2.3.6 | By Tom Hemsley 

Meta Box
Version 4.11.2 | By MetaBox.io 

WP Customer Reviews
Version 3.1.2 | By Go Web Solutions 

Yoast SEO
Version 4.8 | By Team Yoast 

Thankyou

**Comment by elliotcondon** [comment]
Hi @yanuardev 

Thanks for the bug report, can you please open a support ticket with this same information?
- this github repo is not used for support

https://support.advancedcustomfields.com/new-ticket/

Thanks
Elliot
