### ISSUE TITLE
helpers_get_dir uses file path to calculate url

### ISSUE THREAD

**Issue by leigh-ols** [elliotcondon/acf#628]
```php
        $dir = trailingslashit(dirname($file));
```

This method is fine until you place your plugins outside of the wordpress directory and then symlink them.

`project/wordpress/wp-content/plugins -> project/app/plugins`

The logic behind doing this is to have a git repository for each customer, containing their plugins/themes/custom code, and have WordPress as a submodule to that repository.

However, doing something like this causes the function to break.

**Comment by wcc-neal** [comment]
I discovered this issue a couple years ago as well, and have a fix for it:

https://github.com/elliotcondon/acf/pull/634

**Comment by elliotcondon** [comment]
Hi guys

Yes. ACF 4 contains some 'custom' logic to figure out paths, which seemed like a good idea at the time, but we can all agree it is not a great solution long term.

Please note this issue has been fixed correctly in ACF 5
Please update to ACF 5 when possible :)
https://www.advancedcustomfields.com/blog/acf-5-early-access/
