### ISSUE TITLE
ACF plugin changes Wordpress default calendar/date picker pop up. New calendar does not have arrows to switch months.

### ISSUE THREAD

**Issue by brandoncolchin** [elliotcondon/acf#630]
With plugin deactivated: http://imgur.com/a/QgJ51

With plugin activated: http://imgur.com/a/8qmaL

To be clear, the ACF calendar pop ups work fine, it is the WP calendar pop ups from date fields that gets affected.

**Comment by elliotcondon** [comment]
Hi @brandoncolchin 

Thanks for the topic. Can you please open a support ticket via the link below and be sure to include information about the plugins / theme you are using to replicate the issue (WP does not natively have a 'sale start date'): https://support.advancedcustomfields.com/new-ticket/
