### ISSUE TITLE
Bulk actions missing on sync page

### ISSUE THREAD

**Issue by 0x6C77** [elliotcondon/acf#632]
If there are no active field groups but groups ready to sync no bulk actions are shown on the sync page. Once one of the groups is synced then the bulk actions appear and the remainder can be synced in one go.

It would be useful to have th bulk actions always visible when items are available to save time when syncing lots of groups simultaneously.

**Comment by elliotcondon** [comment]
Hi @0x6C77 

From memory, I believe this bug has been fixed in some recent versions. Let me know if this is working for you.

**Comment by 0x6C77** [comment]
Sorry, yes it was fixed in the latest version.

Thank you for such a brilliant plugin.
