### ISSUE TITLE
Acf pro - Uncaught ReferenceError: acf is not defined

### ISSUE THREAD

**Issue by TanguyS** [elliotcondon/acf#633]
I have this error with acf pro: Uncaught ReferenceError: acf is not defined.

Can you just replace:
wp_register_script( 'acf-pro-input', acf_get_dir( "pro/assets/js/acf-pro-input{$min}.js" ), array('acf-input'), acf_get_setting('version') );
wp_register_script( 'acf-pro-field-group', acf_get_dir( "pro/assets/js/acf-pro-field-group{$min}.js" ), array('acf-field-group'), acf_get_setting('version') );

by:
wp_register_script( 'acf-pro-input', acf_get_dir( "pro/assets/js/acf-pro-input{$min}.js" ), array('acf-input'), acf_get_setting('version'), **true** );
wp_register_script( 'acf-pro-field-group', acf_get_dir( "pro/assets/js/acf-pro-field-group{$min}.js" ), array('acf-field-group'), acf_get_setting('version'), **true** );

true meaning to put the script in the footer. It makes these scripts come necessarily after the acf definition and it removes the error in the console.

Thanks.

**Comment by TanguyS** [comment]
I downloaded the update, seems to be already done. Sorrry.

**Comment by lucioufba** [comment]
I too heve this error with acf pro: Uncaught ReferenceError: acf is not defined.
where I replace this code?

**Comment by jbiddulph** [comment]
Please help, I am having this problem too but I'm not using PRO I also replied to this thread:
https://support.advancedcustomfields.com/forums/topic/uncaught-referenceerror-acf-is-not-defined/#post-129527
