### ISSUE TITLE
Register ACF on Packagist

### ISSUE THREAD

**Issue by loganstellway** [elliotcondon/acf#637]
Hi @elliotcondon ,

Would it be possible to setup this repository with [Packagist](https://packagist.org)?

Thanks!

**Comment by elliotcondon** [comment]
Hi @loganstellway 

It should be, can you please provide some info about how this would benifit?
- I don't use composer / package repositories and don't have much knowledge in this area.

Thanks
Elliot

**Comment by loganstellway** [comment]
Hi @elliotcondon 

I use a WordPress wrapper named [Bedrock](https://roots.io/bedrock/). Bedrock allows WordPress & plugins to be installed and managed with [Composer PHP Package Manager](https://getcomposer.org/) and adds several security enhancements. 

You can [register an account](https://packagist.org/login/) on Packagist using your GitHub account and [submit your package](https://packagist.org/about#how-to-submit-packages). 

I'd be happy to register the package, but only with your permission. 

Further: you can create a [GitHub Service Hook](https://packagist.org/about#how-to-update-packages) to push updates to Packagist whenever you update the GIT repository. Once this is setup, there is no management necessary on the Packagist side of things.

**Comment by elliotcondon** [comment]
Hi @loganstellway 

Thanks mate. 

I've got a bit on my plate at the moment, but will take a look at Bedrock and Packagist shortly.

Is Bedrock able to make use of the WP.org ACF repo? The WP repo would be the more 'official' repository for the free ACF plugin.

**Comment by loganstellway** [comment]
Hi @elliotcondon,

There is a [WordPress Packagist](https://wpackagist.org/search?q=advanced-custom-fields) Composer repository that mirrors the WordPress repositories. 

Found my answer [here](https://support.advancedcustomfields.com/forums/topic/installing-acf5-via-composer/). 

Just for documentation's sake, this is how one would require ACF with Composer:
```
composer config repositories.wpackagist composer https://wpackagist.org
composer require wpackagist-plugin/advanced-custom-fields
```

Sorry for the distraction, but thank you!

**Comment by elliotcondon** [comment]
Hi @loganstellway 

Thanks for the reply. I'm glad there is an existing solution!
I'll consider the Packagist in the future, it seems simple enough.

Hope you are enjoying the plugin!
