### ISSUE TITLE
PHP warnings after update to 5.6.5

### ISSUE THREAD

**Issue by Beee4life** [elliotcondon/acf#639]
I updated to 5.6.5 and now my parts of my site appear to be gone on my live server. It works on dev though... Running PHP 5.6.30 on live server and 7.1 on dev

While checking the error logs I found this:

    PHP Warning: include_once(/home/xxx/domains/domain.com/public_html/content/plugins/advanced-custom-fields-pro/includes/api/api-helpers.php): failed to open stream: No such file or directory in /home/xxx/domains/domain.com/public_html/content/plugins/advanced-custom-fields-pro/acf.php on line 110

    PHP message: PHP Warning:  include_once(): Failed opening '/home/xxx/domains/domain.com/public_html/content/plugins/advanced-custom-fields-pro/includes/api/api-helpers.php' for inclusion (include_path='.:/usr/local/php56/lib/php') in /home/xxx/domains/domain.com/public_html/content/plugins/advanced-custom-fields-pro/acf.php on line 110

    PHP message: PHP Fatal error:  Call to undefined function acf_include() in /home/xxx/domains/domain.com/public_html/content/plugins/advanced-custom-fields-pro/acf.php on line 111', referer: http://www.domain.com/wp/wp-admin/plugins.php?plugin_status=active

N E 1 else experiencing the same ?

**Comment by elliotcondon** [comment]
Hi @Beee4life 

Your error suggests the 'includes/api/api-helpers.php' file does not exist. Please check your files are in tact and your permissions are correct.

Thanks
E

**Comment by Beee4life** [comment]
the files were there... but for some reason an error was triggered... just wanted to let you know.
never mind, will close :)
