### ISSUE TITLE
Uncaught TypeError on new_media_frame

### ISSUE THREAD

**Issue by cgidds** [elliotcondon/acf#641]
I'm running a child theme on WordPress 4.8.3 with ACF Pro 5.5.14. When I try to select a different image loaded in an existing ACF field of type "Image", it results in this JS error in the console:  

```
acf-input.min.js?ver=5.5.14:formatted:2293 
Uncaught TypeError: Cannot read property 'query' of undefined
    at Object.new_media_frame (acf-input.min.js?ver=5.5.14:formatted:2293)
    at Object.popup (acf-input.min.js?ver=5.5.14:formatted:2156)
    at Object.edit (acf-input.min.js?ver=5.5.14:formatted:2102)
    at HTMLAnchorElement.<anonymous> (acf-input.min.js?ver=5.5.14:formatted:840)
    at HTMLDocument.dispatch (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,plupload,jquery-ui-resizable&ver=4.8.3:3)
    at HTMLDocument.r.handle (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,plupload,jquery-ui-resizable&ver=4.8.3:3)
```
Upon looking at the code, this is the function the console error is pointing at in the ACF code. Any ideas?

```
        new_media_frame: function(e) {
            var t = {
                title: e.title,
                multiple: e.multiple,
                library: {},
                states: []
            };
            t = this._get_media_frame_settings(t, e);
            var i = wp.media.query(t.library);
            acf.isset(i, "mirroring", "args") && (i.mirroring.args._acfuploader = e.field),
            t.states = [new wp.media.controller.Library({
                library: i,
                multiple: t.multiple,
                title: t.title,
                priority: 20,
                filterable: "all",
                editable: !0,
                allowLocalEdits: !0
            })],
            acf.isset(wp, "media", "controller", "EditImage") && t.states.push(new wp.media.controller.EditImage);
            var a = wp.media(t);
            return a.acf = e,
            a = this._add_media_frame_events(a, e)
        },
```

**Comment by elliotcondon** [comment]
Hi @cgidds 

Thanks for the email,
Elliot here - ACF dev​​​.

Can you please setup a fresh WP site without any plugins / theme and replicate the issue with only ACF PRO installed?

Next, add in your theme, does this start the issue? If so, there is most likely something in your parent (or child) theme that is causing the JS conflict.

**Comment by cgidds** [comment]
Hi @elliotcondon 

I'm closing this issue. I had a translation plugin that was applying a filter on ACF query results on this child theme, and should have only been filtering on the parent theme. Thanks for responding!

**Comment by marcin-biegun** [comment]
Hi @cgidds,
was it wpml? how to solve?

**Comment by cgidds** [comment]
No, it was qTranslate. If that's what you're using, here are the two filters I applied:

`//-- Translate ACF selector fields
function translate_acf_result( $title, $post, $field, $post_id ) {
	$editLang = $_COOKIE['qtrans_edit_language'];
	if($editLang) {
		return qtranxf_use($editLang, $title, false, false);
	} else {
		return qtranxf_useCurrentLanguageIfNotFoundUseDefaultLanguage($title);
	}
}
//-- Only include these filters if plugin is active
include_once( ABSPATH.'wp-admin/includes/plugin.php' );
if ( is_plugin_active( 'qtranslate-x/qtranslate.php' ) ) {
    add_filter( 'acf/fields/relationship/result', 'translate_acf_result', 10, 4 );
    add_filter( 'acf/fields/post_object/result', 'translate_acf_result', 10, 4 );
    add_filter( 'acf/fields/page_link/result', 'translate_acf_result', 10, 4 );
}`

**Comment by marcin-biegun** [comment]
thanks for reply. in our case it was simpler - front-end dev removed accidentally wp_footer() and needed js wasn't obviously loaded. 
btw seems that wpml integrates better (out of the box) than qtranslate

**Comment by cgidds** [comment]
Ah, glad you figured it out!
Yes, we used to have WPML, but it was much heavier and slower than what we wanted. qTranslate gives us the flexibility we need and is lighter weight.
