### ISSUE TITLE
fallback or information for non-javascript browsers

### ISSUE THREAD

**Issue by matthiaswagnerwy** [elliotcondon/acf#644]
hy elliot,

first of all i want to thank you again for your plugin. i am a pro-user for years and still love it. i just had that moment when i needed to try something in the backend without javascript enabled and saw that some fields like tabs or images do not work. i know that this is because they rely pretty much on javascript, but i guess it would be good to display a warning with css or hide the fields if javascript is not enabled. it will be a rare case that clients operate the cms without js, but we all know what can happen when we rely on clients ;)

hoping for a solution while building a "global warning" in the meantime :)
matt

**Comment by elliotcondon** [comment]
Hi @matthiaswagnerwy 

I will consider this, but will made no promises.
