### ISSUE TITLE
wp.media.view.Attachment is undefined in 5.6.6

### ISSUE THREAD

**Issue by amiut** [elliotcondon/acf#645]
Seems like there's a javascript error in `5.6.5` and `5.6.6` which prevents user to interact with wordpress widgets.
```
TypeError: wp.media.view.Attachment is undefined    --- acf-input.min.js:2:19758
```

**Comment by elliotcondon** [comment]
Hi @amiut 

I'm not able to replicate the issue locally which suggests another variable is at play.
Can you please setup a fresh WP site with only ACF PRO installed to test editing widgets?

I suspect another plugin / theme code is preventing the tinymce scripts from being enqueued on your edit page.

Please also check that all HTML is fully rendered for this page by right clicking the page and clicking 'view page source'. You may find that the HTML is cut off and the footer is not completely rendered. This could explain why the JS is failing.

**Comment by amiut** [comment]
@elliotcondon Yes it was a problem with a script in my theme, sorry it was my bad. problem fixed.
