### ISSUE TITLE
Tag the new version 4.4.12

### ISSUE THREAD

**Issue by capuderg** [elliotcondon/acf#648]
I see that the latest version of ACF v4 is 4.4.12: https://wordpress.org/plugins/advanced-custom-fields/#developers

However there is no tag with that version here in this repo. Could you please tag the latest version here as well? 

Thank you and take care!

PS: Great plugin! Keep up the good work! :)

**Comment by elliotcondon** [comment]
Hi @capuderg 

Thanks for the topic. I've just created the 4.4.12 release, sorry for not doing that earlier.
Be sure to checkout ACF5 (early access):

https://www.advancedcustomfields.com/blog/acf-5-early-access/
https://github.com/AdvancedCustomFields/acf
