### ISSUE TITLE
Relationship field filter by Taxonomies and not Post Type

### ISSUE THREAD

**Issue by cziberez** [elliotcondon/acf#652]
If I have a Woocommerce plugin I can only select product as post type, so the post type filter worth nothing for me. It would be better if I could filter by taxonomies for select.

**Comment by elliotcondon** [comment]
Hi @cziberez 

Please use our support tickets for any questions you may have about the plugin. This repo is for bug reports only. https://support.advancedcustomfields.com/new-ticket/

Please note that the Relationship field does contain a 'taxonomy' filter alongside the 'post object' filter. I will need you to provide a more detailed question in your support ticket.
