### ISSUE TITLE
Selecting value in multi-select taxonomy field hides meta box

### ISSUE THREAD

**Issue by crstauf** [elliotcondon/acf#653]
We've investigated, and the issue has been determined to exist on [line 1243 of input.js](https://github.com/elliotcondon/acf/blob/master/js/input.js#L1243). 

Adding the test made earlier on  [L1210](https://github.com/elliotcondon/acf/blob/master/js/input.js#L1210) to L1243 resolves the issue.

Is this a bug? The comments on [L1239](https://github.com/elliotcondon/acf/blob/master/js/input.js#L1239) would seem to suggest it is expected that the event may be caught in both places, but I don't think that proper (or expected) behavior when selecting a term should be to hide the meta box.

If helpful, I can create a sample ACF field group and provide an export file.

**Comment by elliotcondon** [comment]
Hi @crstauf 

Thanks for the topic.
If your taxonomy field contains the 'save_terms' setting, then yes, selecting a value will affect which metaboxes appear on the page.

if you are experiencing any issues with the plugin, please submit a support ticket here:
https://support.advancedcustomfields.com/new-ticket/

**Comment by crstauf** [comment]
@elliotcondon We do not have the 'save_terms' setting turned on.

This seems like a bug, but if you prefer for me to submit a support ticket, can do; please lmk.

**Comment by elliotcondon** [comment]
Hi @crstauf 

Thanks for the reply. Yes, please submit a support ticket.
You have articulated "where" the issue is, but I'm not 100% sure I understand "what" the issue is.

Please provide us with the info / data necessary to replicate the problem and we will take a look.

**Comment by crstauf** [comment]
Support ticket submitted.
