### ISSUE TITLE
Double Clicking to select field name (UX Issue)

### ISSUE THREAD

**Issue by raajtram** [elliotcondon/acf#654]
Upon double clicking the field name, the next item in the table (field type) also gets selected.

![screen recording 2018-01-14 at 08 20 pm](https://user-images.githubusercontent.com/3751021/34923301-a98ae658-f968-11e7-938c-bcf2c3d485a6.gif)

This is probably a non-issue for most users -- but it might get annoying for some who prefer to copy the field names with ease

**Comment by elliotcondon** [comment]
Hi @raajtram 

Thanks for the bug report.
Can you please add your OS / browser information?

**Comment by raajtram** [comment]
Hey @elliotcondon,

It's Apple Mac (latest) and Chrome (latest).

**Comment by elliotcondon** [comment]
Thanks

**Comment by elliotcondon** [comment]
Hi @raajtram 

I've just fixed the issue by adding in a whitespace before the field's name, key and type.

**Comment by raajtram** [comment]
Beautiful, thanks! @elliotcondon.
