### ISSUE TITLE
show parameter for add_meta_box callback no longer supported

### ISSUE THREAD

**Issue by yavormilchev** [elliotcondon/acf#657]
In WordPress 4.9.2 all custom fields are visible on all post types because the `show` parameter here is ignored. 

https://github.com/elliotcondon/acf/blob/master/core/controllers/post.php#L211

Can you please release a fix for this issue? Is there any reason why the `add_meta_box` call can't just be skipped if `$show === false`?

**Comment by elliotcondon** [comment]
Hi @yavormilchev 

Thanks for the topic.
I have just performed some testing and can confirm there is no issue with this $show functionality.
Please check your console log for any JS errors and let me know what you find.

**Comment by yavormilchev** [comment]
Interesting, I suppose there was some error after the upgrade which is now resolved (after other changes were merged in) since I'm not longer able to replicate. Sorry about that!

**Comment by yavormilchev** [comment]
@elliotcondon In case you are interested, the problem was that the scripts were not being loaded because of how the script URLs were generated. Our plugins were symlinked from another folder and it looks like you recently fixed that :) https://github.com/elliotcondon/acf/commit/f9ce9f569e64d3c7fcfc033161476e9bf30d251c

We are using `wpackagist-plugin/advanced-custom-fields` which still hasn't pulled that change.
