### ISSUE TITLE
[Feature Request] Add a repeater unique id or new field type unique_id

### ISSUE THREAD

**Issue by ggedde** [elliotcondon/acf#660]
Since this isn't required by all it should be an option when creating a repeater.  Like "Include Unique ID".  This value then gets returned when grabbing the repeater values.  Maybe as "_unique_id", etc. That way if the client changes the content or re-arranges the order it still has the same unique id for that row.

Or maybe better would be to create an new field type called unique_id.
Then when creating the repeater fields I will just include the unique_id as one of the sub_fields.
This field should not be editable and possibly hidden or allow for option to hide or show.  This might be better as we can change the label and name, etc.

The use case for this is I need a global array of items that the client can create/manage.  When creating posts they can choose which ones they want to use, but I would like for them to be able to edit the global items and have them get updated on all posts.  The issue is I have know way of linking the items together if the client changes the content for the global items. 

I could create a post type or taxonomy for this, but then I would have to do a lot of configuring them like removing functionality, from search, etc.

I could also require the client to use a unique id or possibly do some acf/filters to do this, but I would like to see an easy integration for this.

**Comment by elliotcondon** [comment]
Hi @ggedde 

Thanks for the feature request.
This is a great idea, but perhaps something best left to a 3rd party plugin.

I've had a quick look and have found something perfect:
https://wordpress.org/plugins/acf-unique-id-field/

**Comment by ggedde** [comment]
@elliotcondon 
Wow, I didn't see that when I was first looking.
Haven't tried it yet, but I am sure it is what I was thinking of.
Thanks

**Comment by ggedde** [comment]
Tried it and it works great!
Thanks!
