### ISSUE TITLE
Misleading field name (applies to Pro as well) (en-US)

### ISSUE THREAD

**Issue by gicolek** [elliotcondon/acf#662]
Hello,

The en-US translations are a bit wrong when it comes to the Taxonomy related naming. I've managed to recreate the issue on a fresh WP install with fresh ACF installed.

Basically the "Taxonomy Term" is listing a number of "Taxonomies", not "Taxonomy Terms" https://www.screencast.com/t/ABnVBJl8UH. Similarly the field "Post Taxonomy" lists "Post Taxonomy Terms". In a nutshell the naming is wrong and should be reversed between the two. 

It's a small issue but makes me confused all the time.

FYI: https://codex.wordpress.org/Taxonomies (I'm more than certain you know that ;))

**Comment by elliotcondon** [comment]
Hi @gicolek 

Thanks for the feedback.
I completely agree with you on this, and is something I should change.

I'm happy to change 'Taxonomy Terms' to 'Taxonomy'. This makes more sense
As for 'Post Taxonomy', although technically this is talking about the 'terms', it is more readable to have 'Post Taxonomy' to match the other 'Post Category' location rule.

Let me know what you think about the later.

Thanks
Elliot

**Comment by gicolek** [comment]
Hello Elliot,

I totally forgot about this thread and for whatever reason I didn't get a notification ;)

From what I see you have already applied a fix so thanks for that a lot!

Cheers,
Rafal
