### ISSUE TITLE
Broken Button Group and a console error

### ISSUE THREAD

**Issue by asha23** [elliotcondon/acf#667]
Latest version of ACF Pro.

Can't do a conditional using the button group and my console throws the following error. Also. The flexible content field won't allow me to add content.

Uncaught TypeError: Cannot set property 'toolbars' of undefined at post-new.php?post_type=acf-field-group:902

It's unusable for me at the moment. Any ideas?

**Comment by elliotcondon** [comment]
Hi @asha23 

Please be sure to submit a support ticket here:
https://support.advancedcustomfields.com/new-ticket/

It sounds like you have a JS error on the page which is preventing any other JS from running.
'toolbars' is related to the WYSWIG field, so perhaps there is an issue rendering the footer of your page (scripts, assets, JS, etc).

Please check your page's source code and try setting up a fresh WP install with only ACF PRO installed. Add in your plugins one by one until the issue begins - you may find that a specific plugin / theme code causes the problem.
