### ISSUE TITLE
Typo in gallery field PHP?

### ISSUE THREAD

**Issue by ErinPo** [elliotcondon/acf#675]
Around line 144 in file pro/fields/class-acf-field-gallery.php of ACF v5.6.10 reads:

`if ( !current_user_can( 'edit_post', $id ) )`

However, the WP default permission for this uses the plural form 'edit_posts'.

**Comment by elliotcondon** [comment]
Hi @ErinPo 

This conditional statement is to check that the current user can edit the current $attachment.
Is there a reason you have flagged this as a bug?

**Comment by ErinPo** [comment]
Oh, sorry, it is meant to be an ACF capability. I thought it was supposed to integrate with the native WP capability 'edit_posts'.

Should plugins perhaps prefix their capabilities (acf_edit_post) to avoid such confusion? I am not aware of the recommended convention for this.

**Comment by elliotcondon** [comment]
Hi @ErinPo 

This 'edit_post' capability is part of WP core. This is not part of the ACF plugin and does not require an 'acf' prefix.

You can find this capability mentioned in the WP documentation for `current_user_can()` and many times within the WP core.

I don't think there is any need to flag this as an issue.

**Comment by ErinPo** [comment]
You're right, you can go ahead and close it as an issue.

I was confused because https://codex.wordpress.org/Roles_and_Capabilities only references the plural spelling (edit_posts), so I thought edit_post was not native to WP.
