### ISSUE TITLE
Store fields on option page as serialized array

### ISSUE THREAD

**Issue by billerickson** [elliotcondon/acf#68]
For options, it's a good practice to create a single option and store all your data in there as a serialized array rather than to create an option for each one.

Is adding an option on how the data is stored on the roadmap?

**Comment by BoweFrankema** [comment]
I was wondering if this is still planned?

**Comment by elliotcondon** [comment]
Hi guys

Thanks for the feature request. Yes, this is a good idea for small data, but when you start talking about rows of repeater field data including WYSIWYG fields, this is not a possibility.

I have just added a new setting to ACF PRO which allows you to enable the autoload for the options page values. This may help to quickly load global settings.

It is also possible that you can hook into the `acf/save_post` action and save all the `$_POST['fields']` data into your own wp_options row:
http://www.advancedcustomfields.com/resources/acfsave_post/?version=4
https://codex.wordpress.org/Function_Reference/update_option
