### ISSUE TITLE
Required validations with Gutemberg

### ISSUE THREAD

**Issue by r3tr0k3r** [elliotcondon/acf#682]
If using Gutemberg you leave blank a field marked as required, the post is not saved and does not show any error message. It keeps infinitely saving

**Comment by elliotcondon** [comment]
Hi @r3tr0k3r 

Thanks for the bug report. The Gutenberg plugin currently breaks most of ACF's JS.
This will be tested and fixed before the Gutenberg editor is merged into core :)
