### ISSUE TITLE
blank page when submitting form

### ISSUE THREAD

**Issue by mjugarte** [elliotcondon/acf#691]
i created a form using the code below. when submitting, the page doesn't refresh. i just get a completely blank page. if i refresh i get a "Confirm Form Resubmission" msg. if i highlight url and enter, the page refreshes and the data is saved. any ideas?? thx!

FORM CODE:
function my_acf_user_form_func( $atts ) {
 
  $a = shortcode_atts( array(
    'field_group' => '2679'
  ), $atts );
 
  $uid = get_current_user_id();
  
  if ( ! empty ( $a['field_group'] ) && ! empty ( $uid ) ) {
    $options = array(
      'post_id' => 'user_'.$uid,
      'field_groups' => array( intval( $a['field_group'] ) ),
      'return' => add_query_arg( 'updated', 'true', get_permalink() ),
	  'updated_message' => __("Thank you! Your dietary preferences have been updated.", 'acf')
	  
    );
    
    ob_start();
    
    acf_form( $options );
    $form = ob_get_contents();
    
    ob_end_clean();
  }
  
    return $form;
}

//add_action( 'init', 'acf_head_add' );

// function acf_head_add(){
//   if( !is_admin() ) // alex: load in front-end only!
       //  acf_form_head();

add_shortcode( 'my_acf_user_form', 'my_acf_user_form_func' );
// }

SAVE FORM CODE:
//adding AFC form head
function add_acf_form_head(){
    global $post;
    
  if ( !empty($post) && has_shortcode( $post->post_content, 'my_acf_user_form' ) ) {
        acf_form_head();
    }
}
add_action( 'wp_head', 'add_acf_form_head', 7 );

**Comment by elliotcondon** [comment]
Hi @mjugarte 

Thanks for the question. Can you please contact our support team for any ACF related quesitons:
https://www.advancedcustomfields.com/contact/

If you are experiencing a "white screen of death", it is most likely you are encountering a PHP error which you will need to debug.
