### ISSUE TITLE
Show Pages before Posts in autocomplete?

### ISSUE THREAD

**Issue by collinanderson** [elliotcondon/acf#694]
Hi All,

My website has a _bunch_ of Posts, but usually I want my fields to link to _Pages_ (though _sometimes_ posts). Is there any way to get the Pages to show up before Posts in autocomplete dropdowns?

Thanks,
Collin

**Comment by elliotcondon** [comment]
Hi @collinanderson 

Thanks for the question.
This is easily customized in ACF5 by either:
1. When editing your "post object" field, select the post types you would like available and re-arange them into the desired order
2. Hook into the "acf/get_post_types" filter and change the default order of $post_types parameter.

Thanks
Elliot

FYI. Next time, please submit a support ticket for any ACF questions :)
http://www.advancedcustomfields.com/contact/

**Comment by collinanderson** [comment]
Thanks! I'll use support next time.
