### ISSUE TITLE
Broken WYSIWYG on Firefox and IE

### ISSUE THREAD

**Issue by treyssatvincent** [elliotcondon/acf#695]
We've updated ACF to the last version and now the ACF's WYSIWYG on the front are unusable.

They are just displayed as unfillable textaeras of 1 line.

With Firefox : 

<img width="782" alt="withfirefox" src="https://user-images.githubusercontent.com/18269685/42171729-5ca7964c-7e1a-11e8-9770-e674e2c36698.png">

With Chrome it works fine : 
<img width="395" alt="withchrome" src="https://user-images.githubusercontent.com/18269685/42171923-df4610ce-7e1a-11e8-9e0f-f0494b7d2205.png">

Any idea why ?

Wordpress version : 4.9.6
ACF version : 5.6.10

**Comment by elliotcondon** [comment]
Hi @treyssatvincent 

Thanks for the issue. For all support inquiries, please contact our support team:
http://www.advancedcustomfields.com/contact/

Please be sure to include all the plugins / versions needed to replicate this issue.
