### ISSUE TITLE
Call to undefined function get_field()

### ISSUE THREAD

**Issue by dhaval47** [elliotcondon/acf#697]
I am working on my custom plugin for requirement.

In PHP file while fetch data it shows **Call to undefined function get_field()** 

This is my code
`$use = get_field('use', $post_id);`

**Comment by dhaval47** [comment]
Any way to include ACF's get_field() in my custom plugin ?

**Comment by elliotcondon** [comment]
Hi @dhaval47 

This is a bit of an odd question. It's like you are asking WP how to include a core WP function in your plugin.

If you would like to use the ACF functionality of the `get_field()` function, you will need to require ACF to be installed, or consider including the plugin within your plugin's code.
