### ISSUE TITLE
Possibility of adding Chosen for selects

### ISSUE THREAD

**Issue by jackmahoney** [elliotcondon/acf#70]
Hi Elliot, big fan of your work.

One suggestion: would you consider using Chosen (http://harvesthq.github.io/chosen/) for selects? Some selects can end up being very large on big sites and adding chosen would provide a better user experience. The post-item field is a good example as sites may have hundred of posts. I'd also suggest using <optgroup> tags in this instance.

Cheers

**Comment by micelestium** [comment]
https://wordpress.org/plugins/sw-chosen/

works just fine ;-)

**Comment by elliotcondon** [comment]
Hi guys.

Select2 has been added to ACF PRO and will soon make it's way to the free version (v5)

**Comment by cr101** [comment]
This might help [WooCommerce Forks select2](https://wptavern.com/woocommerce-forks-select2-releases-selectwoo-as-a-drop-in-replacement-with-improved-accessibility)

**Comment by elliotcondon** [comment]
Hi @cr101 

Select2 has been added to ACF PRO and will soon make it's way to the free version (v5)
ACF v5 is currently available for Early Access! Be sure to try it out
https://www.advancedcustomfields.com/resources/beta-test-version-5/
