### ISSUE TITLE
Creating a WP archive with custom field filter array error

### ISSUE THREAD

**Issue by chinatownlee** [elliotcondon/acf#701]
The provided code in the tutorial results (https://www.advancedcustomfields.com/resources/creating-wp-archive-custom-field-filter/) in an array error just as the people described in their posts.

_Warning: array_merge(): Argument #2 is not an array in C:\wamp64\www\wordpress\wp-content\plugins\advanced-custom-fields\core\api.php on line 264_

https://support.advancedcustomfields.com/forums/topic/filter-checkbox-error-warning-array_merge-argument-2-is-not-an-array/

https://support.advancedcustomfields.com/forums/topic/wp-archive-with-custom-field-filters/

Please fix this.

**Comment by elliotcondon** [comment]
Hi @chinatownlee 

Thanks for the bug report. I've just updated the plugin files to fix this issue.

**Comment by elliotcondon** [comment]
Hi. At this stage, I'm not sure when we will release an update for the 4.x version. We are encouraging everyone to upgrade to 5.x ahead of the public release later this year. To learn more about v5, please checkout this guide: https://www.advancedcustomfields.com/resources/upgrade-guide-version-5/

**Comment by chinatownlee** [comment]
So just to be clear, the issue has been resolved in v5? If so I will procceed with the v5.

**Comment by elliotcondon** [comment]
Hi @chinatownlee 

We have updated the ACF 4.x plugin files on github here:
https://github.com/elliotcondon/acf/

We have also fixed this issue many years ago in ACF v5.
