### ISSUE TITLE
Question: is _wp_attachment_context removed ?

### ISSUE THREAD

**Issue by Beee4life** [elliotcondon/acf#703]
I noticed recently that ACF doesn't seem to store the meta field _wp_attachment_context anymore for attachments.

Has this been done with a certain reason or has the meta key changed ?

**Comment by elliotcondon** [comment]
Hi @Beee4life 

Thanks for the question.
Yes, the 'context' has been removed from the `wp_insert_attachment()` call after a recent bug report found this prevented WP from showing the uploaded file in the media grid.

This looks like a bug in WP core which prevents uploads appearing if they have a "context" value. I'm sure WP have a reason for this - perhaps they use it as a way to "hide" featured/cropped/duplicate images?

Sorry if this has caused any issues/headaches on your end, but we think this is the best interest of developers using ACF on a front-end form uploading attachments.

Thanks
E

**Comment by Beee4life** [comment]
I hadn't noticed that particular bug yet.

I use a (custom) image plugin which renames uploaded media which checked for this meta data... Now it's not the end of the world because I can find a way around it :) but was just surprised my images showed 'real names' again...

Is there something unique which has come in place of this ?

**Comment by elliotcondon** [comment]
Thanks for the reply.
No, there is nothing unique that has been added instead, we simply removed the 'context' value from the $args used in this function.

**Comment by Beee4life** [comment]
Ok thanks....

**Comment by Beee4life** [comment]
Is there a way to 'hook' into this and add my own custom meta ? Would help a lot.

**Comment by Beee4life** [comment]
I have 1 image field (basic uploader) and a gallery. I want to distinct between the two uploads. With the previously used meta I could, because only the basic uploader added this meta.

I wrote a custom plugin which renames file names upon upload (which hooks into add_attachment). With that meta value being added I could exclude the gallery from this function and do the renaming on acf/save_post instead, because generating new thumbnails (for the preview) doesn't seem to work. So I want to do this on acf/save_post (which works).

I haven't been successful so far in adding any, so I thought maybe you could point me in the direction.

**Comment by Beee4life** [comment]
Thanks to @Hube2 who [reminded](https://support.advancedcustomfields.com/forums/topic/validation-looks-unexpected/) me of $_POST values I think I now can... Will do some more testing, but looks good.
