### ISSUE TITLE
Sync question

### ISSUE THREAD

**Issue by Beee4life** [elliotcondon/acf#706]
Can it be that recent updates have changed some things regarding group syncing ? We noticed everal times fields were not properly synced when switching between 2 different (ACF) versions. 

I am on 5.7.2 and my colleague was on 5.6.10 (now 5.7.2).

After he updated to 5.7.2 the issues were gone.

**Comment by elliotcondon** [comment]
Hi @Beee4life 

Thanks for the email.
We haven't made any specific changed to the 'sync' functionality, but if you are having any issues, please contact our support team and we will do our best to replicate and diagnose the issue.

**Comment by elliotcondon** [comment]
Contact support link: http://www.advancedcustomfields.com/contact/
