### ISSUE TITLE
ACF and insert_post

### ISSUE THREAD

**Issue by milossh** [elliotcondon/acf#707]
get_field() returns false for posts(tested on custom post type) that were created programmatically. If I create post with wp_insert post, set title, content, status, post_type, everything is ok with wordpress, but if I try to get_field(), it returns false. If i now go to wp-admin post edit, simply click update, get_field() works as expected. Now, I tried to first use wp_insert_post, and then wp_update_post changing its status to publish, but that didn't get me anywhere. I have also tried to compare post fields in wp_posts table, but they're literally the same, and in wp_post_meta, I can see my ACF fields populated properly.

**Comment by milossh** [comment]
I'm not sure if this is a bug or not, but if you use field key for update_field instead of field name, it works properly.

**Comment by elliotcondon** [comment]
Hi @milossh 

Thanks for the topic.
The issue here is related to the "reference value" which is used by ACF to connect a value to a field.

Although important, it shouldn't be preventing a value from being loaded.
Can you please provide some example code that I can use to replicate the issue?

**Comment by milossh** [comment]
Follow next steps:

1) Use CPT UI to create a new Post Type, set slug to 'ugovor'
2) Add new custom field, set condition to show on newly created post type, set it to Select Type and add some values, like: 1 : 'Foobar'
3) In your functions.php, run this code:

```
$ip_args = array(
	'post_title' => 'My testing new CPT instance',
	'post_type'=>'ugovor',
	'post_author' => 12, // User ID
	'post_content' => 'Some test content for my new post',
	'post_category' => 1
);

$nc_id = wp_insert_post($ip_args);

// Update new post to Published
wp_update_post(array(
	'ID' => $nc_id,
	'post_status'  => 'publish'
));

if( $nc_id ) {
	update_field( 'my_field_slug', '1', $nc_id );
}
```

**Comment by elliotcondon** [comment]
Hi @milossh 

Thanks for the reply. I have just trued this exact code, but changed 'my_field_slug' to match my field 'ugovor_select' but cannot find any issue.

All data was entered into the DB correctly, and ACF was able to load the value via get_field() as expected.

Perhaps this issue is specific to the ACF version you are using. What version of ACF / ACF PRO do you have installed?
