### ISSUE TITLE
Post Object field always returning post_ids

### ISSUE THREAD

**Issue by Jebble** [elliotcondon/acf#709]
WordPress: 4.9.7
ACF Pro: 5.7.3

The Post Object field type always returns the Post ID's even if the output is set to Post object.

The exact setup this is happening in is:

ACF Options Page --> Repeater Field --> Post object field

**Comment by elliotcondon** [comment]
Hi @Jebble 

Thanks for the bug report. Can you please submit this issue through our support channel here:
http://www.advancedcustomfields.com/contact/

Please be sure to include some more description about the issue, including an export of your field group, relevant code, and instructions to replicate the issue.

Thanks
E
