### ISSUE TITLE
Issue writing to ACF using Python script 

### ISSUE THREAD

**Issue by racindustries** [elliotcondon/acf#711]
I am trying to automate custom fields filling the following way : 

- A python script grabs data online, transforms and classify it 
- Data is sent to wordpress and auto inserted in ACF 
- Custom Post Type is ready to be published 

So far I tried using the _xml-rpc python library_ and its _custom_fields object_ to fill ACF but it doesn't work. 

Is there any issue with this process ? 

Thanks !

**Comment by elliotcondon** [comment]
Hi @racindustries 

Thanks for the question, but I do not know the answer to this. I have no experience with python. Please direct your question to the `xml-rpc python library` developers.
