### ISSUE TITLE
"Custom Fields" chekbox and panel in Creen Options no longer visible

### ISSUE THREAD

**Issue by s3w47m88** [elliotcondon/acf#724]
As of the current public version of ACF Free the "Custom Fields" checkbox and respective panel that is available via Screen Options is no longer visible at all.

**Comment by elliotcondon** [comment]
Hi @s3w47m88 

Thanks for the bug report. Can you please attach some screenshots to help explain the issue?

**Comment by s3w47m88** [comment]
That makes sense. Thanks! You can close this if you haven't already.
