### ISSUE TITLE
Max of 3 "keywords" when registering a Gutenberg block

### ISSUE THREAD

**Issue by jameelmoses** [elliotcondon/acf#725]
Something that’s in Gutenberg’s documentation but not ACF’s: max of three keywords per block. If you put in four or more values in the `keywords` array it simply won’t show up as an available block in the editor.

see: https://wordpress.org/gutenberg/handbook/block-api/#keywords-optional

"Sometimes a block could have aliases that help users discover it while searching. For example, an image block could also want to be discovered by photo. You can do so by providing an array of terms (which can be translated). It is only allowed to add **as much as three terms per block**."

**Comment by elliotcondon** [comment]
Hi @jameelmoses Thanks for the bug report. I've just opened a ticket with the Gutenberg developers and will also be sure to `array_reduce()` the keywords down to 3 max
