### ISSUE TITLE
acf_register_block: documentation does not spell out that "name" has same limitations as Gutenberg

### ISSUE THREAD

**Issue by benvoynick** [elliotcondon/acf#727]
[Per Gutenberg documentation](https://wordpress.org/gutenberg/handbook/block-api/#block-name) block names "can only contain lowercase alphanumeric characters and dashes, and must begin with a letter." ACF's acf_register_block function therefore has the same restrictions so far as I can tell.

Not a problem that ACF has the same restrictions as Gutenburg. Opening this issue to suggest adding this to the documentation for the name parameter for the acf_register_block function.

**Comment by elliotcondon** [comment]
@benvoynick Thanks. I'll update the docs :)
