### ISSUE TITLE
Fields Published on Preview in Gutenberg

### ISSUE THREAD

**Issue by Kevinlearynet** [elliotcondon/acf#730]
When using the Gutenberg editor with _5.8.0-beta3_ changes to standard (non-block) ACF fields are being saved when a post is previewed rather than updated.

**Steps to reproduce**
1. Change the value of an ACF field on a post using the Gutenberg editor
2. In the top right of Gutenberg, click the "Preview" button
3. Open the published URL for that post (not the draft/preview URL) and you will see the change has published

**Comment by Kevinlearynet** [comment]
@elliotcondon 

Haven't used another "metabox" plugin for years 👍 

You're right, it's a Gutenberg issue.

I disabled ACF and installed/enabled the built-in "Custom Fields" metabox using this plugin: [Custom Fields for Gutenberg](https://wordpress.org/plugins/custom-fields-gutenberg/). When I change the value here and preview, it publishes/updates it. 

I'll file an issue on the Gutenberg project about it. Thanks for the quick follow-up!

**Comment by Soean** [comment]
There is a > 7 years old Ticket about this issue in trac, see https://core.trac.wordpress.org/ticket/20299
