### ISSUE TITLE
ACF Link Field Target Data Returned

### ISSUE THREAD

**Issue by pierrerocket** [elliotcondon/acf#731]
Hello. 

I was clearing validation errors prelaunch for another dev here.  
One of the validation errors I keep running into was:
 
`Bad value  for attribute target on element a: Browsing context name must be at least one character long.`

Looking at the code I realized this is because the developer is using the example verbatim from your link page here:
https://www.advancedcustomfields.com/resources/link/

If the checkbox for open in new isnt checked this returns empty data and you get a validation error on target="".  Ideally this would return _self if this option is not checked for the usage example in your documentation.

**Comment by pierrerocket** [comment]
easy enough to get around with an if/else on the variable 

$icon_link = get_sub_field( 'icon_link' );
if ( ! empty( $icon_link['target'] ) ) {
$icon_link_target = $button['target'];
} else {
$icon_link_target = "_self";
}
?>

But it still seems like it would be most logical for this to return _self if not checked.

**Comment by elliotcondon** [comment]
@pierrerocket thanks for the feedback. I'll update the docs :)
