### ISSUE TITLE
non-dashicon custom icon when registering a Gutenberg block?

### ISSUE THREAD

**Issue by jcklpe** [elliotcondon/acf#732]
Anyway to do that? Maybe it's obvious but I wanted to check.

**Comment by elliotcondon** [comment]
Hi @jcklpe 

Currently, the 'icon' setting may be set to a "dash icon" name, or a custom "svg":
https://www.advancedcustomfields.com/resources/acf_register_block/

Please note that the "svg" options is not currently working, however, we will be working on a solution for this in 5.8

**Comment by jcklpe** [comment]
Thanks Elliot! Loving the beta so far!
