### ISSUE TITLE
Gutenberg editor prevent links redirection

### ISSUE THREAD

**Issue by GregoireSailland** [elliotcondon/acf#736]
Hi elliot!
I'm using acf pro and created some custom blocks for gutenberg.
The problem is in preview mode the acf fields are rendered as in front end and a link make the editor leave to the link target.
My question is:
How to render a different view in gutenberg editor and in front end.
is it possible to use a different callback in editor or to render differently depending on a condition like 
`<?= (is_gutenberg_editor()?"<div.link>":"<a href=...>") ?>`

**Comment by elliotcondon** [comment]
Hi @GregoireSailland 

Please use the `$is_preview` parameter provided to detect if you are previewing the block (backed) or not front end). https://www.advancedcustomfields.com/resources/acf_register_block/
