### ISSUE TITLE
ACF showing under "Advanced Panels"

### ISSUE THREAD

**Issue by adleviton** [elliotcondon/acf#737]
Not sure if I'm missing something, but I can't figure out why ACF is showing under "Advanced Panels".

![image](https://user-images.githubusercontent.com/2176348/50407713-cc9a2680-07aa-11e9-9fc0-97de2c762525.png)

**Comment by elliotcondon** [comment]
Hi @adleviton

This is a known issue we are currently working on.
Please stay tuned to the following GitHib issue which we will keep updated over the coming months.
https://github.com/WordPress/gutenberg/issues/12692
