### ISSUE TITLE
Block preview doesn't show posts if 'cat' is not set in the WP_Query

### ISSUE THREAD

**Issue by sebrosen** [elliotcondon/acf#741]
I'm creating a grid post block that can showcase your latest posts or posts by chosen categories.

I have found that if I don't provide a 'cat' to the WP_query, then the block preview will not display anything. However as soon as a category has been set, the preview show posts correctly.

Here's a simple example for a render callback:

```
$args = array(
	'posts_per_page' => 3,
)

$query = new WP_Query( $args );

if($query->have_posts()) : while ($query->have_posts()) : $query->the_post();
	echo the_title();
endwhile; wp_reset_postdata(); endif;
```

If we do this, the block preview won't show anything, however if we publish the page/post they do display on the live page/post.

If I add a 'cat' parameter to the above $args, then the block preview will correctly show the post titles.

Am I doing something obviously wrong? Or maybe there's a bug?

Cheers!

**Comment by elliotcondon** [comment]
Hi @sebrosen 

The issue is most likely related to modifying global query arguments.
Please use `get_posts()` instead of `new WP_Query()` and see if that helps.
* Please note this function returns an array of posts, and not an object with functions.

**Comment by sebrosen** [comment]
Thanks, get_posts works for showing most recent posts in the block preview
