### ISSUE TITLE
Gallery field and Gutenberg - block preview should be refreshed when sorting images

### ISSUE THREAD

**Issue by virgo79** [elliotcondon/acf#743]
Hi,
when using acf gallery in gutenberg the block preview that renders the images does not refresh when sorting the images using drag and drop.
Maybe this has been fixed for a next release, but in the meanwhile I've resolved the problem adding the `update` event to the `Sortable` object (in `acf-pro-input.js`), as following:

```
var _input = this.$input();

// add sortable
this.$collection().sortable({
	items: '.acf-gallery-attachment',
	forceHelperSize: true,
	forcePlaceholderSize: true,
	scroll: true,
	start: function (event, ui) {
		ui.placeholder.html( ui.item.html() );
		ui.placeholder.removeAttr('style');
		},
	update: function( event, ui ) {
		_input.trigger('change');//this refresh the block preview
	}
});
```

The refresh should be also trigger when updating the attachment fields (title, caption, .. )

**Comment by elliotcondon** [comment]
@virgo79 I've added this to 5.7.11.
