### ISSUE TITLE
[feature request] default alignment option for acf_register_block

### ISSUE THREAD

**Issue by virgo79** [elliotcondon/acf#745]
Hi,
I would like to suggest an option like `default_align` to set a default (initial) alignment option value.
So that a block could be rendered with a specific alignment status when it will be created.

Something like this

```
acf_register_block( array(

   ...
  
  'supports'  => array(
    'align' => array('left', 'center', 'right', 'wide', 'full'),
  ),

  //block will be created full
  'default_align' => 'full'

));
```

**Comment by elliotcondon** [comment]
Hi @virgo79 

Good news. This is already possible. Please see the "align" setting:
https://www.advancedcustomfields.com/resources/acf_register_block/
