### ISSUE TITLE
Wrong Value Output in Repeater Field since ACF 5.7.11

### ISSUE THREAD

**Issue by rogerburkhard** [elliotcondon/acf#747]
Hi,

I've just updated to ACF 5.7.11 and found a very strange bug. I have a Repeater Field:

```
<?php while (have_rows('content_boxes')) : the_row(); ?>
    <?php echo get_sub_field('title'); ?>
    <?php echo get_sub_field('text'); ?>
<?php endwhile; ?>
```

While this works perfectly fine with ACF 5.7.10 and below with the latest version the get_sub_field('text') is rendered with the title field.

Which means instead of output:

Title
Text
Title
Text

it outputs:

Title
Title
Title
Title

**Comment by elliotcondon** [comment]
Hi @rogerburkhard 

You are not the only one experiencing this issue, but I am unable to replicate it for myself.
Can you please export the .json field group so can import the exact fields?

**Comment by rogerburkhard** [comment]
Hi @elliotcondon 

thanks for looking into this.
Additional Information: Activated Classic Editor V. 1.4

Here is the export:

`[
    {
        "key": "group_5c1cc4ec200e0",
        "title": "About",
        "fields": [
            {
                "key": "field_5c1cc503a56c8",
                "label": "Inhaltsboxen",
                "name": "inhaltsboxen",
                "type": "repeater",
                "instructions": "",
                "required": 1,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "collapsed": "",
                "min": 0,
                "max": 0,
                "layout": "table",
                "button_label": "Inhaltsbox hinzufügen",
                "sub_fields": [
                    {
                        "key": "field_5c1cc572d553e",
                        "label": "Titel",
                        "name": "titel",
                        "type": "text",
                        "instructions": "",
                        "required": 0,
                        "conditional_logic": 0,
                        "wrapper": {
                            "width": "",
                            "class": "",
                            "id": ""
                        },
                        "default_value": "",
                        "placeholder": "",
                        "prepend": "",
                        "append": "",
                        "maxlength": ""
                    },
                    {
                        "key": "field_5c1cc539a56c9",
                        "label": "Text",
                        "name": "text",
                        "type": "wysiwyg",
                        "instructions": "",
                        "required": 1,
                        "conditional_logic": 0,
                        "wrapper": {
                            "width": "",
                            "class": "",
                            "id": ""
                        },
                        "default_value": "",
                        "tabs": "all",
                        "toolbar": "full",
                        "media_upload": 1,
                        "delay": 0
                    },
                    {
                        "key": "field_5c1cc546a56ca",
                        "label": "Bild",
                        "name": "bild",
                        "type": "image",
                        "instructions": "",
                        "required": 1,
                        "conditional_logic": 0,
                        "wrapper": {
                            "width": "",
                            "class": "",
                            "id": ""
                        },
                        "return_format": "url",
                        "preview_size": "thumbnail",
                        "library": "all",
                        "min_width": "",
                        "min_height": "",
                        "min_size": "",
                        "max_width": "",
                        "max_height": "",
                        "max_size": "",
                        "mime_types": ""
                    }
                ]
            }
        ],
        "location": [
            [
                {
                    "param": "post_template",
                    "operator": "==",
                    "value": "default"
                }
            ]
        ],
        "menu_order": 0,
        "position": "normal",
        "style": "default",
        "label_placement": "top",
        "instruction_placement": "label",
        "hide_on_screen": [
            "the_content",
            "excerpt",
            "discussion",
            "comments",
            "revisions",
            "slug",
            "author",
            "format",
            "featured_image",
            "categories",
            "tags",
            "send-trackbacks"
        ],
        "active": 1,
        "description": ""
    }
]`

**Comment by elliotcondon** [comment]
@rogerburkhard Thanks for the data. 

I believe the issue you are facing is one that I have fixed today.
Can you please re-download the ACF PRO plugin files and test the issue?

An easy way to re-download is to edit the main acf.php plugin file and change the version number '5.7.11' down to '5.7.10'
- please note the version number appears twice in this file and both will need to be changed
- after this change is made, please update the plugin as per normal and it will update to 5.7.11 (including the new fix)

**Comment by rogerburkhard** [comment]
@elliotcondon 

Just updated to 5.7.11 and the issue is fixed.
Thanks a lot!
