### ISSUE TITLE
ACF fields don't show in Gutenberg when position is "Top (after the title)" - WP 5.1

### ISSUE THREAD

**Issue by Threesixty** [elliotcondon/acf#751]
Dear Elliot,

Everything is explained in the title. Hope it helps.

Regards,
Michael

**Comment by elliotcondon** [comment]
@Threesixty 

Thanks for the bug report.
I believe this is the case when no other field groups are displayed in the "normal" position.
We've got this on our to-do and will get this fixed in the next version :)

**Comment by prajapatisagar** [comment]
@elliotcondon Any solution on this?

**Comment by elliotcondon** [comment]
Hi @prajapatisagar 

We've made a lot of improvements in this space during the year. If you are experiencing an issue where the "After Title" location is not working, can you please provide a full explanation of the issue?

If it's not too much to ask, can you please spin up a fresh WP site and provide me with the step by step instructions to replicate the issue on that site?

**Comment by prajapatisagar** [comment]
Hello @elliotcondon 

Thank you for the response...

I have installed fresh WordPress with ACF Pro 5.8.3 in my local environment. And also created the field group for the post type page. I need ACF field just after title So I have set position "high (After title)". But it is displaying after content, not after title. Here is the exported JSON file for your checking purpose.

> [
    {
        "key": "group_5d957af252a54",
        "title": "Test Field",
        "fields": [
            {
                "key": "field_5d957af36f1ca",
                "label": "Headline",
                "name": "hero-headline",
                "type": "textarea",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "50",
                    "class": "",
                    "id": ""
                },
                "default_value": "",
                "placeholder": "",
                "maxlength": "",
                "rows": 2,
                "new_lines": "br"
            }
        ],
        "location": [
            [
                {
                    "param": "post_type",
                    "operator": "==",
                    "value": "page"
                }
            ]
        ],
        "menu_order": 0,
        "position": "acf_after_title",
        "style": "default",
        "label_placement": "top",
        "instruction_placement": "label",
        "hide_on_screen": "",
        "active": true,
        "description": ""
    }
]

Please note that I have Gutenberg enabled in my site.

Thanks

**Comment by elliotcondon** [comment]
Hi @prajapatisagar 

Thanks for the clarification. This is expected behavior for the Gutenberg editor. It is no longer possible to add a metabox location outside of the "Bottom Panel" area.
