### ISSUE TITLE
'Fatal error: Cannot redeclare' function in ACF Blocks template file

### ISSUE THREAD

**Issue by tomhrtly** [elliotcondon/acf#752]
I'm using ACF Pro v5.8.0-beta3.

### Description

When following the instructions [here](https://www.advancedcustomfields.com/blog/acf-5-8-introducing-acf-blocks-for-gutenberg/) to create my own block using ACF, if I declare a function inside the `block-template.php` file, I sometimes get an error saying that the function has already been declared.

### Steps to Reproduce

1. Create your own block through the [guide](https://www.advancedcustomfields.com/blog/acf-5-8-introducing-acf-blocks-for-gutenberg/)
2. Add a function in the template for example:
`function mysitename_string() {`
`return 'hello';`
`}`
`mysitename_string();`

For some reason this does not happen all the time but there have been moments it has and to fix it I have had to wrap my function in the following:
`if ( !function_exists( 'mysitename_string' ) ) { ... }`

![capture](https://user-images.githubusercontent.com/35436443/53649474-23ecc500-3c3a-11e9-9e4c-b394a70216c0.PNG)

Not an urgent issue, but something that could be looked at before 5.8.

**Comment by elliotcondon** [comment]
Hi @tomhrtly 

Thanks for the topic.

This is expected PHP behavior. It is not possible to re-declare a function with the same name - even if you are declaring it within another function. Because of this, it is best practice (in PHP) to not create a "helper function" within a parent function.

**Comment by tomhrtly** [comment]
@elliotcondon Thanks for the reply, so would you recommend placing all functions that I need for my block inside the same file that I use to register the block instead of the block template file?

**Comment by elliotcondon** [comment]
Yes
