### ISSUE TITLE
Color Picker: Change return value from hexadecimal to RGB/HSL etc

### ISSUE THREAD

**Issue by tomhrtly** [elliotcondon/acf#753]
When using the color picker field in ACF, the return value is always hexadecimal. It would be helpful if you can choose how you want the color to be returned e.g. RGB or HSL etc.

**Comment by elliotcondon** [comment]
Hi @tomhrtly 

Great idea. I'll add this to our ideas list, bu in the meantime, be sure to checkout the "acf/format_value" filter to hook in and apply these value modifications: https://www.advancedcustomfields.com/resources/acf-format_value/

**Comment by tomhrtly** [comment]
@elliotcondon Okay will do, thanks!

**Comment by papazetis** [comment]
`function my_acf_format_value( $value, $post_id, $field ) {

	if ( $value[0] == '#' ) {
		$value = substr( $value, 1 );
	}
	if ( strlen( $value ) == 6 ) {
		list( $r, $g, $b ) = array( $value[0] . $value[1], $value[2] . $value[3], $value[4] . $value[5] );
	} elseif ( strlen( $value ) == 3 ) {
		list( $r, $g, $b ) = array( $value[0] . $value[0], $value[1] . $value[1], $value[2] . $value[2] );
	} else {
		return false;
	}
	$r = hexdec( $r );
	$g = hexdec( $g );
	$b = hexdec( $b );
	
	return array( 'red' => $r, 'green' => $g, 'blue' => $b );
           ===or===
	return 'rgb(' . $r . ', ' . $g . ', ' . $b . ')';
}

add_filter('acf/format_value/type=color_picker', 'my_acf_format_value', 10, 3);`
