### ISSUE TITLE
5.8.0-beta4: Repeater fields not saving

### ISSUE THREAD

**Issue by danielpost** [elliotcondon/acf#757]
Since upgrading to 5.8.0-beta4, our repeater fields aren't saving correctly anymore. They render in the editor when adding them, but don't get saved. They were working fine in 5.8.0-beta3 so my guess is something in the saving process changed which causes the issue.

Here's the code we use to register the block metaboxes, including the faulty repeater:

```php
<?php
$timeline = [
    'key' => 'timeline',
    'title' => __('Timeline', THEME_SLUG),
    'fields' => [
        [
            'key' => 'timeline_title',
            'label' => __('Title', THEME_SLUG),
            'name' => 'timeline_title',
            'type' => 'text',
        ],
        [
            'key' => 'timeline_caption',
            'label' => __('Caption', THEME_SLUG),
            'name' => 'timeline_caption',
            'type' => 'text',
        ],
        [
            'key' => 'timeline_items',
            'label' => __('Items', THEME_SLUG),
            'name' => 'timeline_items',
            'type' => 'repeater',
            'layout' => 'block',
            'sub_fields' => [
                [
                    'key' => 'timeline_items_year',
                    'label' => __('Year', THEME_SLUG),
                    'name' => 'year',
                    'type' => 'text',
                ],
                [
                    'key' => 'timeline_items_text',
                    'label' => __('Content', THEME_SLUG),
                    'name' => 'text',
                    'type' => 'textarea',
                ]
            ]
        ],
    ],
    'location' => [
        [
            [
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/timeline',
            ],
        ],
    ],
];

acf_add_local_field_group($timeline);
```

**Comment by danielpost** [comment]
I did some more testing. It appears that only the last repeater field on the page doesn't get saved (when adding two different Gutenberg blocks with a repeater, whichever one you add last doesn't get their values saved).

Furthermore, I get this error when trying to add the same block twice;

```
( ! ) Warning: Invalid argument supplied for foreach() in /app/public/wp-content/themes/theme-name/vendor/advanced-custom-fields-pro/pro/fields/class-acf-field-repeater.php on line 849
--

```

**Comment by elliotcondon** [comment]
Hi @danielpost 

Thanks for the bug report.
I'll perform some testing and let you know what I find.

**Comment by danielpost** [comment]
Thanks! I'm not ruling out that it's something related to our own setup either, but the fact that it only started occurring after upgrading from beta3 to beta4 leads me to believe it is at least somewhat related to the new update.

**Comment by elliotcondon** [comment]
Hi @danielpost 

I've just performed some testing with this issue and discovered the problem.
The issue here is specific to your field group setup in that your field keys are the same as your field names.

ACF requires all field keys to start with the prefix "field_", but also allows PHP registered fields to ignore that rule. Because your field keys also match your field names, ACF is incorrectly formatting your values when they have already been formatted (because ACF can't tell if the values are saved or being previewed).

To solve the problem, please change your field keys to not match your field names. I'll also consider how I can fix this from our end.

**Comment by elliotcondon** [comment]
@danielpost 

Good news. I was able to find a neat fix for this and will include in the next release.

**Comment by danielpost** [comment]
@elliotcondon Great, thanks so much!

Unrelated question: are they any plans to include some kind of live editing for textfields/textareas? Or live updates using subscribe?

**Comment by elliotcondon** [comment]
Hi @danielpost 

Good question. In the long run, yes.
Right now, we are keeping things simple, and using our PHP framework to update a dynamic block.
