### ISSUE TITLE
[SUGGESTION] Reorder the first 3 fields the of ACF field options

### ISSUE THREAD

**Issue by samjco** [elliotcondon/acf#759]
It would seem that it would make sense to have the choice of "field type" as the first selection, then the field label, and field name... Because some field types will change the landscape of the field group, for instance:

![image](https://user-images.githubusercontent.com/3359062/54234772-c9772280-44dd-11e9-9ce4-d7b40d0959b0.png)

I would even second that it would also be nice to have a "disable/mute" field and a "hide label" switch as field options.

**Comment by elliotcondon** [comment]
Hi @samjco 

Thanks for the suggestion.

I agree that choosing the "field type" should be the first action, but I am not sure about re-ordering the settings. 

Perhaps instead, we should introduce a UX step before the field settings are shown. This could take the form of selecting the field type from a list of icons - similar to how page builders handle blocks.

I would like to redesign the entire field settings UI int the future, and will keep this all in mind.

**Comment by samjco** [comment]
awesome!
