### ISSUE TITLE
5.8.0-beta4: Block assets loading on front end.

### ISSUE THREAD

**Issue by jakerambo** [elliotcondon/acf#761]
In pro/blocks.php line 383 scripts are enqueued using `enqueue_block_assets` which causes all of the editor assets to load on on the front end such as react, react-dom, redux, compose,  etc... 

This should be `enqueue_block_editor_assets` so that the block related scripts are only run in the admin.

**Comment by elliotcondon** [comment]
Thanks @jakerambo 

I've got this on my to-do and will fix shortly.

**Comment by elliotcondon** [comment]
Fixed.
