### ISSUE TITLE
The acf/validate_value filter does not validate fields using Gutenberg

### ISSUE THREAD

**Issue by ramiroazar** [elliotcondon/acf#763]
Custom validation using the `acf/validate_value` filter does not work when using Gutenberg, but works as expected when using the Classic Editor.

Is there a JavaScript equivalent that is supposed to be used instead since the release of Gutenberg?

WordPress `5.1.1`
Advanced Custom Fields PRO `5.7.13`

**Comment by elliotcondon** [comment]
Hi @ramiroazar 

Thanks for the question.

Validation is currently not working in the new Gutenberg editor and is something we will need to look into. Can you please clarify if your fields are in a standard metabox, or if you are trying out the ACF Blocks feature in 5.8.0-beta?

**Comment by ramiroazar** [comment]
I haven't had the pleasure to test ACF Blocks yet. The fields which are not being validated are just in a standard metabox.

**Comment by elliotcondon** [comment]
Thanks @ramiroazar. We hope to have this fixed in the near future, but unfortunately can confirm that validation is not yet working in the new Block editor.

**Comment by matthiaswagnerwy** [comment]
it would be great to notice that in you documentation (https://www.advancedcustomfields.com/resources/acf-validate_value/) to avoid frustrating time while searching for the reason it does not validate ;)

**Comment by elliotcondon** [comment]
Hi @matthiaswagnerwy

Absolutely. I do have some positive news to share about ACF validation in the Gutenberg editor. Please see this https://github.com/AdvancedCustomFields/acf/issues/113#issuecomment-616949241 for a solution prototype.
