### ISSUE TITLE
Undefined index: param in [...]\advanced-custom-fields\includes\compatibility.php on line 397

### ISSUE THREAD

**Issue by emidevelop** [elliotcondon/acf#766]
Hello Elliot, 
I just installed ACF v5.7.12 and without having had time to make this error appeared: 
Undefined index: param in [...]\advanced-custom-fields\includes\compatibility.php on line 397 
``
// migrate param
if( isset($replace[ $rule['param'] ]) ) {
    $field_group['location'][ $i ][ $j ]['param'] = $replace[ $rule['param'] ];
}
``
Do you have a fix for this problem? 
Thank you in advance

**Comment by elliotcondon** [comment]
Hi @emidevelop 

Did you solve the issue?

**Comment by emidevelop** [comment]
Hey Elliot, yes thank you very much, it was a mistake on my part it did not come from the plugins so i marked as resolved.

**Comment by mcodigital** [comment]
Hi guys, mind sharing what your experiences are? I am getting the same error on a page when I added a subfield on my repeater field.
