### ISSUE TITLE
Custom Fields not displaying in Preview when using Gutenberg

### ISSUE THREAD

**Issue by jweston491** [elliotcondon/acf#769]
When adding a custom field to a Post, Page or Custom Post Type, the field's contents are not rendered in the front-end when Previewing and using Gutenberg. 

What I did:
- Installed Twenty-Nineteen Theme and ACF.
- Created Custom Text Field "test_field"
- Added `the_field('test_field')` to `single.php`
- Published post, confirmed Field content is showing as expected on live page. 
- Clicked "Preview" on Post, field is not rendering. 

The issue goes away when I install and activate "Disable Gutenberg" plugin. 

Using WP 5.2 and PHP 7.2.9. The issue does not seem to happen in 5.1.1.

I opened a similar but separate issue back in January [here](https://github.com/AdvancedCustomFields/acf/issues/118), though this issue seems to be resolved with 5.2

**Comment by elliotcondon** [comment]
Hi @jweston491 

Thanks for the bug report. Can you confirm if by closing this issue, you were able to solve the problem? If not, I've got this on my to-do and will test in the coming week.

Thanks
Elliot

**Comment by jweston491** [comment]
Sorry about that @elliotcondon, I wasn’t sure if I had posted this in the right repo, hence the duplicate. *The issue is still occurring for me*, in the conditions I posted above. Sorry again for the confusion.
