### ISSUE TITLE
Make the tests folder public

### ISSUE THREAD

**Issue by Luc45** [elliotcondon/acf#772]
Hey Elliot!

First of all, whenever I get in contact with ACF crew I always repeat this: You guys are **AWESOME**.

Now, to the issue itself. I'm tasked of writing tests for a project in the company I work at. Some of these tests have to do with ACF, such as programmatically adding groups and fields and so on. I imagined that if I could have access to ACF tests, it could guide me write my own tests.

Looking at `acf.php` I saw this:

```
// Include tests.
//acf_include('tests/tests.php');
```

But I couldn't find the tests folder anywhere, not even here on GitHub. 

I wonder if this folder could be made public, to help us write tests that are related to ACF?

_(Did I already say you guys are awesome?)_

**Comment by elliotcondon** [comment]
Hi @Luc45 
Thanks for the topic.

Our "tests" folder contains a basic custom testing suite to run through functions.
It isn't something we wish to make public, as it doesn't use a testing library, console, etc.

**Comment by Luc45** [comment]
Alright, thanks for the clarification!

Keep up the good work buddy!
