### ISSUE TITLE
Is this repository up-to-date?

### ISSUE THREAD

**Issue by ezmiller** [elliotcondon/acf#773]
I have been hoping to reference the advanced-custom-fields repository as a submodule in another git repo, but it looks like this repository is behind the one in the official wordpress plugin hub: [link](https://wordpress.org/plugins/advanced-custom-fields/#developers).

I also looked at the version contained in the git mirror of the wordpress svn, but it's also behind it seems: https://github.com/wp-plugins/advanced-custom-fields

Is there any git version of the up-to-date plugin?

**Comment by elliotcondon** [comment]
Hi @ezmiller 

The ACF repo has moved here: https://github.com/advancedcustomfields/acf/
