### ISSUE TITLE
Bug with Links in WYSYWIG Using Blocks

### ISSUE THREAD

**Issue by lodog23** [elliotcondon/acf#775]
ACF 5.8
WordPress 5.2
Browser Chrome

I am having an issue with the insertion/editing of links in WYSYWIG fields when using a WYSYWIG field in a custom block. 

This issue came about when I created a custom block with a WYSYWIG field. When I add that custom block to a page and add a link to the field it works fine when I just type the link URL, but if I try to click the arrow, pencil or any icon in the link popup it proceeds to flicker, not allowing me to click any of these icons. 

I tested this issue in both Chrome and Firefox, and when I test it in Firefox I don't receive the bug, but in Chrome it does. 

I also found a workaround to this bug in Chrome by changing the zoom level of my browser to 200%. This allowed me to click the link icons.

This bug doesn't appear to happen in the default WordPress Gutenberg blocks, so I believe this is an issue with ACF.

Appreciate the help!

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/29789743/58177552-98039b80-7c72-11e9-9302-518c923a47f0.gif)

**Comment by elliotcondon** [comment]
Hi @lodog23 

Thanks for the detailed bug report.

The issue you are seeing is a conflict between the tinymce library and the Gutenberg editor.
Another developer has reported this issue over on the Gutenberg GitHub repo which you can follow here: https://github.com/WordPress/gutenberg/issues/14878

I'm not sure if this issue can be solved from our end, but looks to be fixable via the OSX scrollbar settings.
