### ISSUE TITLE
update_row and update_field return false if no change to value

### ISSUE THREAD

**Issue by jgmediadesign** [elliotcondon/acf#777]
when using update_row and update_field - if there is no change to the value the function returns false. 

According to the documentation (https://www.advancedcustomfields.com/resources/update_row/) this should only occur if there has been an error.

**Comment by elliotcondon** [comment]
Hi @jgmediadesign 

Thanks for the topic. Yes, similar to the (https://codex.wordpress.org/Function_Reference/update_post_meta) function, if the value passed to this function is the same as the value that is already in the database, this function returns false.

I'll update the docs to include this :)
