### ISSUE TITLE
PHP Warning: Running ACF Pro v5.6.9 and PHP 7.2

### ISSUE THREAD

**Issue by sharpenedpixels** [elliotcondon/acf#783]
Hi guys,

I've taken over a website for a client and they're having some issues, with what looks like, ACF Pro.

I've got a PHP warning popping up on the site. The warning is:

Warning: count(): Parameter must be an array or an object that implements Countable on line 1

I have a fair idea what bit of code is affecting this, but can't find a fix. Any chance you guys can help?

The code is below:

@php ($count = count(get_sub_field('faqs')))
@php ($half = round($count / 2))
@php ($i = 1)
@if (have_rows('faqs'))
  <section class="section-FAQ">
  <div class="container">

    <div class="row justify-content-between">
      <div id="accordian">

    @while(have_rows('faqs')) @php(the_row())
      <div class="card">
        <div class="card-header" id="headingOne">
          <a class="mb-0 collapsed button"  href="#collapse-{{$i}}" data-toggle="collapse" data-target="#collapse-{{$i}}" aria-expanded="false" aria-controls="collapse-{{$i}}">
            @php(the_sub_field('title'))
          </a>
        </div>

        <div id="collapse-{{$i}}" class="collapse show" aria-labelledby="heading-{{$i}}" data-parent="#accordion">
          <div class="card-body">
            <p>@php(the_sub_field('text'))</p>
          </div>
        </div>
      </div>
      @if ($i == $half)
      @endif
      @php ($i++)

    @endwhile
  </div>
</div>
</div>
</section>

@endif

It seems to be the very first line that is giving the issue. Seems this needs to be an array, I've tried a couple of things but to no avail. Any help would be much appreciated.

I have removed the first line all together and that seems to have removed the warning message, but I'm worried this might have knock on effects.

Any insight would be great, thanks Kevin.

**Comment by elliotcondon** [comment]
Hi @sharpenedpixels 

This kind of question would be best asked to the ACF support team here:
http://www.advancedcustomfields.com/contact/

The issue sounds simple. When the "faqs" sub field does not contain a value, it will return `false`. Passing `false` into the `count()` function will result in a PHP warning.

Please be sure to check if a value exists, and provide some graceful logic to accommodate `false` values.
