### ISSUE TITLE
oEmbed not working with youtube-nocookie.com

### ISSUE THREAD

**Issue by iannacone** [elliotcondon/acf#784]
The oEmbed is not showing the iframe with the domain www.youtube-nocookie.com.
[What www.youtube-nocookie.com is](https://stackoverflow.com/questions/42555450/how-to-embed-youtube-videos-without-cookies)

**Comment by elliotcondon** [comment]
Hi @iannacone 

The ACF oEmbed field uses the [WP Embed API](https://wordpress.org/support/article/embeds/) which may not yet work with the www.youtube-nocookie.com service.

It is possible to add custom providers - please see the linked doc for more info :)

**Comment by iannacone** [comment]
Thanks!
