### ISSUE TITLE
update_field() fails, if there is already a custom post inserted.

### ISSUE THREAD

**Issue by Elmzelji** [elliotcondon/acf#791]
I'm trying to update a custom post field, with no luck, when inserting everything runs smoothly, but when trying to update, nothing happens update_field() return false; I've tried with field name and tried with field key, but nothing, disabled all plugins and reverted to the twenty twenty theme and still same issue.

With field name;
update_field("banner_image", $event["IMAGE_LINK"], $id_event);

With field key;
update_field(get_field_object('banner_image', $id_event)["key"], $event["IMAGE_LINK"], $id_event);

**Comment by elliotcondon** [comment]
Hi @Elmzelji 

Thanks for the email,
Elliot here - ACF dev​​​.

Please note this GitHub repo is not intended for ACF support. If you are looking for assistance to write some custom functionality, please be sure to contact our support team here: https://www.advancedcustomfields.com/contact/

My advice would be to debug your variables.
In your first snippet, make sure that  the variables `$event["IMAGE_LINK"]` and `$id_event` are as expected. It will be helpful to provide these to support.

In your second snippet, make sure that  the variables `get_field_object('banner_image', $id_event)`, `$event["IMAGE_LINK"]` and `$id_event` are as expected. Same goes for providing them to support.

Wishing you all the best 👍
