### ISSUE TITLE
ACF Gutenberg block don't work without interaction (keypress)

### ISSUE THREAD

**Issue by kubiqsk** [elliotcondon/acf#793]
I have custom ACF gutenberg block with 1 text field with default value
When you add this block from Gutenberg then it is only
`<!-- wp:acf/my-custom-block /-->`
so it will not render anything on frontend...
but when I click inside input (focus) and press some arrow on keyboard (keypress) then it magically change to correct
`<!-- wp:acf/my-custom-block {"id":"block_5eb165f54ee72","name":"acf/my-custom-block","data":{"field_5eb162a46644a":"Lorem ipsum default text"},"mode":"auto"} /-->`
and then it works, so simply:
the problem is that I can not use my custom block just by adding it to the content, but I need to change something in it or do some interaction like keypress - mouse click is obviously not affecting anything so it is not "interaction" in this meaning...
so we need to fix first code insertion to contain default settings, values, etc...

**Comment by elliotcondon** [comment]
Hi @kubiqsk 

Thanks for the topic.

I'll add this to our to-do list and hope to investigate the problem shortly.

**Comment by elliotcondon** [comment]
Hi @kubiqsk 

I've just spent some time with this issue, but was not able to replicate the problem. In my testing, the block's field data is saved as expected without any need to focus or change an input.

Can you please share some more details about your block type?
- What are the "mode" and "supports" settings?

**Comment by kubiqsk** [comment]
Hi @elliotcondon 
Yes, it works in current version, thanks

**Comment by elliotcondon** [comment]
@kubiqsk Thanks for the reply. Can you please confirm that the issue is solved and we can close the ticket?
