### ISSUE TITLE
Attachment location rules not being respected

### ISSUE THREAD

**Issue by maketimetodesign** [elliotcondon/acf#795]
Hi, 

WordPress: **5.4.2**
ACF: **5.9.1**

I recently create some ACF fields to allow for some extra data on media library elements/attachments. I only need this to be shown on our projects CPT. I set this up as below, but found the rules are ignored. Has anyone else found this or am I missing something?!

Thanks in advance.

With the following rules the expected outcome doesn't match
<img width="1433" alt="Screenshot 2020-10-05 at 16 32 11" src="https://user-images.githubusercontent.com/1922302/95099980-823c2c80-0728-11eb-8231-8e3901f49743.png">

Rules aren't shown...
<img width="1425" alt="Screenshot 2020-10-05 at 16 32 41" src="https://user-images.githubusercontent.com/1922302/95099986-8405f000-0728-11eb-90f6-92f817412986.png">

If I remove the and clause of which post type to show then we're good.
<img width="1424" alt="Screenshot 2020-10-05 at 16 32 56" src="https://user-images.githubusercontent.com/1922302/95100039-98e28380-0728-11eb-8c94-5f96c70ea851.png">

As shown here...
<img width="1429" alt="Screenshot 2020-10-05 at 16 33 09" src="https://user-images.githubusercontent.com/1922302/95100052-9aac4700-0728-11eb-8585-746d585638d6.png">

**Comment by elliotcondon** [comment]
Hi @maketimetodesign 

Thanks for the post. What you are wanting to achieve won't be possible with our standard Location rules. Currently, the "Attachment" Location rule only allows you to specify "all" or a "specific mime type" as the different levels of control.

If you are wanting to display custom fields within the Media popup modal (or Gallery field sidebar) depending on the post being edited, you will need to register a custom Location rule with custom logic.

Luckily, we have a fresh guide on how you can get started with exactly that!
https://www.advancedcustomfields.com/resources/custom-location-rules/

**Comment by maketimetodesign** [comment]
Amazing thanks for the prompt response @elliotcondon, that's great. I did wonder if it might be a stretching what was possible with the location rules. I'll take a look at that article and rustle something up!

**Comment by maketimetodesign** [comment]
Hey @elliotcondon, I've tried to set this up, but the only variables set on $screen are the following:

`
    [lang] => 
    [ajax] => 
    [attachment_id] => 973
    [attachment] => 973
`

So I'm not sure how I can check against the post type that the current media form/attachment is being displayed on? Any ideas at all please? 

Thanks in advance!

**Comment by elliotcondon** [comment]
Aah yes, you will need to customize the "screen" args via the PHP filter "acf/location/screen" and add in a reference to the post being edited. Sometihng like this should work:

```
<?php
add_filter('acf/location/screen', 'my_acf_location_screen', 10, 1);
function my_acf_location_screen( $args ) {
	
	// Check if the current screen args are prepared for an attachment and add in a reference to the post being edited.
	if( isset($args['attachment_id']) ) {
		$args['_post_id'] = isset( $_POST['post_id'] ) ? $_POST['post_id'] : 0;
	}
	return $args;
}
```

With this filter added, you should be able to access that "_post_id" value from within the `ACF_Location:match()` method.
The value will exist within the `$screen` parameter like so:
`
public function match( $rule, $screen, $field_group ) {
	// Check screen args for "_post_id" which will exist when editing an attachment.
	// Return false for all other edit screens.
	if( isset($screen['_post_id']) ) {
		$post_id = $screen['_post_id'];
	} else {
		return false;
	}
	
	// Do some logic here and return true or false...
}
`

Hope that helps 👍.

**Comment by maketimetodesign** [comment]
Dude that more than helps! Absolute legend thanks for taking the time to share the code. Will go give this a whirl now. 
Look forward to digging deeper in to Location filters! 

Thanks again, much appreciated.

**Comment by elliotcondon** [comment]
Happy to help! This was a good question, and prompts me to update the docs with more info!

**Comment by maketimetodesign** [comment]
Awesome, glad it was a useful exercise, such a powerful and flexible addition! That did the trick and it's working perfectly. Thanks again!
