### ISSUE TITLE
[Feature request] acf block js templates

### ISSUE THREAD

**Issue by virgo79** [elliotcondon/acf#799]
Hi,
acf blocks relies on ajax to update a block preview everytime an acf field value changes for that block.

This architecure works very well, but it miss the "real time change" experience that would greatly improve the page building experience.
Gutenberg is based on react and it is able to offer this experience natively.

I would like to suggest to extending the acf block architecture, giving developers the opportunity to create js templates for acf blocks. 
Js templates fo acf blocks cold be used to upadate block previews in real time without having to make ajax/rest server calls.

This could be an optional feature for developers.

A similar architecure is currently builtin  in the wordpress customizer, offering developers the opportunity of adding and removing customizer controls using javascript, while in customizer.

I think this solution would definitely fill the gap between acf blocks and gutenberg blocks.

**Comment by elliotcondon** [comment]
Hi @virgo79 

I completely agree that the true power of Gutenberg content editing lies in the instantaneous visual feedback between content and design, however, this suggestion lies outside the scope of our PHP focused plugin.

Our primary goal with Advanced Custom Fields is to support developers though a tried-and-tested PHP based custom field framework. Whilst I acknowledge that WordPress is in a current transition from "classic" content editing to a more "real time" React + Rest API combination, our plugin is not looking to solve this new problem.
